// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package dashboards_filters

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// DashboardsFilters handles communication with the Dashboards Filters methods of the
	// ThousandEyes API.
	DashboardsFilters struct {
		client client.Client
	}
)

// NewDashboardsFilters returns a Dashboards Filters service bound to client.
func NewDashboardsFilters(client client.Client) *DashboardsFilters {
	return &DashboardsFilters{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Dashboards Filters
// -----------------------------------------------------------------------------

// GetDashboardsFilters list dashboard filters.
// URL: GET /dashboards/filters
// Optional query params: searchPattern
//
// Returns a list of dashboard filters and its context within your account
// group.
func (s *DashboardsFilters) GetDashboardsFilters(ctx context.Context, opts ...client.RequestOption) (*ApiContextFiltersResponse, *resty.Response, error) {

	endpoint := "/dashboards/filters"

	var result ApiContextFiltersResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateDashboardFilter create dashboard filter.
// URL: POST /dashboards/filters
//
// Creates a new dashboard filter in your account group.
func (s *DashboardsFilters) CreateDashboardFilter(ctx context.Context, request *ApiContextFilterRequest, opts ...client.RequestOption) (*ApiContextFilterResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/dashboards/filters"

	var result ApiContextFilterResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteDashboardFilter delete dashboard filter.
// URL: DELETE /dashboards/filters/{id}
//
// Deletes a dashboard filter using the `filterId` provided in the request.
func (s *DashboardsFilters) DeleteDashboardFilter(ctx context.Context, id string, opts ...client.RequestOption) (*resty.Response, error) {
	if id == "" {
		return nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/dashboards/filters/%s", id)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetDashboardFilter get dashboard filter.
// URL: GET /dashboards/filters/{id}
//
// Returns a list of data source filters and their metadata within the
// dashboard filter.
func (s *DashboardsFilters) GetDashboardFilter(ctx context.Context, id string, opts ...client.RequestOption) (*ApiContextFilterResponse, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/dashboards/filters/%s", id)

	var result ApiContextFilterResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateDashboardFilter update dashboard filter.
// URL: PUT /dashboards/filters/{id}
//
// Updates an existing dashboard filter in your account group.
func (s *DashboardsFilters) UpdateDashboardFilter(ctx context.Context, id string, request *ApiContextFilterRequest, opts ...client.RequestOption) (*ApiContextFilterResponse, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/dashboards/filters/%s", id)

	var result ApiContextFilterResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
