// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package autonomous_system_prefixes

import "fmt"

// PrefixAssociationType is an enumeration from the OpenAPI specification. The
// method by which the prefix is associated with the Autonomous System. It is
// open: values outside the enumeration decode and compare as their underlying
// string.
type PrefixAssociationType string

// PrefixAssociationType values.
const (
	PrefixAssociationTypeAnnounced PrefixAssociationType = "announced"
	PrefixAssociationTypeRpki      PrefixAssociationType = "rpki"
	PrefixAssociationTypeAllocated PrefixAssociationType = "allocated"
	PrefixAssociationTypeUnknown   PrefixAssociationType = "unknown"
)

// String returns the value as the API spells it, or "PrefixAssociationType(v)" for
// values outside the enumeration.
func (v PrefixAssociationType) String() string {
	switch v {
	case PrefixAssociationTypeAnnounced:
		return "announced"
	case PrefixAssociationTypeRpki:
		return "rpki"
	case PrefixAssociationTypeAllocated:
		return "allocated"
	case PrefixAssociationTypeUnknown:
		return "unknown"
	}
	return fmt.Sprintf("PrefixAssociationType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v PrefixAssociationType) IsKnown() bool {
	switch v {
	case PrefixAssociationTypeAnnounced:
		return true
	case PrefixAssociationTypeRpki:
		return true
	case PrefixAssociationTypeAllocated:
		return true
	case PrefixAssociationTypeUnknown:
		return true
	}
	return false
}

// PrefixAssociationTypeValues returns every value the specification declares, in
// specification order.
func PrefixAssociationTypeValues() []PrefixAssociationType {
	return []PrefixAssociationType{
		PrefixAssociationTypeAnnounced,
		PrefixAssociationTypeRpki,
		PrefixAssociationTypeAllocated,
		PrefixAssociationTypeUnknown,
	}
}
