// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package usage

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// Usage handles communication with the Usage methods of the
	// ThousandEyes API.
	Usage struct {
		client client.Client
	}
)

// NewUsage returns a Usage service bound to client.
func NewUsage(client client.Client) *Usage {
	return &Usage{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Usage
// -----------------------------------------------------------------------------

// GetUsage get usage information for the last month.
// URL: GET /usage
// Optional query params: expand
//
// This operation returns usage for the current period.
func (s *Usage) GetUsage(ctx context.Context, opts ...client.RequestOption) (*ResourceUsage, *resty.Response, error) {

	endpoint := "/usage"

	var result ResourceUsage

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetEnterpriseAgentsUnitsUsage get enterprise agent usage.
// URL: GET /usage/units/enterprise-agents
// Optional query params: startDate, endDate, cursor
//
// This operation returns the organization's enterprise agents usage for a
// specific time period, or the curent billing cycle if no time period is
// specified.
func (s *Usage) GetEnterpriseAgentsUnitsUsage(ctx context.Context, opts ...client.RequestOption) (*EnterpriseAgentsUsage, *resty.Response, error) {

	endpoint := "/usage/units/enterprise-agents"

	var result EnterpriseAgentsUsage

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	// The collection arrives across pages linked by _links.next. Fetching only
	// the first would silently truncate the result, so every page is merged.
	// Bound the walk with client.WithMaxPages when that is not wanted.
	var items []EnterpriseAgentUnitsByTestOwnerAccountGroup
	merge := func(page []byte) error {
		var batch []EnterpriseAgentUnitsByTestOwnerAccountGroup
		if err := json.Unmarshal(page, &batch); err != nil {
			return fmt.Errorf("decoding breakdowns page: %w", err)
		}
		items = append(items, batch...)
		return nil
	}

	resp, err := req.GetPaginated(endpoint, "breakdowns", merge)
	if err != nil {
		return nil, resp, err
	}
	result.Breakdowns = items

	return &result, resp, nil
}

// GetTestsUnitsUsage get cloud and enterprise agents units usage.
// URL: GET /usage/units/tests
// Optional query params: startDate, endDate, cursor
//
// This operation returns the cloud and enterprise agents usage for all the
// tests for a specific time period, or the curent billing cycle if no time
// period is specified.
func (s *Usage) GetTestsUnitsUsage(ctx context.Context, opts ...client.RequestOption) (*TestsUsage, *resty.Response, error) {

	endpoint := "/usage/units/tests"

	var result TestsUsage

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	// The collection arrives across pages linked by _links.next. Fetching only
	// the first would silently truncate the result, so every page is merged.
	// Bound the walk with client.WithMaxPages when that is not wanted.
	var items []UnitsByTests
	merge := func(page []byte) error {
		var batch []UnitsByTests
		if err := json.Unmarshal(page, &batch); err != nil {
			return fmt.Errorf("decoding breakdowns page: %w", err)
		}
		items = append(items, batch...)
		return nil
	}

	resp, err := req.GetPaginated(endpoint, "breakdowns", merge)
	if err != nil {
		return nil, resp, err
	}
	result.Breakdowns = items

	return &result, resp, nil
}
