// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package agent_to_server_tests

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// AgentToServerTests handles communication with the Agent to Server Tests methods of the
	// ThousandEyes API.
	AgentToServerTests struct {
		client client.Client
	}
)

// NewAgentToServerTests returns a Agent to Server Tests service bound to client.
func NewAgentToServerTests(client client.Client) *AgentToServerTests {
	return &AgentToServerTests{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Agent to Server Tests
// -----------------------------------------------------------------------------

// GetAgentToServerTests list Agent to Server tests.
// URL: GET /tests/agent-to-server
//
// Returns a list of Agent to Server tests and saved events.
func (s *AgentToServerTests) GetAgentToServerTests(ctx context.Context, opts ...client.RequestOption) (*ResourceAgentToServerTests, *resty.Response, error) {

	endpoint := "/tests/agent-to-server"

	var result ResourceAgentToServerTests

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateAgentToServerTest create Agent to Server test.
// URL: POST /tests/agent-to-server
// Optional query params: expand
//
// Creates a new Agent to Server test.
func (s *AgentToServerTests) CreateAgentToServerTest(ctx context.Context, request *AgentToServerTestRequest, opts ...client.RequestOption) (*AgentToServerTestResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/tests/agent-to-server"

	var result AgentToServerTestResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteAgentToServerTest delete Agent to Server test.
// URL: DELETE /tests/agent-to-server/{testId}
//
// Deletes an Agent to Server test.
func (s *AgentToServerTests) DeleteAgentToServerTest(ctx context.Context, testId string, opts ...client.RequestOption) (*resty.Response, error) {
	if testId == "" {
		return nil, fmt.Errorf("testId is required")
	}

	endpoint := fmt.Sprintf("/tests/agent-to-server/%s", testId)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetAgentToServerTest get Agent to Server test.
// URL: GET /tests/agent-to-server/{testId}
// Optional query params: versionId, expand
//
// Returns details for a Agent to Server test, including name, intervals,
// targets, alert rules and agents.
func (s *AgentToServerTests) GetAgentToServerTest(ctx context.Context, testId string, opts ...client.RequestOption) (*AgentToServerTestResponse, *resty.Response, error) {
	if testId == "" {
		return nil, nil, fmt.Errorf("testId is required")
	}

	endpoint := fmt.Sprintf("/tests/agent-to-server/%s", testId)

	var result AgentToServerTestResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateAgentToServerTest update Agent to Server test.
// URL: PUT /tests/agent-to-server/{testId}
// Optional query params: expand
//
// Updates an Agent to Server test.
func (s *AgentToServerTests) UpdateAgentToServerTest(ctx context.Context, testId string, request *UpdateAgentToServerTestRequest, opts ...client.RequestOption) (*AgentToServerTestResponse, *resty.Response, error) {
	if testId == "" {
		return nil, nil, fmt.Errorf("testId is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/tests/agent-to-server/%s", testId)

	var result AgentToServerTestResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
