// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package internet_insights_catalog_providers

// ApiAsn is generated from the OpenAPI specification.
type ApiAsn struct {
	// ASN (Autonomous Systems Number)
	ID *int `json:"id,omitempty"`
	// ASN (Autonomous Systems Number) name
	Name *string `json:"name,omitempty"`
}

// ApiCatalogProvider Catalog provider
type ApiCatalogProvider struct {
	Links *SelfLinks `json:"_links,omitempty"`
	// The number of ASN's covered by the provider.
	AsnsCount *int `json:"asnsCount,omitempty"`
	// The number of countries covered by the provider.
	CountriesCount *int      `json:"countriesCount,omitempty"`
	DataType       DataType  `json:"dataType,omitempty"`
	ID             CatalogId `json:"id,omitempty"`
	// Indicates whether the catalog provider is included in the licensed packages.
	Included *bool `json:"included,omitempty"`
	// The number of interfaces covered by the provider.
	InterfacesCount *int `json:"interfacesCount,omitempty"`
	// The number of locations covered by the provider.
	LocationsCount *int         `json:"locationsCount,omitempty"`
	ProviderName   ProviderName `json:"providerName,omitempty"`
	ProviderType   ProviderType `json:"providerType,omitempty"`
	Region         Region       `json:"region,omitempty"`
}

// ApiCatalogProviderDetails is generated from the OpenAPI specification.
type ApiCatalogProviderDetails struct {
	Links *SelfLinks `json:"_links,omitempty"`
	// List of ASN's covered by the Provider.
	Asns     []ApiAsn  `json:"asns,omitempty"`
	DataType DataType  `json:"dataType,omitempty"`
	ID       CatalogId `json:"id,omitempty"`
	// List of locations covered by the Provider.
	Locations    []ProviderLocation `json:"locations,omitempty"`
	ProviderName ProviderName       `json:"providerName,omitempty"`
	ProviderType ProviderType       `json:"providerType,omitempty"`
	Region       Region             `json:"region,omitempty"`
}

// ApiCatalogProviderFilter Advanced filter query used to filter the response.
// The provider name, location, asn can be partial names. Can filter on: -
// Provider name - Provider type - Region - Location - ASN - included
type ApiCatalogProviderFilter struct {
	// Name of the ASN (Autonomous Systems Number) covered by providers.
	Asn *string `json:"asn,omitempty"`
	// Indicates whether the catalog provider is included in the licensed packages.
	Included *bool `json:"included,omitempty"`
	// Location of the catalog provider.
	Location *string `json:"location,omitempty"`
	// The name of the catalog provider.
	ProviderName *string `json:"providerName,omitempty"`
	// The type of catalog provider.
	ProviderType *string `json:"providerType,omitempty"`
	// The catalog provider region.
	Region *string `json:"region,omitempty"`
}

// ApiCatalogProviderResponse is generated from the OpenAPI specification.
type ApiCatalogProviderResponse struct {
	Links *SelfLinks `json:"_links,omitempty"`
	// List of catalog providers.
	Providers []ApiCatalogProvider `json:"providers,omitempty"`
}

// CatalogId The catalog provider ID.
type CatalogId string

// DataType The type of data produced by the provider.
type DataType string

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// ProviderLocation is generated from the OpenAPI specification.
type ProviderLocation struct {
	// The number of interfaces covered by the Provider at this location.
	InterfacesCount *int `json:"interfacesCount,omitempty"`
	// The location covered by the Provider.
	Location *string `json:"location,omitempty"`
}

// ProviderName The name of the catalog provider.
type ProviderName string

// ProviderType The type of catalog provider.
type ProviderType string

// Region The catalog provider region.
type Region string

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self *Link `json:"self,omitempty"`
}
