// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.103)

package api_token

// ApiToken is generated from the OpenAPI specification.
type ApiToken struct {
	// The API token for your account.
	BearerToken *string `json:"bearerToken,omitempty"`
	// The date and time when the generated API token will expire.
	ValidUntil *string `json:"validUntil,omitempty"`
}
