// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package api_token

import (
	"context"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// APIToken handles communication with the API Token methods of the
	// ThousandEyes API.
	APIToken struct {
		client client.Client
	}
)

// NewAPIToken returns a API Token service bound to client.
func NewAPIToken(client client.Client) *APIToken {
	return &APIToken{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - API Token
// -----------------------------------------------------------------------------

// RegenerateApiToken regenerate API token.
// URL: POST /api-tokens
//
// Regenerates the bearer token for your account.
func (s *APIToken) RegenerateApiToken(ctx context.Context, opts ...client.RequestOption) (*ApiToken, *resty.Response, error) {

	endpoint := "/api-tokens"

	var result ApiToken

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
