// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package endpoint_agent_labels

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// EndpointAgentLabels handles communication with the Endpoint Agent Labels methods of the
	// ThousandEyes API.
	EndpointAgentLabels struct {
		client client.Client
	}
)

// NewEndpointAgentLabels returns a Endpoint Agent Labels service bound to client.
func NewEndpointAgentLabels(client client.Client) *EndpointAgentLabels {
	return &EndpointAgentLabels{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Endpoint Agent Labels
// -----------------------------------------------------------------------------

// GetEndpointLabels list labels.
// URL: GET /endpoint/labels
// Optional query params: max, cursor, expand
//
// Returns a list of labels.
func (s *EndpointAgentLabels) GetEndpointLabels(ctx context.Context, opts ...client.RequestOption) (*Labels, *resty.Response, error) {

	endpoint := "/endpoint/labels"

	var result Labels

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateEndpointLabel create label.
// URL: POST /endpoint/labels
//
// Creates a new label.
func (s *EndpointAgentLabels) CreateEndpointLabel(ctx context.Context, request *LabelRequest, opts ...client.RequestOption) (*LabelResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/endpoint/labels"

	var result LabelResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteEndpointLabel delete label.
// URL: DELETE /endpoint/labels/{id}
//
// Deletes the label from your account.
func (s *EndpointAgentLabels) DeleteEndpointLabel(ctx context.Context, opts ...client.RequestOption) (*resty.Response, error) {

	endpoint := "/endpoint/labels/{id}"

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetEndpointLabel retrieve label.
// URL: GET /endpoint/labels/{id}
// Optional query params: expand
//
// Returns a single label using its ID.
func (s *EndpointAgentLabels) GetEndpointLabel(ctx context.Context, opts ...client.RequestOption) (*LabelResponse, *resty.Response, error) {

	endpoint := "/endpoint/labels/{id}"

	var result LabelResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateEndpointLabel update label.
// URL: PATCH /endpoint/labels/{id}
//
// Updates a label using its ID.
func (s *EndpointAgentLabels) UpdateEndpointLabel(ctx context.Context, request *Label, opts ...client.RequestOption) (*LabelResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/endpoint/labels/{id}"

	var result LabelResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Patch(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
