// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package page_load_tests

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// PageLoadTests handles communication with the Page Load Tests methods of the
	// ThousandEyes API.
	PageLoadTests struct {
		client client.Client
	}
)

// NewPageLoadTests returns a Page Load Tests service bound to client.
func NewPageLoadTests(client client.Client) *PageLoadTests {
	return &PageLoadTests{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Page Load Tests
// -----------------------------------------------------------------------------

// GetPageLoadTests list Page Load tests.
// URL: GET /tests/page-load
//
// Returns a list of all Page Load tests and saved events.
func (s *PageLoadTests) GetPageLoadTests(ctx context.Context, opts ...client.RequestOption) (*ResourcePageLoadTests, *resty.Response, error) {

	endpoint := "/tests/page-load"

	var result ResourcePageLoadTests

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreatePageLoadTest create Page Load test.
// URL: POST /tests/page-load
// Optional query params: expand
//
// Creates a new Page Load test.
func (s *PageLoadTests) CreatePageLoadTest(ctx context.Context, request *PageLoadTestRequest, opts ...client.RequestOption) (*PageLoadTestResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/tests/page-load"

	var result PageLoadTestResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeletePageLoadTest delete Page Load test.
// URL: DELETE /tests/page-load/{testId}
//
// Deletes the specified Page Load test.
func (s *PageLoadTests) DeletePageLoadTest(ctx context.Context, testId string, opts ...client.RequestOption) (*resty.Response, error) {
	if testId == "" {
		return nil, fmt.Errorf("testId is required")
	}

	endpoint := fmt.Sprintf("/tests/page-load/%s", testId)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetPageLoadTest get Page Load test.
// URL: GET /tests/page-load/{testId}
// Optional query params: versionId, expand
//
// Returns details for a Page Load test, including name, intervals, targets,
// alert rules and agents.
func (s *PageLoadTests) GetPageLoadTest(ctx context.Context, testId string, opts ...client.RequestOption) (*PageLoadTestResponse, *resty.Response, error) {
	if testId == "" {
		return nil, nil, fmt.Errorf("testId is required")
	}

	endpoint := fmt.Sprintf("/tests/page-load/%s", testId)

	var result PageLoadTestResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdatePageLoadTest update Page Load test.
// URL: PUT /tests/page-load/{testId}
// Optional query params: expand
//
// Updates a Page Load test.
func (s *PageLoadTests) UpdatePageLoadTest(ctx context.Context, testId string, request *PageLoadTestRequest, opts ...client.RequestOption) (*PageLoadTestResponse, *resty.Response, error) {
	if testId == "" {
		return nil, nil, fmt.Errorf("testId is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/tests/page-load/%s", testId)

	var result PageLoadTestResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
