// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package events

import (
	"encoding/json"
	"fmt"
)

// EventDetail is a discriminated union from the OpenAPI specification. The
// type property selects which variant is populated.
//
// Build one with a NewEventDetailFrom… constructor, which sets the discriminator
// and the variant together. Setting them by hand risks disagreement, which
// MarshalJSON reports rather than silently dropping.
type EventDetail struct {
	// Type names which variant below is populated.
	Type EventDetailType `json:"type"`

	// Agent is set when type is "agent".
	Agent *AgentEventDetail `json:"-"`
	// AgentBranch is set when type is "agent-branch".
	AgentBranch *AgentBranchEventDetail `json:"-"`
	// AgentLocal is set when type is "agent-local".
	AgentLocal *AgentLocalEventDetail `json:"-"`
	// Application is set when type is "application".
	Application *ApplicationEventDetail `json:"-"`
	// Dns is set when type is "dns".
	Dns *DnsEventDetail `json:"-"`
	// DnsName is set when type is "dns-name".
	DnsName *DnsNameEventDetail `json:"-"`
	// DnsServer is set when type is "dns-server".
	DnsServer *DnsServerEventDetail `json:"-"`
	// Domain is set when type is "domain".
	Domain *DomainEventDetail `json:"-"`
	// Gateway is set when type is "gateway".
	Gateway *GatewayEventDetail `json:"-"`
	// NameServer is set when type is "name-server".
	NameServer *NameServerEventDetail `json:"-"`
	// Network is set when type is "network".
	Network *NetworkEventDetail `json:"-"`
	// NetworkPop is set when type is "network-pop".
	NetworkPop *NetworkPopEventDetail `json:"-"`
	// Proxy is set when type is "proxy".
	Proxy *ProxyEventDetail `json:"-"`
	// Target is set when type is "target".
	Target *TargetEventDetail `json:"-"`
	// TargetNetwork is set when type is "target-network".
	TargetNetwork *TargetNetworkEventDetail `json:"-"`
	// Vpn is set when type is "vpn".
	Vpn *VpnEventDetail `json:"-"`
	// Wireless is set when type is "wireless".
	Wireless *WirelessEventDetail `json:"-"`

	// Raw is the payload as received. It is always populated, and is the only
	// way to reach a variant added to the API after this code was generated.
	Raw json.RawMessage `json:"-"`
}

// NewEventDetailFromAgent returns a EventDetail holding v.
func NewEventDetailFromAgent(v AgentEventDetail) EventDetail {
	return EventDetail{
		Type:  EventDetailTypeAgent,
		Agent: &v,
	}
}

// IsAgent reports whether the discriminator selects the
// "agent" variant.
func (u EventDetail) IsAgent() bool {
	return u.Type == EventDetailTypeAgent
}

// GetAgent returns the "agent" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetAgent() (*AgentEventDetail, bool) {
	if !u.IsAgent() || u.Agent == nil {
		return nil, false
	}
	return u.Agent, true
}

// NewEventDetailFromAgentBranch returns a EventDetail holding v.
func NewEventDetailFromAgentBranch(v AgentBranchEventDetail) EventDetail {
	return EventDetail{
		Type:        EventDetailTypeAgentBranch,
		AgentBranch: &v,
	}
}

// IsAgentBranch reports whether the discriminator selects the
// "agent-branch" variant.
func (u EventDetail) IsAgentBranch() bool {
	return u.Type == EventDetailTypeAgentBranch
}

// GetAgentBranch returns the "agent-branch" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetAgentBranch() (*AgentBranchEventDetail, bool) {
	if !u.IsAgentBranch() || u.AgentBranch == nil {
		return nil, false
	}
	return u.AgentBranch, true
}

// NewEventDetailFromAgentLocal returns a EventDetail holding v.
func NewEventDetailFromAgentLocal(v AgentLocalEventDetail) EventDetail {
	return EventDetail{
		Type:       EventDetailTypeAgentLocal,
		AgentLocal: &v,
	}
}

// IsAgentLocal reports whether the discriminator selects the
// "agent-local" variant.
func (u EventDetail) IsAgentLocal() bool {
	return u.Type == EventDetailTypeAgentLocal
}

// GetAgentLocal returns the "agent-local" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetAgentLocal() (*AgentLocalEventDetail, bool) {
	if !u.IsAgentLocal() || u.AgentLocal == nil {
		return nil, false
	}
	return u.AgentLocal, true
}

// NewEventDetailFromApplication returns a EventDetail holding v.
func NewEventDetailFromApplication(v ApplicationEventDetail) EventDetail {
	return EventDetail{
		Type:        EventDetailTypeApplication,
		Application: &v,
	}
}

// IsApplication reports whether the discriminator selects the
// "application" variant.
func (u EventDetail) IsApplication() bool {
	return u.Type == EventDetailTypeApplication
}

// GetApplication returns the "application" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetApplication() (*ApplicationEventDetail, bool) {
	if !u.IsApplication() || u.Application == nil {
		return nil, false
	}
	return u.Application, true
}

// NewEventDetailFromDns returns a EventDetail holding v.
func NewEventDetailFromDns(v DnsEventDetail) EventDetail {
	return EventDetail{
		Type: EventDetailTypeDns,
		Dns:  &v,
	}
}

// IsDns reports whether the discriminator selects the
// "dns" variant.
func (u EventDetail) IsDns() bool {
	return u.Type == EventDetailTypeDns
}

// GetDns returns the "dns" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetDns() (*DnsEventDetail, bool) {
	if !u.IsDns() || u.Dns == nil {
		return nil, false
	}
	return u.Dns, true
}

// NewEventDetailFromDnsName returns a EventDetail holding v.
func NewEventDetailFromDnsName(v DnsNameEventDetail) EventDetail {
	return EventDetail{
		Type:    EventDetailTypeDnsName,
		DnsName: &v,
	}
}

// IsDnsName reports whether the discriminator selects the
// "dns-name" variant.
func (u EventDetail) IsDnsName() bool {
	return u.Type == EventDetailTypeDnsName
}

// GetDnsName returns the "dns-name" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetDnsName() (*DnsNameEventDetail, bool) {
	if !u.IsDnsName() || u.DnsName == nil {
		return nil, false
	}
	return u.DnsName, true
}

// NewEventDetailFromDnsServer returns a EventDetail holding v.
func NewEventDetailFromDnsServer(v DnsServerEventDetail) EventDetail {
	return EventDetail{
		Type:      EventDetailTypeDnsServer,
		DnsServer: &v,
	}
}

// IsDnsServer reports whether the discriminator selects the
// "dns-server" variant.
func (u EventDetail) IsDnsServer() bool {
	return u.Type == EventDetailTypeDnsServer
}

// GetDnsServer returns the "dns-server" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetDnsServer() (*DnsServerEventDetail, bool) {
	if !u.IsDnsServer() || u.DnsServer == nil {
		return nil, false
	}
	return u.DnsServer, true
}

// NewEventDetailFromDomain returns a EventDetail holding v.
func NewEventDetailFromDomain(v DomainEventDetail) EventDetail {
	return EventDetail{
		Type:   EventDetailTypeDomain,
		Domain: &v,
	}
}

// IsDomain reports whether the discriminator selects the
// "domain" variant.
func (u EventDetail) IsDomain() bool {
	return u.Type == EventDetailTypeDomain
}

// GetDomain returns the "domain" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetDomain() (*DomainEventDetail, bool) {
	if !u.IsDomain() || u.Domain == nil {
		return nil, false
	}
	return u.Domain, true
}

// NewEventDetailFromGateway returns a EventDetail holding v.
func NewEventDetailFromGateway(v GatewayEventDetail) EventDetail {
	return EventDetail{
		Type:    EventDetailTypeGateway,
		Gateway: &v,
	}
}

// IsGateway reports whether the discriminator selects the
// "gateway" variant.
func (u EventDetail) IsGateway() bool {
	return u.Type == EventDetailTypeGateway
}

// GetGateway returns the "gateway" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetGateway() (*GatewayEventDetail, bool) {
	if !u.IsGateway() || u.Gateway == nil {
		return nil, false
	}
	return u.Gateway, true
}

// NewEventDetailFromNameServer returns a EventDetail holding v.
func NewEventDetailFromNameServer(v NameServerEventDetail) EventDetail {
	return EventDetail{
		Type:       EventDetailTypeNameServer,
		NameServer: &v,
	}
}

// IsNameServer reports whether the discriminator selects the
// "name-server" variant.
func (u EventDetail) IsNameServer() bool {
	return u.Type == EventDetailTypeNameServer
}

// GetNameServer returns the "name-server" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetNameServer() (*NameServerEventDetail, bool) {
	if !u.IsNameServer() || u.NameServer == nil {
		return nil, false
	}
	return u.NameServer, true
}

// NewEventDetailFromNetwork returns a EventDetail holding v.
func NewEventDetailFromNetwork(v NetworkEventDetail) EventDetail {
	return EventDetail{
		Type:    EventDetailTypeNetwork,
		Network: &v,
	}
}

// IsNetwork reports whether the discriminator selects the
// "network" variant.
func (u EventDetail) IsNetwork() bool {
	return u.Type == EventDetailTypeNetwork
}

// GetNetwork returns the "network" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetNetwork() (*NetworkEventDetail, bool) {
	if !u.IsNetwork() || u.Network == nil {
		return nil, false
	}
	return u.Network, true
}

// NewEventDetailFromNetworkPop returns a EventDetail holding v.
func NewEventDetailFromNetworkPop(v NetworkPopEventDetail) EventDetail {
	return EventDetail{
		Type:       EventDetailTypeNetworkPop,
		NetworkPop: &v,
	}
}

// IsNetworkPop reports whether the discriminator selects the
// "network-pop" variant.
func (u EventDetail) IsNetworkPop() bool {
	return u.Type == EventDetailTypeNetworkPop
}

// GetNetworkPop returns the "network-pop" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetNetworkPop() (*NetworkPopEventDetail, bool) {
	if !u.IsNetworkPop() || u.NetworkPop == nil {
		return nil, false
	}
	return u.NetworkPop, true
}

// NewEventDetailFromProxy returns a EventDetail holding v.
func NewEventDetailFromProxy(v ProxyEventDetail) EventDetail {
	return EventDetail{
		Type:  EventDetailTypeProxy,
		Proxy: &v,
	}
}

// IsProxy reports whether the discriminator selects the
// "proxy" variant.
func (u EventDetail) IsProxy() bool {
	return u.Type == EventDetailTypeProxy
}

// GetProxy returns the "proxy" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetProxy() (*ProxyEventDetail, bool) {
	if !u.IsProxy() || u.Proxy == nil {
		return nil, false
	}
	return u.Proxy, true
}

// NewEventDetailFromTarget returns a EventDetail holding v.
func NewEventDetailFromTarget(v TargetEventDetail) EventDetail {
	return EventDetail{
		Type:   EventDetailTypeTarget,
		Target: &v,
	}
}

// IsTarget reports whether the discriminator selects the
// "target" variant.
func (u EventDetail) IsTarget() bool {
	return u.Type == EventDetailTypeTarget
}

// GetTarget returns the "target" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetTarget() (*TargetEventDetail, bool) {
	if !u.IsTarget() || u.Target == nil {
		return nil, false
	}
	return u.Target, true
}

// NewEventDetailFromTargetNetwork returns a EventDetail holding v.
func NewEventDetailFromTargetNetwork(v TargetNetworkEventDetail) EventDetail {
	return EventDetail{
		Type:          EventDetailTypeTargetNetwork,
		TargetNetwork: &v,
	}
}

// IsTargetNetwork reports whether the discriminator selects the
// "target-network" variant.
func (u EventDetail) IsTargetNetwork() bool {
	return u.Type == EventDetailTypeTargetNetwork
}

// GetTargetNetwork returns the "target-network" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetTargetNetwork() (*TargetNetworkEventDetail, bool) {
	if !u.IsTargetNetwork() || u.TargetNetwork == nil {
		return nil, false
	}
	return u.TargetNetwork, true
}

// NewEventDetailFromVpn returns a EventDetail holding v.
func NewEventDetailFromVpn(v VpnEventDetail) EventDetail {
	return EventDetail{
		Type: EventDetailTypeVpn,
		Vpn:  &v,
	}
}

// IsVpn reports whether the discriminator selects the
// "vpn" variant.
func (u EventDetail) IsVpn() bool {
	return u.Type == EventDetailTypeVpn
}

// GetVpn returns the "vpn" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetVpn() (*VpnEventDetail, bool) {
	if !u.IsVpn() || u.Vpn == nil {
		return nil, false
	}
	return u.Vpn, true
}

// NewEventDetailFromWireless returns a EventDetail holding v.
func NewEventDetailFromWireless(v WirelessEventDetail) EventDetail {
	return EventDetail{
		Type:     EventDetailTypeWireless,
		Wireless: &v,
	}
}

// IsWireless reports whether the discriminator selects the
// "wireless" variant.
func (u EventDetail) IsWireless() bool {
	return u.Type == EventDetailTypeWireless
}

// GetWireless returns the "wireless" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u EventDetail) GetWireless() (*WirelessEventDetail, bool) {
	if !u.IsWireless() || u.Wireless == nil {
		return nil, false
	}
	return u.Wireless, true
}

// UnmarshalJSON decodes the variant selected by type.
//
// An unrecognised discriminator is not an error. The API adds variants without
// a major version change, and failing the whole response because one field is
// new would be worse than leaving that field unpopulated; Raw still holds it.
func (u *EventDetail) UnmarshalJSON(data []byte) error {
	u.Raw = append(u.Raw[:0], data...)

	var tag struct {
		Value EventDetailType `json:"type"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("reading EventDetail discriminator: %w", err)
	}
	u.Type = tag.Value

	switch tag.Value {
	case EventDetailTypeAgent:
		var v AgentEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Agent = &v
	case EventDetailTypeAgentBranch:
		var v AgentBranchEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.AgentBranch = &v
	case EventDetailTypeAgentLocal:
		var v AgentLocalEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.AgentLocal = &v
	case EventDetailTypeApplication:
		var v ApplicationEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Application = &v
	case EventDetailTypeDns:
		var v DnsEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Dns = &v
	case EventDetailTypeDnsName:
		var v DnsNameEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.DnsName = &v
	case EventDetailTypeDnsServer:
		var v DnsServerEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.DnsServer = &v
	case EventDetailTypeDomain:
		var v DomainEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Domain = &v
	case EventDetailTypeGateway:
		var v GatewayEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Gateway = &v
	case EventDetailTypeNameServer:
		var v NameServerEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.NameServer = &v
	case EventDetailTypeNetwork:
		var v NetworkEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Network = &v
	case EventDetailTypeNetworkPop:
		var v NetworkPopEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.NetworkPop = &v
	case EventDetailTypeProxy:
		var v ProxyEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Proxy = &v
	case EventDetailTypeTarget:
		var v TargetEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Target = &v
	case EventDetailTypeTargetNetwork:
		var v TargetNetworkEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.TargetNetwork = &v
	case EventDetailTypeVpn:
		var v VpnEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Vpn = &v
	case EventDetailTypeWireless:
		var v WirelessEventDetail
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding EventDetail variant %q: %w", tag.Value, err)
		}
		u.Wireless = &v
	}

	return nil
}

// MarshalJSON encodes the variant the discriminator selects.
//
// A discriminator naming a variant that is not populated is an error rather
// than a silent fallback: emitting Raw or null there would send the server
// something the caller did not ask for.
func (u EventDetail) MarshalJSON() ([]byte, error) {
	switch u.Type {
	case EventDetailTypeAgent:
		if u.Agent == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Agent is not set",
				u.Type)
		}
		return marshalVariant(u.Agent, "type", string(u.Type))
	case EventDetailTypeAgentBranch:
		if u.AgentBranch == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but AgentBranch is not set",
				u.Type)
		}
		return marshalVariant(u.AgentBranch, "type", string(u.Type))
	case EventDetailTypeAgentLocal:
		if u.AgentLocal == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but AgentLocal is not set",
				u.Type)
		}
		return marshalVariant(u.AgentLocal, "type", string(u.Type))
	case EventDetailTypeApplication:
		if u.Application == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Application is not set",
				u.Type)
		}
		return marshalVariant(u.Application, "type", string(u.Type))
	case EventDetailTypeDns:
		if u.Dns == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Dns is not set",
				u.Type)
		}
		return marshalVariant(u.Dns, "type", string(u.Type))
	case EventDetailTypeDnsName:
		if u.DnsName == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but DnsName is not set",
				u.Type)
		}
		return marshalVariant(u.DnsName, "type", string(u.Type))
	case EventDetailTypeDnsServer:
		if u.DnsServer == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but DnsServer is not set",
				u.Type)
		}
		return marshalVariant(u.DnsServer, "type", string(u.Type))
	case EventDetailTypeDomain:
		if u.Domain == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Domain is not set",
				u.Type)
		}
		return marshalVariant(u.Domain, "type", string(u.Type))
	case EventDetailTypeGateway:
		if u.Gateway == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Gateway is not set",
				u.Type)
		}
		return marshalVariant(u.Gateway, "type", string(u.Type))
	case EventDetailTypeNameServer:
		if u.NameServer == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but NameServer is not set",
				u.Type)
		}
		return marshalVariant(u.NameServer, "type", string(u.Type))
	case EventDetailTypeNetwork:
		if u.Network == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Network is not set",
				u.Type)
		}
		return marshalVariant(u.Network, "type", string(u.Type))
	case EventDetailTypeNetworkPop:
		if u.NetworkPop == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but NetworkPop is not set",
				u.Type)
		}
		return marshalVariant(u.NetworkPop, "type", string(u.Type))
	case EventDetailTypeProxy:
		if u.Proxy == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Proxy is not set",
				u.Type)
		}
		return marshalVariant(u.Proxy, "type", string(u.Type))
	case EventDetailTypeTarget:
		if u.Target == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Target is not set",
				u.Type)
		}
		return marshalVariant(u.Target, "type", string(u.Type))
	case EventDetailTypeTargetNetwork:
		if u.TargetNetwork == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but TargetNetwork is not set",
				u.Type)
		}
		return marshalVariant(u.TargetNetwork, "type", string(u.Type))
	case EventDetailTypeVpn:
		if u.Vpn == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Vpn is not set",
				u.Type)
		}
		return marshalVariant(u.Vpn, "type", string(u.Type))
	case EventDetailTypeWireless:
		if u.Wireless == nil {
			return nil, fmt.Errorf(
				"EventDetail: type is %q but Wireless is not set",
				u.Type)
		}
		return marshalVariant(u.Wireless, "type", string(u.Type))
	}

	// The discriminator is one this SDK does not know. Round-trip what arrived
	// rather than rejecting a payload the server considers valid.
	if len(u.Raw) > 0 {
		return u.Raw, nil
	}
	if u.Type == "" {
		return []byte("null"), nil
	}
	return nil, fmt.Errorf(
		"EventDetail: unknown type %q and no raw payload to fall back on",
		u.Type)
}

// marshalVariant encodes a union variant with its discriminator reinstated,
// since the variant types do not carry the tag themselves.
func marshalVariant(variant any, property, value string) ([]byte, error) {
	encoded, err := json.Marshal(variant)
	if err != nil {
		return nil, fmt.Errorf("encoding variant: %w", err)
	}

	fields := map[string]json.RawMessage{}
	if err := json.Unmarshal(encoded, &fields); err != nil {
		// Not an object, so there is nowhere to reinstate the discriminator.
		return encoded, nil
	}

	tag, err := json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("encoding discriminator: %w", err)
	}
	fields[property] = tag

	return json.Marshal(fields)
}
