// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package agent_to_server_instant_tests

import "fmt"

// CloudEnterpriseAgentType is an enumeration from the OpenAPI specification.
// Type of the agent. It is open: values outside the enumeration decode and
// compare as their underlying string.
type CloudEnterpriseAgentType string

// CloudEnterpriseAgentType values.
const (
	CloudEnterpriseAgentTypeCloud             CloudEnterpriseAgentType = "cloud"
	CloudEnterpriseAgentTypeEnterpriseCluster CloudEnterpriseAgentType = "enterprise-cluster"
	CloudEnterpriseAgentTypeEnterprise        CloudEnterpriseAgentType = "enterprise"
)

// String returns the value as the API spells it, or "CloudEnterpriseAgentType(v)" for
// values outside the enumeration.
func (v CloudEnterpriseAgentType) String() string {
	switch v {
	case CloudEnterpriseAgentTypeCloud:
		return "cloud"
	case CloudEnterpriseAgentTypeEnterpriseCluster:
		return "enterprise-cluster"
	case CloudEnterpriseAgentTypeEnterprise:
		return "enterprise"
	}
	return fmt.Sprintf("CloudEnterpriseAgentType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v CloudEnterpriseAgentType) IsKnown() bool {
	switch v {
	case CloudEnterpriseAgentTypeCloud:
		return true
	case CloudEnterpriseAgentTypeEnterpriseCluster:
		return true
	case CloudEnterpriseAgentTypeEnterprise:
		return true
	}
	return false
}

// CloudEnterpriseAgentTypeValues returns every value the specification declares, in
// specification order.
func CloudEnterpriseAgentTypeValues() []CloudEnterpriseAgentType {
	return []CloudEnterpriseAgentType{
		CloudEnterpriseAgentTypeCloud,
		CloudEnterpriseAgentTypeEnterpriseCluster,
		CloudEnterpriseAgentTypeEnterprise,
	}
}

// NetworkProviderType is an enumeration from the OpenAPI specification.
// Classification of the agent's network provider. It is open: values outside
// the enumeration decode and compare as their underlying string.
type NetworkProviderType string

// NetworkProviderType values.
const (
	NetworkProviderTypeUnknown       NetworkProviderType = "unknown"
	NetworkProviderTypeIsp           NetworkProviderType = "isp"
	NetworkProviderTypeCdn           NetworkProviderType = "cdn"
	NetworkProviderTypeStub          NetworkProviderType = "stub"
	NetworkProviderTypeCloudProvider NetworkProviderType = "cloud-provider"
	NetworkProviderTypeCarrier       NetworkProviderType = "carrier"
)

// String returns the value as the API spells it, or "NetworkProviderType(v)" for
// values outside the enumeration.
func (v NetworkProviderType) String() string {
	switch v {
	case NetworkProviderTypeUnknown:
		return "unknown"
	case NetworkProviderTypeIsp:
		return "isp"
	case NetworkProviderTypeCdn:
		return "cdn"
	case NetworkProviderTypeStub:
		return "stub"
	case NetworkProviderTypeCloudProvider:
		return "cloud-provider"
	case NetworkProviderTypeCarrier:
		return "carrier"
	}
	return fmt.Sprintf("NetworkProviderType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v NetworkProviderType) IsKnown() bool {
	switch v {
	case NetworkProviderTypeUnknown:
		return true
	case NetworkProviderTypeIsp:
		return true
	case NetworkProviderTypeCdn:
		return true
	case NetworkProviderTypeStub:
		return true
	case NetworkProviderTypeCloudProvider:
		return true
	case NetworkProviderTypeCarrier:
		return true
	}
	return false
}

// NetworkProviderTypeValues returns every value the specification declares, in
// specification order.
func NetworkProviderTypeValues() []NetworkProviderType {
	return []NetworkProviderType{
		NetworkProviderTypeUnknown,
		NetworkProviderTypeIsp,
		NetworkProviderTypeCdn,
		NetworkProviderTypeStub,
		NetworkProviderTypeCloudProvider,
		NetworkProviderTypeCarrier,
	}
}

// TestDscpId is an enumeration from the OpenAPI specification. DSCP ID [to see
// list for acceptable
// values](https://docs.thousandeyes.com/product-documentation/tests/dscp-options-in-network-tests)
// It is open: values outside the enumeration decode and compare as their
// underlying string.
type TestDscpId string

// TestDscpId values.
const (
	TestDscpIdN0  TestDscpId = "0"
	TestDscpIdN8  TestDscpId = "8"
	TestDscpIdN16 TestDscpId = "16"
	TestDscpIdN24 TestDscpId = "24"
	TestDscpIdN32 TestDscpId = "32"
	TestDscpIdN40 TestDscpId = "40"
	TestDscpIdN48 TestDscpId = "48"
	TestDscpIdN56 TestDscpId = "56"
	TestDscpIdN10 TestDscpId = "10"
	TestDscpIdN12 TestDscpId = "12"
	TestDscpIdN14 TestDscpId = "14"
	TestDscpIdN18 TestDscpId = "18"
	TestDscpIdN20 TestDscpId = "20"
	TestDscpIdN22 TestDscpId = "22"
	TestDscpIdN26 TestDscpId = "26"
	TestDscpIdN28 TestDscpId = "28"
	TestDscpIdN30 TestDscpId = "30"
	TestDscpIdN34 TestDscpId = "34"
	TestDscpIdN36 TestDscpId = "36"
	TestDscpIdN38 TestDscpId = "38"
	TestDscpIdN46 TestDscpId = "46"
	TestDscpIdN44 TestDscpId = "44"
)

// String returns the value as the API spells it, or "TestDscpId(v)" for
// values outside the enumeration.
func (v TestDscpId) String() string {
	switch v {
	case TestDscpIdN0:
		return "0"
	case TestDscpIdN8:
		return "8"
	case TestDscpIdN16:
		return "16"
	case TestDscpIdN24:
		return "24"
	case TestDscpIdN32:
		return "32"
	case TestDscpIdN40:
		return "40"
	case TestDscpIdN48:
		return "48"
	case TestDscpIdN56:
		return "56"
	case TestDscpIdN10:
		return "10"
	case TestDscpIdN12:
		return "12"
	case TestDscpIdN14:
		return "14"
	case TestDscpIdN18:
		return "18"
	case TestDscpIdN20:
		return "20"
	case TestDscpIdN22:
		return "22"
	case TestDscpIdN26:
		return "26"
	case TestDscpIdN28:
		return "28"
	case TestDscpIdN30:
		return "30"
	case TestDscpIdN34:
		return "34"
	case TestDscpIdN36:
		return "36"
	case TestDscpIdN38:
		return "38"
	case TestDscpIdN46:
		return "46"
	case TestDscpIdN44:
		return "44"
	}
	return fmt.Sprintf("TestDscpId(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestDscpId) IsKnown() bool {
	switch v {
	case TestDscpIdN0:
		return true
	case TestDscpIdN8:
		return true
	case TestDscpIdN16:
		return true
	case TestDscpIdN24:
		return true
	case TestDscpIdN32:
		return true
	case TestDscpIdN40:
		return true
	case TestDscpIdN48:
		return true
	case TestDscpIdN56:
		return true
	case TestDscpIdN10:
		return true
	case TestDscpIdN12:
		return true
	case TestDscpIdN14:
		return true
	case TestDscpIdN18:
		return true
	case TestDscpIdN20:
		return true
	case TestDscpIdN22:
		return true
	case TestDscpIdN26:
		return true
	case TestDscpIdN28:
		return true
	case TestDscpIdN30:
		return true
	case TestDscpIdN34:
		return true
	case TestDscpIdN36:
		return true
	case TestDscpIdN38:
		return true
	case TestDscpIdN46:
		return true
	case TestDscpIdN44:
		return true
	}
	return false
}

// TestDscpIdValues returns every value the specification declares, in
// specification order.
func TestDscpIdValues() []TestDscpId {
	return []TestDscpId{
		TestDscpIdN0,
		TestDscpIdN8,
		TestDscpIdN16,
		TestDscpIdN24,
		TestDscpIdN32,
		TestDscpIdN40,
		TestDscpIdN48,
		TestDscpIdN56,
		TestDscpIdN10,
		TestDscpIdN12,
		TestDscpIdN14,
		TestDscpIdN18,
		TestDscpIdN20,
		TestDscpIdN22,
		TestDscpIdN26,
		TestDscpIdN28,
		TestDscpIdN30,
		TestDscpIdN34,
		TestDscpIdN36,
		TestDscpIdN38,
		TestDscpIdN46,
		TestDscpIdN44,
	}
}

// TestIpv6Policy is an enumeration from the OpenAPI specification. IP version
// policy. It is open: values outside the enumeration decode and compare as
// their underlying string.
type TestIpv6Policy string

// TestIpv6Policy values.
const (
	TestIpv6PolicyForceIpv4      TestIpv6Policy = "force-ipv4"
	TestIpv6PolicyPreferIpv6     TestIpv6Policy = "prefer-ipv6"
	TestIpv6PolicyForceIpv6      TestIpv6Policy = "force-ipv6"
	TestIpv6PolicyUseAgentPolicy TestIpv6Policy = "use-agent-policy"
)

// String returns the value as the API spells it, or "TestIpv6Policy(v)" for
// values outside the enumeration.
func (v TestIpv6Policy) String() string {
	switch v {
	case TestIpv6PolicyForceIpv4:
		return "force-ipv4"
	case TestIpv6PolicyPreferIpv6:
		return "prefer-ipv6"
	case TestIpv6PolicyForceIpv6:
		return "force-ipv6"
	case TestIpv6PolicyUseAgentPolicy:
		return "use-agent-policy"
	}
	return fmt.Sprintf("TestIpv6Policy(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestIpv6Policy) IsKnown() bool {
	switch v {
	case TestIpv6PolicyForceIpv4:
		return true
	case TestIpv6PolicyPreferIpv6:
		return true
	case TestIpv6PolicyForceIpv6:
		return true
	case TestIpv6PolicyUseAgentPolicy:
		return true
	}
	return false
}

// TestIpv6PolicyValues returns every value the specification declares, in
// specification order.
func TestIpv6PolicyValues() []TestIpv6Policy {
	return []TestIpv6Policy{
		TestIpv6PolicyForceIpv4,
		TestIpv6PolicyPreferIpv6,
		TestIpv6PolicyForceIpv6,
		TestIpv6PolicyUseAgentPolicy,
	}
}

// TestPathTraceMode is an enumeration from the OpenAPI specification. Select
// `inSession` to perform the path trace within a TCP session. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestPathTraceMode string

// TestPathTraceMode values.
const (
	TestPathTraceModeClassic   TestPathTraceMode = "classic"
	TestPathTraceModeInSession TestPathTraceMode = "in-session"
)

// String returns the value as the API spells it, or "TestPathTraceMode(v)" for
// values outside the enumeration.
func (v TestPathTraceMode) String() string {
	switch v {
	case TestPathTraceModeClassic:
		return "classic"
	case TestPathTraceModeInSession:
		return "in-session"
	}
	return fmt.Sprintf("TestPathTraceMode(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestPathTraceMode) IsKnown() bool {
	switch v {
	case TestPathTraceModeClassic:
		return true
	case TestPathTraceModeInSession:
		return true
	}
	return false
}

// TestPathTraceModeValues returns every value the specification declares, in
// specification order.
func TestPathTraceModeValues() []TestPathTraceMode {
	return []TestPathTraceMode{
		TestPathTraceModeClassic,
		TestPathTraceModeInSession,
	}
}

// TestProbeMode is an enumeration from the OpenAPI specification. Probe mode
// used by network test, only valid when the protocol is set to TCP. It is
// open: values outside the enumeration decode and compare as their underlying
// string.
type TestProbeMode string

// TestProbeMode values.
const (
	TestProbeModeAuto TestProbeMode = "auto"
	TestProbeModeSack TestProbeMode = "sack"
	TestProbeModeSyn  TestProbeMode = "syn"
)

// String returns the value as the API spells it, or "TestProbeMode(v)" for
// values outside the enumeration.
func (v TestProbeMode) String() string {
	switch v {
	case TestProbeModeAuto:
		return "auto"
	case TestProbeModeSack:
		return "sack"
	case TestProbeModeSyn:
		return "syn"
	}
	return fmt.Sprintf("TestProbeMode(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestProbeMode) IsKnown() bool {
	switch v {
	case TestProbeModeAuto:
		return true
	case TestProbeModeSack:
		return true
	case TestProbeModeSyn:
		return true
	}
	return false
}

// TestProbeModeValues returns every value the specification declares, in
// specification order.
func TestProbeModeValues() []TestProbeMode {
	return []TestProbeMode{
		TestProbeModeAuto,
		TestProbeModeSack,
		TestProbeModeSyn,
	}
}

// TestProtocol is an enumeration from the OpenAPI specification. Protocol used
// by dependent network tests (end-to-end, path trace, PMTUD). It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestProtocol string

// TestProtocol values.
const (
	TestProtocolTcp  TestProtocol = "tcp"
	TestProtocolIcmp TestProtocol = "icmp"
	TestProtocolUdp  TestProtocol = "udp"
)

// String returns the value as the API spells it, or "TestProtocol(v)" for
// values outside the enumeration.
func (v TestProtocol) String() string {
	switch v {
	case TestProtocolTcp:
		return "tcp"
	case TestProtocolIcmp:
		return "icmp"
	case TestProtocolUdp:
		return "udp"
	}
	return fmt.Sprintf("TestProtocol(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestProtocol) IsKnown() bool {
	switch v {
	case TestProtocolTcp:
		return true
	case TestProtocolIcmp:
		return true
	case TestProtocolUdp:
		return true
	}
	return false
}

// TestProtocolValues returns every value the specification declares, in
// specification order.
func TestProtocolValues() []TestProtocol {
	return []TestProtocol{
		TestProtocolTcp,
		TestProtocolIcmp,
		TestProtocolUdp,
	}
}
