// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.101)

package generic_connectors

import "fmt"

// AuthenticationType is an enumeration from the OpenAPI specification. It is
// open: values outside the enumeration decode and compare as their underlying
// string.
type AuthenticationType string

// AuthenticationType values.
const (
	AuthenticationTypeBasic                  AuthenticationType = "basic"
	AuthenticationTypeBearerToken            AuthenticationType = "bearer-token"
	AuthenticationTypeOauthAuthCode          AuthenticationType = "oauth-auth-code"
	AuthenticationTypeOauthClientCredentials AuthenticationType = "oauth-client-credentials"
	AuthenticationTypeOtherToken             AuthenticationType = "other-token"
	AuthenticationTypeConjurHost             AuthenticationType = "conjur-host"
)

// String returns the value as the API spells it, or "AuthenticationType(v)" for
// values outside the enumeration.
func (v AuthenticationType) String() string {
	switch v {
	case AuthenticationTypeBasic:
		return "basic"
	case AuthenticationTypeBearerToken:
		return "bearer-token"
	case AuthenticationTypeOauthAuthCode:
		return "oauth-auth-code"
	case AuthenticationTypeOauthClientCredentials:
		return "oauth-client-credentials"
	case AuthenticationTypeOtherToken:
		return "other-token"
	case AuthenticationTypeConjurHost:
		return "conjur-host"
	}
	return fmt.Sprintf("AuthenticationType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v AuthenticationType) IsKnown() bool {
	switch v {
	case AuthenticationTypeBasic:
		return true
	case AuthenticationTypeBearerToken:
		return true
	case AuthenticationTypeOauthAuthCode:
		return true
	case AuthenticationTypeOauthClientCredentials:
		return true
	case AuthenticationTypeOtherToken:
		return true
	case AuthenticationTypeConjurHost:
		return true
	}
	return false
}

// AuthenticationTypeValues returns every value the specification declares, in
// specification order.
func AuthenticationTypeValues() []AuthenticationType {
	return []AuthenticationType{
		AuthenticationTypeBasic,
		AuthenticationTypeBearerToken,
		AuthenticationTypeOauthAuthCode,
		AuthenticationTypeOauthClientCredentials,
		AuthenticationTypeOtherToken,
		AuthenticationTypeConjurHost,
	}
}

// ConnectorType is an enumeration from the OpenAPI specification. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type ConnectorType string

// ConnectorType values.
const (
	ConnectorTypeGeneric ConnectorType = "generic"
)

// String returns the value as the API spells it, or "ConnectorType(v)" for
// values outside the enumeration.
func (v ConnectorType) String() string {
	switch v {
	case ConnectorTypeGeneric:
		return "generic"
	}
	return fmt.Sprintf("ConnectorType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v ConnectorType) IsKnown() bool {
	switch v {
	case ConnectorTypeGeneric:
		return true
	}
	return false
}

// ConnectorTypeValues returns every value the specification declares, in
// specification order.
func ConnectorTypeValues() []ConnectorType {
	return []ConnectorType{
		ConnectorTypeGeneric,
	}
}

// GenericConnectorAuthType is an enumeration from the OpenAPI specification.
// selects which variant of GenericConnectorAuth is populated. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type GenericConnectorAuthType string

// GenericConnectorAuthType values.
const (
	GenericConnectorAuthTypeBasic                  GenericConnectorAuthType = "basic"
	GenericConnectorAuthTypeBearerToken            GenericConnectorAuthType = "bearer-token"
	GenericConnectorAuthTypeOauthAuthCode          GenericConnectorAuthType = "oauth-auth-code"
	GenericConnectorAuthTypeOauthClientCredentials GenericConnectorAuthType = "oauth-client-credentials"
	GenericConnectorAuthTypeOtherToken             GenericConnectorAuthType = "other-token"
)

// String returns the value as the API spells it, or "GenericConnectorAuthType(v)" for
// values outside the enumeration.
func (v GenericConnectorAuthType) String() string {
	switch v {
	case GenericConnectorAuthTypeBasic:
		return "basic"
	case GenericConnectorAuthTypeBearerToken:
		return "bearer-token"
	case GenericConnectorAuthTypeOauthAuthCode:
		return "oauth-auth-code"
	case GenericConnectorAuthTypeOauthClientCredentials:
		return "oauth-client-credentials"
	case GenericConnectorAuthTypeOtherToken:
		return "other-token"
	}
	return fmt.Sprintf("GenericConnectorAuthType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v GenericConnectorAuthType) IsKnown() bool {
	switch v {
	case GenericConnectorAuthTypeBasic:
		return true
	case GenericConnectorAuthTypeBearerToken:
		return true
	case GenericConnectorAuthTypeOauthAuthCode:
		return true
	case GenericConnectorAuthTypeOauthClientCredentials:
		return true
	case GenericConnectorAuthTypeOtherToken:
		return true
	}
	return false
}

// GenericConnectorAuthTypeValues returns every value the specification declares, in
// specification order.
func GenericConnectorAuthTypeValues() []GenericConnectorAuthType {
	return []GenericConnectorAuthType{
		GenericConnectorAuthTypeBasic,
		GenericConnectorAuthTypeBearerToken,
		GenericConnectorAuthTypeOauthAuthCode,
		GenericConnectorAuthTypeOauthClientCredentials,
		GenericConnectorAuthTypeOtherToken,
	}
}
