// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package generic_connectors

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// GenericConnectors handles communication with the Generic Connectors methods of the
	// ThousandEyes API.
	GenericConnectors struct {
		client client.Client
	}
)

// NewGenericConnectors returns a Generic Connectors service bound to client.
func NewGenericConnectors(client client.Client) *GenericConnectors {
	return &GenericConnectors{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Generic Connectors
// -----------------------------------------------------------------------------

// GetGenericConnectors list connectors.
// URL: GET /connectors/generic
//
// Returns a list of connectors in the specified account group.
func (s *GenericConnectors) GetGenericConnectors(ctx context.Context, opts ...client.RequestOption) (*ResourceGenericConnectors, *resty.Response, error) {

	endpoint := "/connectors/generic"

	var result ResourceGenericConnectors

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateGenericConnector create connector.
// URL: POST /connectors/generic
//
// Creates a new connector.
func (s *GenericConnectors) CreateGenericConnector(ctx context.Context, request *GenericConnector, opts ...client.RequestOption) (*GenericConnector, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/connectors/generic"

	var result GenericConnector

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteGenericConnector delete connector.
// URL: DELETE /connectors/generic/{id}
//
// Deletes the connector specified by ID.
func (s *GenericConnectors) DeleteGenericConnector(ctx context.Context, id string, opts ...client.RequestOption) (*resty.Response, error) {
	if id == "" {
		return nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/connectors/generic/%s", id)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetGenericConnector retrieve connector.
// URL: GET /connectors/generic/{id}
//
// Retrieves details of a connector by its ID.
func (s *GenericConnectors) GetGenericConnector(ctx context.Context, id string, opts ...client.RequestOption) (*GenericConnector, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/connectors/generic/%s", id)

	var result GenericConnector

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateGenericConnector update connector.
// URL: PUT /connectors/generic/{id}
//
// Updates the connector specified by ID.
func (s *GenericConnectors) UpdateGenericConnector(ctx context.Context, id string, request *GenericConnector, opts ...client.RequestOption) (*GenericConnector, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/connectors/generic/%s", id)

	var result GenericConnector

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// ListGenericConnectorOperations list operation IDs for a connector.
// URL: GET /connectors/generic/{id}/operations
//
// Returns a list of operation IDs assigned to a connector.
func (s *GenericConnectors) ListGenericConnectorOperations(ctx context.Context, id string, opts ...client.RequestOption) (*Assignments, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/connectors/generic/%s/operations", id)

	var result Assignments

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// SetGenericConnectorOperations assign operations to a connector.
// URL: PUT /connectors/generic/{id}/operations
//
// Assigns operations to a connector.
func (s *GenericConnectors) SetGenericConnectorOperations(ctx context.Context, id string, request []string, opts ...client.RequestOption) (*Assignments, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/connectors/generic/%s/operations", id)

	var result Assignments

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
