// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package endpoint_agent_log_items

// EndpointAgentLogItem is generated from the OpenAPI specification.
type EndpointAgentLogItem struct {
	AgentLogItemType EndpointAgentLogItemType `json:"agentLogItemType,omitempty"`
	// Unique ID of the log item.
	ID                   *string                       `json:"id,omitempty"`
	OnlineOfflineLogItem *EndpointOnlineOfflineLogItem `json:"onlineOfflineLogItem,omitempty"`
	StateChangesLogItem  *EndpointStateChangesLogItem  `json:"stateChangesLogItem,omitempty"`
	// Time when the log item was recorded, in milliseconds since the Unix epoch.
	TimestampMs *int64               `json:"timestampMs,omitempty"`
	VpnLogItem  *EndpointVpnLogItem  `json:"vpnLogItem,omitempty"`
	WifiLogItem *EndpointWifiLogItem `json:"wifiLogItem,omitempty"`
}

// EndpointAgentLogItemsResponse is generated from the OpenAPI specification.
type EndpointAgentLogItemsResponse struct {
	Links *PaginationNextAndSelfLink `json:"_links,omitempty"`
	// Log items for the endpoint agent.
	Logs []EndpointAgentLogItem `json:"logs"`
}

// EndpointOnlineOfflineLogItem is generated from the OpenAPI specification.
type EndpointOnlineOfflineLogItem struct {
	LogItemType EndpointOnlineOfflineLogItemType `json:"logItemType,omitempty"`
}

// EndpointStateChangesLogItem is generated from the OpenAPI specification.
type EndpointStateChangesLogItem struct {
	LogItemType EndpointStateChangesLogItemType `json:"logItemType,omitempty"`
}

// EndpointVpnLogItem is generated from the OpenAPI specification.
type EndpointVpnLogItem struct {
	LogItemType EndpointVpnLogItemType `json:"logItemType,omitempty"`
	// VPN server address.
	VpnServerAddress *string `json:"vpnServerAddress,omitempty"`
	// VPN server name.
	VpnServerName *string         `json:"vpnServerName,omitempty"`
	VpnType       EndpointVpnType `json:"vpnType,omitempty"`
}

// EndpointWifiLogItem is generated from the OpenAPI specification.
type EndpointWifiLogItem struct {
	// Wireless access point BSSID.
	Bssid *string `json:"bssid,omitempty"`
	// Previous wireless access point BSSID.
	BssidFrom *string `json:"bssidFrom,omitempty"`
	// Wireless channel.
	Channel *string `json:"channel,omitempty"`
	// Previous wireless channel.
	ChannelFrom *string                            `json:"channelFrom,omitempty"`
	Failure     *EndpointWirelessConnectionFailure `json:"failure,omitempty"`
	LogItemType EndpointWifiLogItemType            `json:"logItemType,omitempty"`
	// Wireless physical mode.
	PhysicalMode *string `json:"physicalMode,omitempty"`
	// Previous wireless physical mode.
	PhysicalModeFrom *string `json:"physicalModeFrom,omitempty"`
	// Wireless network SSID.
	Ssid *string `json:"ssid,omitempty"`
}

// EndpointWirelessConnectionFailure is generated from the OpenAPI specification.
type EndpointWirelessConnectionFailure struct {
	// Wireless connection failure code.
	Code *int64 `json:"code,omitempty"`
	// Additional context for the wireless connection failure.
	Context *string                               `json:"context,omitempty"`
	Type    EndpointWirelessConnectionFailureType `json:"type,omitempty"`
}

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// PaginationNextAndSelfLink A links object containing a related link for
// forward pagination.
type PaginationNextAndSelfLink struct {
	Next *Link `json:"next,omitempty"`
	Self *Link `json:"self,omitempty"`
}
