// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.98)

package emulation

import "fmt"

// EmulatedDeviceCategory is an enumeration from the OpenAPI specification. The
// type of device being emulated. It is open: values outside the enumeration
// decode and compare as their underlying string.
type EmulatedDeviceCategory string

// EmulatedDeviceCategory values.
const (
	EmulatedDeviceCategoryDesktop EmulatedDeviceCategory = "desktop"
	EmulatedDeviceCategoryLaptop  EmulatedDeviceCategory = "laptop"
	EmulatedDeviceCategoryPhone   EmulatedDeviceCategory = "phone"
	EmulatedDeviceCategoryTablet  EmulatedDeviceCategory = "tablet"
)

// String returns the value as the API spells it, or "EmulatedDeviceCategory(v)" for
// values outside the enumeration.
func (v EmulatedDeviceCategory) String() string {
	switch v {
	case EmulatedDeviceCategoryDesktop:
		return "desktop"
	case EmulatedDeviceCategoryLaptop:
		return "laptop"
	case EmulatedDeviceCategoryPhone:
		return "phone"
	case EmulatedDeviceCategoryTablet:
		return "tablet"
	}
	return fmt.Sprintf("EmulatedDeviceCategory(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v EmulatedDeviceCategory) IsKnown() bool {
	switch v {
	case EmulatedDeviceCategoryDesktop:
		return true
	case EmulatedDeviceCategoryLaptop:
		return true
	case EmulatedDeviceCategoryPhone:
		return true
	case EmulatedDeviceCategoryTablet:
		return true
	}
	return false
}

// EmulatedDeviceCategoryValues returns every value the specification declares, in
// specification order.
func EmulatedDeviceCategoryValues() []EmulatedDeviceCategory {
	return []EmulatedDeviceCategory{
		EmulatedDeviceCategoryDesktop,
		EmulatedDeviceCategoryLaptop,
		EmulatedDeviceCategoryPhone,
		EmulatedDeviceCategoryTablet,
	}
}
