// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package tag_assignment

import "fmt"

// AssignmentType is an enumeration from the OpenAPI specification. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type AssignmentType string

// AssignmentType values.
const (
	AssignmentTypeTest                 AssignmentType = "test"
	AssignmentTypeVAgent               AssignmentType = "v-agent"
	AssignmentTypeEndpointTest         AssignmentType = "endpoint-test"
	AssignmentTypeDashboard            AssignmentType = "dashboard"
	AssignmentTypeConnectedDevicesTest AssignmentType = "connected-devices-test"
)

// String returns the value as the API spells it, or "AssignmentType(v)" for
// values outside the enumeration.
func (v AssignmentType) String() string {
	switch v {
	case AssignmentTypeTest:
		return "test"
	case AssignmentTypeVAgent:
		return "v-agent"
	case AssignmentTypeEndpointTest:
		return "endpoint-test"
	case AssignmentTypeDashboard:
		return "dashboard"
	case AssignmentTypeConnectedDevicesTest:
		return "connected-devices-test"
	}
	return fmt.Sprintf("AssignmentType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v AssignmentType) IsKnown() bool {
	switch v {
	case AssignmentTypeTest:
		return true
	case AssignmentTypeVAgent:
		return true
	case AssignmentTypeEndpointTest:
		return true
	case AssignmentTypeDashboard:
		return true
	case AssignmentTypeConnectedDevicesTest:
		return true
	}
	return false
}

// AssignmentTypeValues returns every value the specification declares, in
// specification order.
func AssignmentTypeValues() []AssignmentType {
	return []AssignmentType{
		AssignmentTypeTest,
		AssignmentTypeVAgent,
		AssignmentTypeEndpointTest,
		AssignmentTypeDashboard,
		AssignmentTypeConnectedDevicesTest,
	}
}
