// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package tag_assignment

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// TagAssignment handles communication with the Tag Assignment methods of the
	// ThousandEyes API.
	TagAssignment struct {
		client client.Client
	}
)

// NewTagAssignment returns a Tag Assignment service bound to client.
func NewTagAssignment(client client.Client) *TagAssignment {
	return &TagAssignment{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Tag Assignment
// -----------------------------------------------------------------------------

// AssignTags assign multiple tags to multiple objects.
// URL: POST /tags/assign
//
// Assigns the specified static tags to the specified objects.
func (s *TagAssignment) AssignTags(ctx context.Context, opts ...client.RequestOption) (*BulkTagAssignments, *resty.Response, error) {

	endpoint := "/tags/assign"

	var result BulkTagAssignments

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UnassignTags remove multiple tags from multiple objects.
// URL: POST /tags/unassign
//
// Removes the specified static tags from one or more objects.
func (s *TagAssignment) UnassignTags(ctx context.Context, opts ...client.RequestOption) (*BulkTagAssignments, *resty.Response, error) {

	endpoint := "/tags/unassign"

	var result BulkTagAssignments

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// AssignTag assign tag to multiple objects.
// URL: POST /tags/{id}/assign
//
// Assigns a static tag to one or more objects.
func (s *TagAssignment) AssignTag(ctx context.Context, id string, opts ...client.RequestOption) (*BulkTagAssignment, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/tags/%s/assign", id)

	var result BulkTagAssignment

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UnassignTag remove tag from multiple objects.
// URL: POST /tags/{id}/unassign
//
// Removes a static tag from one or more objects.
func (s *TagAssignment) UnassignTag(ctx context.Context, id string, opts ...client.RequestOption) (*resty.Response, error) {
	if id == "" {
		return nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/tags/%s/unassign", id)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}
