// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.101)

package endpoint_real_user_tests

import "fmt"

// EndpointMonitoringSettingsType is an enumeration from the OpenAPI
// specification. Endpoint Agent selector type used by the monitoring settings.
// It is open: values outside the enumeration decode and compare as their
// underlying string.
type EndpointMonitoringSettingsType string

// EndpointMonitoringSettingsType values.
const (
	EndpointMonitoringSettingsTypeAllAgents      EndpointMonitoringSettingsType = "all-agents"
	EndpointMonitoringSettingsTypeSpecificAgents EndpointMonitoringSettingsType = "specific-agents"
	EndpointMonitoringSettingsTypeAgentLabels    EndpointMonitoringSettingsType = "agent-labels"
	EndpointMonitoringSettingsTypeAgentTags      EndpointMonitoringSettingsType = "agent-tags"
)

// String returns the value as the API spells it, or "EndpointMonitoringSettingsType(v)" for
// values outside the enumeration.
func (v EndpointMonitoringSettingsType) String() string {
	switch v {
	case EndpointMonitoringSettingsTypeAllAgents:
		return "all-agents"
	case EndpointMonitoringSettingsTypeSpecificAgents:
		return "specific-agents"
	case EndpointMonitoringSettingsTypeAgentLabels:
		return "agent-labels"
	case EndpointMonitoringSettingsTypeAgentTags:
		return "agent-tags"
	}
	return fmt.Sprintf("EndpointMonitoringSettingsType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v EndpointMonitoringSettingsType) IsKnown() bool {
	switch v {
	case EndpointMonitoringSettingsTypeAllAgents:
		return true
	case EndpointMonitoringSettingsTypeSpecificAgents:
		return true
	case EndpointMonitoringSettingsTypeAgentLabels:
		return true
	case EndpointMonitoringSettingsTypeAgentTags:
		return true
	}
	return false
}

// EndpointMonitoringSettingsTypeValues returns every value the specification declares, in
// specification order.
func EndpointMonitoringSettingsTypeValues() []EndpointMonitoringSettingsType {
	return []EndpointMonitoringSettingsType{
		EndpointMonitoringSettingsTypeAllAgents,
		EndpointMonitoringSettingsTypeSpecificAgents,
		EndpointMonitoringSettingsTypeAgentLabels,
		EndpointMonitoringSettingsTypeAgentTags,
	}
}
