// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package cyberark_conjur_connectors

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// CyberArkConjurConnectors handles communication with the CyberArk Conjur Connectors methods of the
	// ThousandEyes API.
	CyberArkConjurConnectors struct {
		client client.Client
	}
)

// NewCyberArkConjurConnectors returns a CyberArk Conjur Connectors service bound to client.
func NewCyberArkConjurConnectors(client client.Client) *CyberArkConjurConnectors {
	return &CyberArkConjurConnectors{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - CyberArk Conjur Connectors
// -----------------------------------------------------------------------------

// GetConjurConnectors list Conjur connectors.
// URL: GET /connectors/conjur
//
// Returns a list of CyberArk Conjur connectors in the specified account group.
func (s *CyberArkConjurConnectors) GetConjurConnectors(ctx context.Context, opts ...client.RequestOption) (*ConjurConnectors, *resty.Response, error) {

	endpoint := "/connectors/conjur"

	var result ConjurConnectors

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateConjurConnector create Conjur connector.
// URL: POST /connectors/conjur
//
// Creates a new CyberArk Conjur connector.
func (s *CyberArkConjurConnectors) CreateConjurConnector(ctx context.Context, request *ConjurConnector, opts ...client.RequestOption) (*ConjurConnector, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/connectors/conjur"

	var result ConjurConnector

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteConjurConnector delete a Conjur connector.
// URL: DELETE /connectors/conjur/{id}
// Optional query params: confirmDisabledObjects
//
// Deleted the CyberArk Conjur connector specified by ID.
func (s *CyberArkConjurConnectors) DeleteConjurConnector(ctx context.Context, id string, opts ...client.RequestOption) (*resty.Response, error) {
	if id == "" {
		return nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/connectors/conjur/%s", id)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetConjurConnector retrieve a Conjur connector.
// URL: GET /connectors/conjur/{id}
//
// Retrieves details of a CyberArk Conjur connector by its ID.
func (s *CyberArkConjurConnectors) GetConjurConnector(ctx context.Context, id string, opts ...client.RequestOption) (*ConjurConnector, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/connectors/conjur/%s", id)

	var result ConjurConnector

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateConjurConnector update a Conjur connector.
// URL: PUT /connectors/conjur/{id}
//
// Updates the CyberArk Conjur connector specified by ID.
func (s *CyberArkConjurConnectors) UpdateConjurConnector(ctx context.Context, id string, request *ConjurConnector, opts ...client.RequestOption) (*ConjurConnector, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/connectors/conjur/%s", id)

	var result ConjurConnector

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetConjurConnectorOperations list operation IDs for a Conjur connector.
// URL: GET /connectors/conjur/{id}/operations
//
// Returns a list of operation IDs assigned to a CyberArk Conjur connector.
func (s *CyberArkConjurConnectors) GetConjurConnectorOperations(ctx context.Context, id string, opts ...client.RequestOption) (*Assignments, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/connectors/conjur/%s/operations", id)

	var result Assignments

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// SetConjurConnectorOperations assign operations to a Conjur connector.
// URL: PUT /connectors/conjur/{id}/operations
// Optional query params: confirmDisabledObjects
//
// Assigns operations to a CyberArk Conjur connector.
func (s *CyberArkConjurConnectors) SetConjurConnectorOperations(ctx context.Context, id string, request []string, opts ...client.RequestOption) (*Assignments, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/connectors/conjur/%s/operations", id)

	var result Assignments

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
