// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package dashboard_snapshots

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// DashboardSnapshots handles communication with the Dashboard Snapshots methods of the
	// ThousandEyes API.
	DashboardSnapshots struct {
		client client.Client
	}
)

// NewDashboardSnapshots returns a Dashboard Snapshots service bound to client.
func NewDashboardSnapshots(client client.Client) *DashboardSnapshots {
	return &DashboardSnapshots{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Dashboard Snapshots
// -----------------------------------------------------------------------------

// GetDashboardSnapshots list dashboard snapshots.
// URL: GET /dashboard-snapshots
// Optional query params: dashboardId, cursor
//
// Returns a list of dashboard snapshots within your account group.
func (s *DashboardSnapshots) GetDashboardSnapshots(ctx context.Context, opts ...client.RequestOption) (*DashboardSnapshotsPage, *resty.Response, error) {

	endpoint := "/dashboard-snapshots"

	var result DashboardSnapshotsPage

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateDashboardSnapshot create dashboard snapshot.
// URL: POST /dashboard-snapshots
//
// Creates a new dashboard snapshot within your account group.
func (s *DashboardSnapshots) CreateDashboardSnapshot(ctx context.Context, request *GenerateDashboardSnapshotRequest, opts ...client.RequestOption) (*DashboardSnapshotResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/dashboard-snapshots"

	var result DashboardSnapshotResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteDashboardSnapshot delete dashboard snapshot.
// URL: DELETE /dashboard-snapshots/{snapshotId}
//
// Deletes a dashboard snapshot using the `snapshotId` provided in the request.
func (s *DashboardSnapshots) DeleteDashboardSnapshot(ctx context.Context, snapshotId string, opts ...client.RequestOption) (*resty.Response, error) {
	if snapshotId == "" {
		return nil, fmt.Errorf("snapshotId is required")
	}

	endpoint := fmt.Sprintf("/dashboard-snapshots/%s", snapshotId)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetDashboardSnapshot retrieve dashboard snapshot.
// URL: GET /dashboard-snapshots/{snapshotId}
//
// This operation returns a list of widgets configured in dashboard snapshot
// configured in ThousandEyes.
func (s *DashboardSnapshots) GetDashboardSnapshot(ctx context.Context, snapshotId string, opts ...client.RequestOption) (*ApiDashboardSnapshot, *resty.Response, error) {
	if snapshotId == "" {
		return nil, nil, fmt.Errorf("snapshotId is required")
	}

	endpoint := fmt.Sprintf("/dashboard-snapshots/%s", snapshotId)

	var result ApiDashboardSnapshot

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateDashboardSnapshotExpirationDate update snapshot expiration.
// URL: PATCH /dashboard-snapshots/{snapshotId}
//
// Updates the expiration date of a dashboard snapshot.
func (s *DashboardSnapshots) UpdateDashboardSnapshotExpirationDate(ctx context.Context, snapshotId string, request *UpdateSnapshotExpirationDateApiRequest, opts ...client.RequestOption) (*resty.Response, error) {
	if snapshotId == "" {
		return nil, fmt.Errorf("snapshotId is required")
	}
	if request == nil {
		return nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/dashboard-snapshots/%s", snapshotId)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Patch(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetDashboardSnapshotWidgetData retrieve dashboard snapshot data.
// URL: GET /dashboard-snapshots/{snapshotId}/widgets/{widgetId}
//
// Returns actual metrics used in the generation of a dashboard snapshot.
func (s *DashboardSnapshots) GetDashboardSnapshotWidgetData(ctx context.Context, snapshotId string, widgetId string, opts ...client.RequestOption) (*ApiWidgetDataSnapshotResponse, *resty.Response, error) {
	if snapshotId == "" {
		return nil, nil, fmt.Errorf("snapshotId is required")
	}
	if widgetId == "" {
		return nil, nil, fmt.Errorf("widgetId is required")
	}

	endpoint := fmt.Sprintf("/dashboard-snapshots/%s/widgets/%s", snapshotId, widgetId)

	var result ApiWidgetDataSnapshotResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
