// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.103)

package agent_to_server_endpoint_instant_scheduled_tests

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// AgentToServerEndpointInstantScheduledTests handles communication with the Agent to Server Endpoint Instant Scheduled Tests methods of the
	// ThousandEyes API.
	AgentToServerEndpointInstantScheduledTests struct {
		client client.Client
	}
)

// NewAgentToServerEndpointInstantScheduledTests returns a Agent to Server Endpoint Instant Scheduled Tests service bound to client.
func NewAgentToServerEndpointInstantScheduledTests(client client.Client) *AgentToServerEndpointInstantScheduledTests {
	return &AgentToServerEndpointInstantScheduledTests{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Agent to Server Endpoint Instant Scheduled Tests
// -----------------------------------------------------------------------------

// CreateAgentToServerScheduledInstantTest run agent to server instant scheduled test.
// URL: POST /endpoint/tests/scheduled-tests/agent-to-server/instant
//
// Creates and runs a new endpoint agent to server instant scheduled test in
// ThousandEyes.
func (s *AgentToServerEndpointInstantScheduledTests) CreateAgentToServerScheduledInstantTest(ctx context.Context, request *EndpointAgentToServerInstantTest, opts ...client.RequestOption) (*EndpointAgentToServerTest, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/endpoint/tests/scheduled-tests/agent-to-server/instant"

	var result EndpointAgentToServerTest

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
