// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package sip_server_instant_tests

import "fmt"

// CloudEnterpriseAgentType is an enumeration from the OpenAPI specification.
// Type of the agent. It is open: values outside the enumeration decode and
// compare as their underlying string.
type CloudEnterpriseAgentType string

// CloudEnterpriseAgentType values.
const (
	CloudEnterpriseAgentTypeCloud             CloudEnterpriseAgentType = "cloud"
	CloudEnterpriseAgentTypeEnterpriseCluster CloudEnterpriseAgentType = "enterprise-cluster"
	CloudEnterpriseAgentTypeEnterprise        CloudEnterpriseAgentType = "enterprise"
)

// String returns the value as the API spells it, or "CloudEnterpriseAgentType(v)" for
// values outside the enumeration.
func (v CloudEnterpriseAgentType) String() string {
	switch v {
	case CloudEnterpriseAgentTypeCloud:
		return "cloud"
	case CloudEnterpriseAgentTypeEnterpriseCluster:
		return "enterprise-cluster"
	case CloudEnterpriseAgentTypeEnterprise:
		return "enterprise"
	}
	return fmt.Sprintf("CloudEnterpriseAgentType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v CloudEnterpriseAgentType) IsKnown() bool {
	switch v {
	case CloudEnterpriseAgentTypeCloud:
		return true
	case CloudEnterpriseAgentTypeEnterpriseCluster:
		return true
	case CloudEnterpriseAgentTypeEnterprise:
		return true
	}
	return false
}

// CloudEnterpriseAgentTypeValues returns every value the specification declares, in
// specification order.
func CloudEnterpriseAgentTypeValues() []CloudEnterpriseAgentType {
	return []CloudEnterpriseAgentType{
		CloudEnterpriseAgentTypeCloud,
		CloudEnterpriseAgentTypeEnterpriseCluster,
		CloudEnterpriseAgentTypeEnterprise,
	}
}

// NetworkProviderType is an enumeration from the OpenAPI specification.
// Classification of the agent's network provider. It is open: values outside
// the enumeration decode and compare as their underlying string.
type NetworkProviderType string

// NetworkProviderType values.
const (
	NetworkProviderTypeUnknown       NetworkProviderType = "unknown"
	NetworkProviderTypeIsp           NetworkProviderType = "isp"
	NetworkProviderTypeCdn           NetworkProviderType = "cdn"
	NetworkProviderTypeStub          NetworkProviderType = "stub"
	NetworkProviderTypeCloudProvider NetworkProviderType = "cloud-provider"
	NetworkProviderTypeCarrier       NetworkProviderType = "carrier"
)

// String returns the value as the API spells it, or "NetworkProviderType(v)" for
// values outside the enumeration.
func (v NetworkProviderType) String() string {
	switch v {
	case NetworkProviderTypeUnknown:
		return "unknown"
	case NetworkProviderTypeIsp:
		return "isp"
	case NetworkProviderTypeCdn:
		return "cdn"
	case NetworkProviderTypeStub:
		return "stub"
	case NetworkProviderTypeCloudProvider:
		return "cloud-provider"
	case NetworkProviderTypeCarrier:
		return "carrier"
	}
	return fmt.Sprintf("NetworkProviderType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v NetworkProviderType) IsKnown() bool {
	switch v {
	case NetworkProviderTypeUnknown:
		return true
	case NetworkProviderTypeIsp:
		return true
	case NetworkProviderTypeCdn:
		return true
	case NetworkProviderTypeStub:
		return true
	case NetworkProviderTypeCloudProvider:
		return true
	case NetworkProviderTypeCarrier:
		return true
	}
	return false
}

// NetworkProviderTypeValues returns every value the specification declares, in
// specification order.
func NetworkProviderTypeValues() []NetworkProviderType {
	return []NetworkProviderType{
		NetworkProviderTypeUnknown,
		NetworkProviderTypeIsp,
		NetworkProviderTypeCdn,
		NetworkProviderTypeStub,
		NetworkProviderTypeCloudProvider,
		NetworkProviderTypeCarrier,
	}
}

// SipTestProtocol is an enumeration from the OpenAPI specification. Transport
// layer for SIP communication. It is open: values outside the enumeration
// decode and compare as their underlying string.
type SipTestProtocol string

// SipTestProtocol values.
const (
	SipTestProtocolTcp SipTestProtocol = "tcp"
	SipTestProtocolTls SipTestProtocol = "tls"
	SipTestProtocolUdp SipTestProtocol = "udp"
)

// String returns the value as the API spells it, or "SipTestProtocol(v)" for
// values outside the enumeration.
func (v SipTestProtocol) String() string {
	switch v {
	case SipTestProtocolTcp:
		return "tcp"
	case SipTestProtocolTls:
		return "tls"
	case SipTestProtocolUdp:
		return "udp"
	}
	return fmt.Sprintf("SipTestProtocol(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v SipTestProtocol) IsKnown() bool {
	switch v {
	case SipTestProtocolTcp:
		return true
	case SipTestProtocolTls:
		return true
	case SipTestProtocolUdp:
		return true
	}
	return false
}

// SipTestProtocolValues returns every value the specification declares, in
// specification order.
func SipTestProtocolValues() []SipTestProtocol {
	return []SipTestProtocol{
		SipTestProtocolTcp,
		SipTestProtocolTls,
		SipTestProtocolUdp,
	}
}

// TestIpv6Policy is an enumeration from the OpenAPI specification. IP version
// policy. It is open: values outside the enumeration decode and compare as
// their underlying string.
type TestIpv6Policy string

// TestIpv6Policy values.
const (
	TestIpv6PolicyForceIpv4      TestIpv6Policy = "force-ipv4"
	TestIpv6PolicyPreferIpv6     TestIpv6Policy = "prefer-ipv6"
	TestIpv6PolicyForceIpv6      TestIpv6Policy = "force-ipv6"
	TestIpv6PolicyUseAgentPolicy TestIpv6Policy = "use-agent-policy"
)

// String returns the value as the API spells it, or "TestIpv6Policy(v)" for
// values outside the enumeration.
func (v TestIpv6Policy) String() string {
	switch v {
	case TestIpv6PolicyForceIpv4:
		return "force-ipv4"
	case TestIpv6PolicyPreferIpv6:
		return "prefer-ipv6"
	case TestIpv6PolicyForceIpv6:
		return "force-ipv6"
	case TestIpv6PolicyUseAgentPolicy:
		return "use-agent-policy"
	}
	return fmt.Sprintf("TestIpv6Policy(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestIpv6Policy) IsKnown() bool {
	switch v {
	case TestIpv6PolicyForceIpv4:
		return true
	case TestIpv6PolicyPreferIpv6:
		return true
	case TestIpv6PolicyForceIpv6:
		return true
	case TestIpv6PolicyUseAgentPolicy:
		return true
	}
	return false
}

// TestIpv6PolicyValues returns every value the specification declares, in
// specification order.
func TestIpv6PolicyValues() []TestIpv6Policy {
	return []TestIpv6Policy{
		TestIpv6PolicyForceIpv4,
		TestIpv6PolicyPreferIpv6,
		TestIpv6PolicyForceIpv6,
		TestIpv6PolicyUseAgentPolicy,
	}
}

// TestPathTraceMode is an enumeration from the OpenAPI specification. Select
// `inSession` to perform the path trace within a TCP session. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestPathTraceMode string

// TestPathTraceMode values.
const (
	TestPathTraceModeClassic   TestPathTraceMode = "classic"
	TestPathTraceModeInSession TestPathTraceMode = "in-session"
)

// String returns the value as the API spells it, or "TestPathTraceMode(v)" for
// values outside the enumeration.
func (v TestPathTraceMode) String() string {
	switch v {
	case TestPathTraceModeClassic:
		return "classic"
	case TestPathTraceModeInSession:
		return "in-session"
	}
	return fmt.Sprintf("TestPathTraceMode(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestPathTraceMode) IsKnown() bool {
	switch v {
	case TestPathTraceModeClassic:
		return true
	case TestPathTraceModeInSession:
		return true
	}
	return false
}

// TestPathTraceModeValues returns every value the specification declares, in
// specification order.
func TestPathTraceModeValues() []TestPathTraceMode {
	return []TestPathTraceMode{
		TestPathTraceModeClassic,
		TestPathTraceModeInSession,
	}
}

// TestProbeMode is an enumeration from the OpenAPI specification. Probe mode
// used by network test, only valid when the protocol is set to TCP. It is
// open: values outside the enumeration decode and compare as their underlying
// string.
type TestProbeMode string

// TestProbeMode values.
const (
	TestProbeModeAuto TestProbeMode = "auto"
	TestProbeModeSack TestProbeMode = "sack"
	TestProbeModeSyn  TestProbeMode = "syn"
)

// String returns the value as the API spells it, or "TestProbeMode(v)" for
// values outside the enumeration.
func (v TestProbeMode) String() string {
	switch v {
	case TestProbeModeAuto:
		return "auto"
	case TestProbeModeSack:
		return "sack"
	case TestProbeModeSyn:
		return "syn"
	}
	return fmt.Sprintf("TestProbeMode(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestProbeMode) IsKnown() bool {
	switch v {
	case TestProbeModeAuto:
		return true
	case TestProbeModeSack:
		return true
	case TestProbeModeSyn:
		return true
	}
	return false
}

// TestProbeModeValues returns every value the specification declares, in
// specification order.
func TestProbeModeValues() []TestProbeMode {
	return []TestProbeMode{
		TestProbeModeAuto,
		TestProbeModeSack,
		TestProbeModeSyn,
	}
}
