// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.101)

package sip_server_instant_tests

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// SIPServerInstantTests handles communication with the SIP Server Instant Tests methods of the
	// ThousandEyes API.
	SIPServerInstantTests struct {
		client client.Client
	}
)

// NewSIPServerInstantTests returns a SIP Server Instant Tests service bound to client.
func NewSIPServerInstantTests(client client.Client) *SIPServerInstantTests {
	return &SIPServerInstantTests{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - SIP Server Instant Tests
// -----------------------------------------------------------------------------

// CreateSipServerInstantTest create SIP server instant test.
// URL: POST /tests/sip-server/instant
// Optional query params: expand
//
// Creates and runs a new SIP server instant test.
func (s *SIPServerInstantTests) CreateSipServerInstantTest(ctx context.Context, request *SipServerInstantTestRequest, opts ...client.RequestOption) (*SipServerInstantTestResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/tests/sip-server/instant"

	var result SipServerInstantTestResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
