// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package run_endpoint_instant_scheduled_tests

// EndpointRunScheduledInstantTestResult is generated from the OpenAPI specification.
type EndpointRunScheduledInstantTestResult struct {
	Message *string `json:"message,omitempty"`
}
