// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package operation_connectors

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// OperationConnectors handles communication with the Operation Connectors methods of the
	// ThousandEyes API.
	OperationConnectors struct {
		client client.Client
	}
)

// NewOperationConnectors returns a Operation Connectors service bound to client.
func NewOperationConnectors(client client.Client) *OperationConnectors {
	return &OperationConnectors{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Operation Connectors
// -----------------------------------------------------------------------------

// GetOperationConnectors retrieve connectors assigned to an operation.
// URL: GET /operations/{type}/{id}/connectors
//
// Returns a list of connectors assigned to a specific operation.
func (s *OperationConnectors) GetOperationConnectors(ctx context.Context, typeParam string, id string, opts ...client.RequestOption) (*Assignments, *resty.Response, error) {
	if typeParam == "" {
		return nil, nil, fmt.Errorf("type is required")
	}
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/operations/%s/%s/connectors", typeParam, id)

	var result Assignments

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// SetOperationConnectors assign connectors to an operation.
// URL: PUT /operations/{type}/{id}/connectors
// Optional query params: confirmDisabledObjects
//
// Assigns one or more connectors to an operation.
func (s *OperationConnectors) SetOperationConnectors(ctx context.Context, typeParam string, id string, request []string, opts ...client.RequestOption) (*Assignments, *resty.Response, error) {
	if typeParam == "" {
		return nil, nil, fmt.Errorf("type is required")
	}
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/operations/%s/%s/connectors", typeParam, id)

	var result Assignments

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
