// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package templates

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// Templates handles communication with the Templates methods of the
	// ThousandEyes API.
	Templates struct {
		client client.Client
	}
)

// NewTemplates returns a Templates service bound to client.
func NewTemplates(client client.Client) *Templates {
	return &Templates{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Templates
// -----------------------------------------------------------------------------

// GetTemplates list templates.
// URL: GET /templates
// Optional query params: certificationLevel, module, name
//
// Retrieves a list of all your templates
func (s *Templates) GetTemplates(ctx context.Context, opts ...client.RequestOption) (*TemplatesResponse, *resty.Response, error) {

	endpoint := "/templates"

	var result TemplatesResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateTemplate create template.
// URL: POST /templates
//
// Creates a template.
func (s *Templates) CreateTemplate(ctx context.Context, request *Template, opts ...client.RequestOption) (*TemplateResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/templates"

	var result TemplateResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteTemplate delete template.
// URL: DELETE /templates/{id}
//
// Deletes a template using its ID.
func (s *Templates) DeleteTemplate(ctx context.Context, id string, opts ...client.RequestOption) (*resty.Response, error) {
	if id == "" {
		return nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/templates/%s", id)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetTemplate get template.
// URL: GET /templates/{id}
//
// Gets a template using its ID.
func (s *Templates) GetTemplate(ctx context.Context, id string, opts ...client.RequestOption) (*TemplateResponse, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/templates/%s", id)

	var result TemplateResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateTemplate update template.
// URL: PUT /templates/{id}
//
// Updates an existing template.
func (s *Templates) UpdateTemplate(ctx context.Context, id string, request *Template, opts ...client.RequestOption) (*TemplateResponse, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/templates/%s", id)

	var result TemplateResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeployTemplate deploy template.
// URL: POST /templates/{id}/deploy
//
// Deploys a template, which will result in creating any of the tests, tags,
// alert rules, dashboards or other assets defined in the template.
func (s *Templates) DeployTemplate(ctx context.Context, id string, request *DeployTemplate, opts ...client.RequestOption) (*TemplateResponse, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/templates/%s/deploy", id)

	var result TemplateResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetSharingSettings get template sharing settings.
// URL: GET /templates/{id}/sharing-settings
func (s *Templates) GetSharingSettings(ctx context.Context, id string, opts ...client.RequestOption) (*SharingSettingsResponse, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/templates/%s/sharing-settings", id)

	var result SharingSettingsResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateSharingSettings update template sharing settings.
// URL: PUT /templates/{id}/sharing-settings
func (s *Templates) UpdateSharingSettings(ctx context.Context, id string, request *SharingSettings, opts ...client.RequestOption) (*SharingSettingsResponse, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/templates/%s/sharing-settings", id)

	var result SharingSettingsResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
