// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package quotas

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// Quotas handles communication with the Quotas methods of the
	// ThousandEyes API.
	Quotas struct {
		client client.Client
	}
)

// NewQuotas returns a Quotas service bound to client.
func NewQuotas(client client.Client) *Quotas {
	return &Quotas{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Quotas
// -----------------------------------------------------------------------------

// GetQuotas get organization and account group usage quota.
// URL: GET /quotas
//
// This operation retrieves usage quotas for both organization and account
// groups.
func (s *Quotas) GetQuotas(ctx context.Context, opts ...client.RequestOption) (*ResourceQuotas, *resty.Response, error) {

	endpoint := "/quotas"

	var result ResourceQuotas

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// AssignOrganizationsAccountGroupsQuotas create or update accout group quotas.
// URL: POST /quotas/account-groups/assign
//
// This operation assigns quota values to multiple account groups across
// multiple organizations.
func (s *Quotas) AssignOrganizationsAccountGroupsQuotas(ctx context.Context, request *OrganizationsQuotasAssign, opts ...client.RequestOption) (*OrganizationsQuotasAssign, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/quotas/account-groups/assign"

	var result OrganizationsQuotasAssign

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UnassignOrganizationsAccountGroupsQuotas remove account group quotas from organizations.
// URL: POST /quotas/account-groups/unassign
//
// This operation removes quotas from multiple account groups across multiple
// organizations.
func (s *Quotas) UnassignOrganizationsAccountGroupsQuotas(ctx context.Context, request *OrganizationsQuotasUnassign, opts ...client.RequestOption) (*resty.Response, error) {
	if request == nil {
		return nil, fmt.Errorf("request is required")
	}

	endpoint := "/quotas/account-groups/unassign"

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// AssignOrganizationsQuotas create or update organizations quotas.
// URL: POST /quotas/assign
//
// This operation recieves a list of organization quotas to create or update.
func (s *Quotas) AssignOrganizationsQuotas(ctx context.Context, request *QuotasAssignRequest, opts ...client.RequestOption) (*QuotasAssignResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/quotas/assign"

	var result QuotasAssignResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UnassignOrganizationsQuotas remove organization quotas.
// URL: POST /quotas/unassign
//
// This operation recieves a list of organization IDs to remove their current
// quota.
func (s *Quotas) UnassignOrganizationsQuotas(ctx context.Context, request *QuotasUnassign, opts ...client.RequestOption) (*resty.Response, error) {
	if request == nil {
		return nil, fmt.Errorf("request is required")
	}

	endpoint := "/quotas/unassign"

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}
