// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.103)

package endpoint_proxies

import (
	"context"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// EndpointProxies handles communication with the Endpoint Proxies methods of the
	// ThousandEyes API.
	EndpointProxies struct {
		client client.Client
	}
)

// NewEndpointProxies returns a Endpoint Proxies service bound to client.
func NewEndpointProxies(client client.Client) *EndpointProxies {
	return &EndpointProxies{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Endpoint Proxies
// -----------------------------------------------------------------------------

// GetEndpointProxies list endpoint proxy settings.
// URL: GET /endpoint/proxies
//
// Returns proxy settings for endpoint agents.
func (s *EndpointProxies) GetEndpointProxies(ctx context.Context, opts ...client.RequestOption) (*EndpointProxiesResponse, *resty.Response, error) {

	endpoint := "/endpoint/proxies"

	var result EndpointProxiesResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
