// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package cloud_insights_integrations

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// CloudInsightsIntegrations handles communication with the Cloud Insights Integrations methods of the
	// ThousandEyes API.
	CloudInsightsIntegrations struct {
		client client.Client
	}
)

// NewCloudInsightsIntegrations returns a Cloud Insights Integrations service bound to client.
func NewCloudInsightsIntegrations(client client.Client) *CloudInsightsIntegrations {
	return &CloudInsightsIntegrations{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Cloud Insights Integrations
// -----------------------------------------------------------------------------

// GetAllAWSMonitoringIntegrations list AWS integrations.
// URL: GET /cloud-insights/integration/aws
//
// Retrieves all AWS inventory and flow logs monitoring integrations configured
// for the authenticated account group in ThousandEyes.
func (s *CloudInsightsIntegrations) GetAllAWSMonitoringIntegrations(ctx context.Context, opts ...client.RequestOption) (*AwsMonitoringIntegrations, *resty.Response, error) {

	endpoint := "/cloud-insights/integration/aws"

	var result AwsMonitoringIntegrations

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateAWSFlowLogsMonitoringIntegration create AWS flow logs monitoring integration.
// URL: POST /cloud-insights/integration/aws/flow-logs
//
// Creates a new AWS flow logs monitoring integration.
func (s *CloudInsightsIntegrations) CreateAWSFlowLogsMonitoringIntegration(ctx context.Context, request *AwsFlowLogsIntegrationRequest, opts ...client.RequestOption) (*AwsMonitoringIntegration, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/cloud-insights/integration/aws/flow-logs"

	var result AwsMonitoringIntegration

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetAWSFlowlogsMonitoringIntegrationPolicies get AWS flow logs monitoring IAM policies.
// URL: GET /cloud-insights/integration/aws/flow-logs/policies
//
// Retrieves the AWS IAM policies required to configure an AWS flow logs
// monitoring integration in JSON string format for the authenticated account
// group.
func (s *CloudInsightsIntegrations) GetAWSFlowlogsMonitoringIntegrationPolicies(ctx context.Context, opts ...client.RequestOption) (*AwsMonitoringPoliciesJsonString, *resty.Response, error) {

	endpoint := "/cloud-insights/integration/aws/flow-logs/policies"

	var result AwsMonitoringPoliciesJsonString

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateAWSInventoryMonitoringIntegration create AWS inventory monitoring integration.
// URL: POST /cloud-insights/integration/aws/inventory
//
// Creates a new AWS inventory monitoring integration.
func (s *CloudInsightsIntegrations) CreateAWSInventoryMonitoringIntegration(ctx context.Context, request *AwsInventoryIntegrationRequest, opts ...client.RequestOption) (*AwsMonitoringIntegration, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/cloud-insights/integration/aws/inventory"

	var result AwsMonitoringIntegration

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetAWSInventoryMonitoringIntegrationPolicies get AWS inventory monitoring IAM policies.
// URL: GET /cloud-insights/integration/aws/inventory/policies
//
// Retrieves the AWS IAM policies required to configure an AWS inventory
// monitoring integration in JSON string format for the authenticated account
// group.
func (s *CloudInsightsIntegrations) GetAWSInventoryMonitoringIntegrationPolicies(ctx context.Context, opts ...client.RequestOption) (*AwsMonitoringPoliciesJsonString, *resty.Response, error) {

	endpoint := "/cloud-insights/integration/aws/inventory/policies"

	var result AwsMonitoringPoliciesJsonString

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteAwsMonitoringIntegration delete AWS integration.
// URL: DELETE /cloud-insights/integration/aws/{integrationId}
//
// Deletes a specific AWS inventory or flow logs monitoring integration using
// the AWS integration ID.
func (s *CloudInsightsIntegrations) DeleteAwsMonitoringIntegration(ctx context.Context, integrationId string, opts ...client.RequestOption) (*resty.Response, error) {
	if integrationId == "" {
		return nil, fmt.Errorf("integrationId is required")
	}

	endpoint := fmt.Sprintf("/cloud-insights/integration/aws/%s", integrationId)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetAWSMonitoringIntegration get AWS integration.
// URL: GET /cloud-insights/integration/aws/{integrationId}
//
// Retrieves details for a specific AWS inventory or flow logs monitoring
// integration associated with the authenticated account group using the unique
// integration ID.
func (s *CloudInsightsIntegrations) GetAWSMonitoringIntegration(ctx context.Context, integrationId string, opts ...client.RequestOption) (*AwsMonitoringIntegration, *resty.Response, error) {
	if integrationId == "" {
		return nil, nil, fmt.Errorf("integrationId is required")
	}

	endpoint := fmt.Sprintf("/cloud-insights/integration/aws/%s", integrationId)

	var result AwsMonitoringIntegration

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetAllAzureMonitoringIntegrations list Azure integrations.
// URL: GET /cloud-insights/integration/azure
//
// Retrieves all Azure inventory and flow logs monitoring integrations
// configured for the authenticated account group in ThousandEyes.
func (s *CloudInsightsIntegrations) GetAllAzureMonitoringIntegrations(ctx context.Context, opts ...client.RequestOption) (*AzureMonitoringIntegrations, *resty.Response, error) {

	endpoint := "/cloud-insights/integration/azure"

	var result AzureMonitoringIntegrations

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateAzureFlowLogsMonitoringIntegration create Azure flow logs monitoring integration.
// URL: POST /cloud-insights/integration/azure/flow-logs
//
// Creates a new Azure flow logs monitoring integration.
func (s *CloudInsightsIntegrations) CreateAzureFlowLogsMonitoringIntegration(ctx context.Context, request *AzureFlowLogsIntegrationRequest, opts ...client.RequestOption) (*AzureMonitoringIntegration, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/cloud-insights/integration/azure/flow-logs"

	var result AzureMonitoringIntegration

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateAzureFlowLogsMonitoringIntegration update Azure flow logs monitoring integration.
// URL: PUT /cloud-insights/integration/azure/flow-logs/{integrationId}
//
// Updates an existing Azure flow logs monitoring integration.
func (s *CloudInsightsIntegrations) UpdateAzureFlowLogsMonitoringIntegration(ctx context.Context, integrationId string, request *AzureFlowLogsIntegrationRequest, opts ...client.RequestOption) (*AzureMonitoringIntegration, *resty.Response, error) {
	if integrationId == "" {
		return nil, nil, fmt.Errorf("integrationId is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/cloud-insights/integration/azure/flow-logs/%s", integrationId)

	var result AzureMonitoringIntegration

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateAzureInventoryMonitoringIntegration create Azure inventory monitoring integration.
// URL: POST /cloud-insights/integration/azure/inventory
//
// Creates a new Azure inventory monitoring integration.
func (s *CloudInsightsIntegrations) CreateAzureInventoryMonitoringIntegration(ctx context.Context, request *AzureInventoryIntegrationRequest, opts ...client.RequestOption) (*AzureMonitoringIntegration, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/cloud-insights/integration/azure/inventory"

	var result AzureMonitoringIntegration

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateAzureInventoryMonitoringIntegration update Azure inventory monitoring integration.
// URL: PUT /cloud-insights/integration/azure/inventory/{integrationId}
//
// Updates an existing Azure inventory monitoring integration.
func (s *CloudInsightsIntegrations) UpdateAzureInventoryMonitoringIntegration(ctx context.Context, integrationId string, request *AzureInventoryIntegrationRequest, opts ...client.RequestOption) (*AzureMonitoringIntegration, *resty.Response, error) {
	if integrationId == "" {
		return nil, nil, fmt.Errorf("integrationId is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/cloud-insights/integration/azure/inventory/%s", integrationId)

	var result AzureMonitoringIntegration

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteAzureMonitoringIntegration delete Azure integration.
// URL: DELETE /cloud-insights/integration/azure/{integrationId}
//
// Deletes a specific Azure inventory or flow logs monitoring integration using
// the Azure integration ID.
func (s *CloudInsightsIntegrations) DeleteAzureMonitoringIntegration(ctx context.Context, integrationId string, opts ...client.RequestOption) (*resty.Response, error) {
	if integrationId == "" {
		return nil, fmt.Errorf("integrationId is required")
	}

	endpoint := fmt.Sprintf("/cloud-insights/integration/azure/%s", integrationId)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetAzureMonitoringIntegration get Azure integration.
// URL: GET /cloud-insights/integration/azure/{integrationId}
//
// Retrieves details for a specific Azure inventory or flow logs monitoring
// integration associated with the authenticated account group using the unique
// integration ID.
func (s *CloudInsightsIntegrations) GetAzureMonitoringIntegration(ctx context.Context, integrationId string, opts ...client.RequestOption) (*AzureMonitoringIntegration, *resty.Response, error) {
	if integrationId == "" {
		return nil, nil, fmt.Errorf("integrationId is required")
	}

	endpoint := fmt.Sprintf("/cloud-insights/integration/azure/%s", integrationId)

	var result AzureMonitoringIntegration

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
