// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.101)

package bgp_updates

import "fmt"

// BgpRpkiStatus is an enumeration from the OpenAPI specification. RPKI
// validation status for BGP data, using the validation states defined in RFC
// 6811, Section 2. It is open: values outside the enumeration decode and
// compare as their underlying string.
type BgpRpkiStatus string

// BgpRpkiStatus values.
const (
	BgpRpkiStatusValid        BgpRpkiStatus = "Valid"
	BgpRpkiStatusInvalid      BgpRpkiStatus = "Invalid"
	BgpRpkiStatusNotFound     BgpRpkiStatus = "NotFound"
	BgpRpkiStatusNotAvailable BgpRpkiStatus = "NotAvailable"
)

// String returns the value as the API spells it, or "BgpRpkiStatus(v)" for
// values outside the enumeration.
func (v BgpRpkiStatus) String() string {
	switch v {
	case BgpRpkiStatusValid:
		return "Valid"
	case BgpRpkiStatusInvalid:
		return "Invalid"
	case BgpRpkiStatusNotFound:
		return "NotFound"
	case BgpRpkiStatusNotAvailable:
		return "NotAvailable"
	}
	return fmt.Sprintf("BgpRpkiStatus(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v BgpRpkiStatus) IsKnown() bool {
	switch v {
	case BgpRpkiStatusValid:
		return true
	case BgpRpkiStatusInvalid:
		return true
	case BgpRpkiStatusNotFound:
		return true
	case BgpRpkiStatusNotAvailable:
		return true
	}
	return false
}

// BgpRpkiStatusValues returns every value the specification declares, in
// specification order.
func BgpRpkiStatusValues() []BgpRpkiStatus {
	return []BgpRpkiStatus{
		BgpRpkiStatusValid,
		BgpRpkiStatusInvalid,
		BgpRpkiStatusNotFound,
		BgpRpkiStatusNotAvailable,
	}
}

// BgpUpdateType is an enumeration from the OpenAPI specification. Type of BGP
// update. It is open: values outside the enumeration decode and compare as
// their underlying string.
type BgpUpdateType string

// BgpUpdateType values.
const (
	BgpUpdateTypeAnnouncement BgpUpdateType = "announcement"
	BgpUpdateTypeWithdrawal   BgpUpdateType = "withdrawal"
	BgpUpdateTypeUnspecified  BgpUpdateType = "unspecified"
)

// String returns the value as the API spells it, or "BgpUpdateType(v)" for
// values outside the enumeration.
func (v BgpUpdateType) String() string {
	switch v {
	case BgpUpdateTypeAnnouncement:
		return "announcement"
	case BgpUpdateTypeWithdrawal:
		return "withdrawal"
	case BgpUpdateTypeUnspecified:
		return "unspecified"
	}
	return fmt.Sprintf("BgpUpdateType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v BgpUpdateType) IsKnown() bool {
	switch v {
	case BgpUpdateTypeAnnouncement:
		return true
	case BgpUpdateTypeWithdrawal:
		return true
	case BgpUpdateTypeUnspecified:
		return true
	}
	return false
}

// BgpUpdateTypeValues returns every value the specification declares, in
// specification order.
func BgpUpdateTypeValues() []BgpUpdateType {
	return []BgpUpdateType{
		BgpUpdateTypeAnnouncement,
		BgpUpdateTypeWithdrawal,
		BgpUpdateTypeUnspecified,
	}
}

// MonitorType is an enumeration from the OpenAPI specification. Type of
// monitor It is open: values outside the enumeration decode and compare as
// their underlying string.
type MonitorType string

// MonitorType values.
const (
	MonitorTypePublic  MonitorType = "public"
	MonitorTypePrivate MonitorType = "private"
)

// String returns the value as the API spells it, or "MonitorType(v)" for
// values outside the enumeration.
func (v MonitorType) String() string {
	switch v {
	case MonitorTypePublic:
		return "public"
	case MonitorTypePrivate:
		return "private"
	}
	return fmt.Sprintf("MonitorType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v MonitorType) IsKnown() bool {
	switch v {
	case MonitorTypePublic:
		return true
	case MonitorTypePrivate:
		return true
	}
	return false
}

// MonitorTypeValues returns every value the specification declares, in
// specification order.
func MonitorTypeValues() []MonitorType {
	return []MonitorType{
		MonitorTypePublic,
		MonitorTypePrivate,
	}
}
