// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.103)

package bgp_updates

// BgpMonitor is generated from the OpenAPI specification.
type BgpMonitor struct {
	// Autonomous system number in which the monitor is found.
	Asn *int64 `json:"asn,omitempty"`
	// Country ID
	CountryID *string `json:"countryId,omitempty"`
	// IP address of the BGP monitor
	IpAddress *string `json:"ipAddress,omitempty"`
	// BGP monitor ID
	MonitorID *string `json:"monitorId,omitempty"`
	// Display name of the BGP monitor
	MonitorName *string     `json:"monitorName,omitempty"`
	MonitorType MonitorType `json:"monitorType,omitempty"`
	// Name of the autonomous system in which the monitor is found
	Network *string `json:"network,omitempty"`
}

// BgpUpdate BGP update observed by a BGP monitor.
type BgpUpdate struct {
	// AS path for the update.
	AsPath []int64 `json:"asPath"`
	// BGP communities attached to the update.
	Communities []string `json:"communities"`
	// BGP monitor that observed the update.
	Monitor *BgpMonitor `json:"monitor,omitempty"`
	// BGP monitor ID that observed the update.
	MonitorID *string `json:"monitorId,omitempty"`
	// Origin autonomous system (AS) number.
	OriginAs int64 `json:"originAs"`
	// IP prefix in CIDR notation.
	Prefix string `json:"prefix"`
	// RPKI validation status for the update, using the validation states defined
	// in RFC 6811, Section 2.
	RpkiStatus BgpRpkiStatus `json:"rpkiStatus"`
	// Date and time when the update was observed.
	Timestamp string `json:"timestamp"`
	// Type of BGP update.
	UpdateType BgpUpdateType `json:"updateType"`
}

// BgpUpdates is generated from the OpenAPI specification.
type BgpUpdates struct {
	Links   *PaginationLinks `json:"_links,omitempty"`
	Updates []BgpUpdate      `json:"updates,omitempty"`
}

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// PaginationLinks A links object containing pagination related link(s).
type PaginationLinks struct {
	Next     *Link `json:"next,omitempty"`
	Previous *Link `json:"previous,omitempty"`
	Self     *Link `json:"self,omitempty"`
}
