// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.103)

package bgp_updates

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// BGPUpdates handles communication with the BGP Updates methods of the
	// ThousandEyes API.
	BGPUpdates struct {
		client client.Client
	}
)

// NewBGPUpdates returns a BGP Updates service bound to client.
func NewBGPUpdates(client client.Client) *BGPUpdates {
	return &BGPUpdates{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - BGP Updates
// -----------------------------------------------------------------------------

// GetBgpUpdates list BGP updates.
// URL: GET /bgp/updates
// Optional query params: max, cursor, expand, startDate, endDate, prefix, originAs, asPath, rpkiStatus, updateType, monitor, communities
//
// Retrieves a paginated list of BGP updates for prefixes tracked by the
// account group.
//
// Fetches every page. Bound the walk with client.WithMaxPages.
func (s *BGPUpdates) GetBgpUpdates(ctx context.Context, opts ...client.RequestOption) (*BgpUpdates, *resty.Response, error) {

	endpoint := "/bgp/updates"

	var result BgpUpdates

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	// The collection arrives across pages linked by _links.next. Fetching only
	// the first would silently truncate the result, so every page is merged.
	// Bound the walk with client.WithMaxPages when that is not wanted.
	var items []BgpUpdate
	merge := func(page []byte) error {
		var batch []BgpUpdate
		if err := json.Unmarshal(page, &batch); err != nil {
			return fmt.Errorf("decoding updates page: %w", err)
		}
		items = append(items, batch...)
		return nil
	}

	resp, err := req.GetPaginated(endpoint, "updates", merge)
	if err != nil {
		return nil, resp, err
	}
	result.Updates = items

	return &result, resp, nil
}
