// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.98)

package alert_suppression_windows

import "fmt"

// AlertSuppressionWindowState is an enumeration from the OpenAPI
// specification. Indicates the current status of the suppression window. It is
// open: values outside the enumeration decode and compare as their underlying
// string.
type AlertSuppressionWindowState string

// AlertSuppressionWindowState values.
const (
	AlertSuppressionWindowStateActive   AlertSuppressionWindowState = "active"
	AlertSuppressionWindowStateInactive AlertSuppressionWindowState = "inactive"
	AlertSuppressionWindowStateEnded    AlertSuppressionWindowState = "ended"
)

// String returns the value as the API spells it, or "AlertSuppressionWindowState(v)" for
// values outside the enumeration.
func (v AlertSuppressionWindowState) String() string {
	switch v {
	case AlertSuppressionWindowStateActive:
		return "active"
	case AlertSuppressionWindowStateInactive:
		return "inactive"
	case AlertSuppressionWindowStateEnded:
		return "ended"
	}
	return fmt.Sprintf("AlertSuppressionWindowState(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v AlertSuppressionWindowState) IsKnown() bool {
	switch v {
	case AlertSuppressionWindowStateActive:
		return true
	case AlertSuppressionWindowStateInactive:
		return true
	case AlertSuppressionWindowStateEnded:
		return true
	}
	return false
}

// AlertSuppressionWindowStateValues returns every value the specification declares, in
// specification order.
func AlertSuppressionWindowStateValues() []AlertSuppressionWindowState {
	return []AlertSuppressionWindowState{
		AlertSuppressionWindowStateActive,
		AlertSuppressionWindowStateInactive,
		AlertSuppressionWindowStateEnded,
	}
}

// DaysOfWeek is an enumeration from the OpenAPI specification. Specifies the
// day to activate the alert suppression window. It is open: values outside the
// enumeration decode and compare as their underlying string.
type DaysOfWeek string

// DaysOfWeek values.
const (
	DaysOfWeekSun DaysOfWeek = "sun"
	DaysOfWeekMon DaysOfWeek = "mon"
	DaysOfWeekTue DaysOfWeek = "tue"
	DaysOfWeekWed DaysOfWeek = "wed"
	DaysOfWeekThu DaysOfWeek = "thu"
	DaysOfWeekFri DaysOfWeek = "fri"
	DaysOfWeekSat DaysOfWeek = "sat"
)

// String returns the value as the API spells it, or "DaysOfWeek(v)" for
// values outside the enumeration.
func (v DaysOfWeek) String() string {
	switch v {
	case DaysOfWeekSun:
		return "sun"
	case DaysOfWeekMon:
		return "mon"
	case DaysOfWeekTue:
		return "tue"
	case DaysOfWeekWed:
		return "wed"
	case DaysOfWeekThu:
		return "thu"
	case DaysOfWeekFri:
		return "fri"
	case DaysOfWeekSat:
		return "sat"
	}
	return fmt.Sprintf("DaysOfWeek(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v DaysOfWeek) IsKnown() bool {
	switch v {
	case DaysOfWeekSun:
		return true
	case DaysOfWeekMon:
		return true
	case DaysOfWeekTue:
		return true
	case DaysOfWeekWed:
		return true
	case DaysOfWeekThu:
		return true
	case DaysOfWeekFri:
		return true
	case DaysOfWeekSat:
		return true
	}
	return false
}

// DaysOfWeekValues returns every value the specification declares, in
// specification order.
func DaysOfWeekValues() []DaysOfWeek {
	return []DaysOfWeek{
		DaysOfWeekSun,
		DaysOfWeekMon,
		DaysOfWeekTue,
		DaysOfWeekWed,
		DaysOfWeekThu,
		DaysOfWeekFri,
		DaysOfWeekSat,
	}
}

// EndRepeatType is an enumeration from the OpenAPI specification. End repeat
// options type. It is open: values outside the enumeration decode and compare
// as their underlying string.
type EndRepeatType string

// EndRepeatType values.
const (
	EndRepeatTypeCount EndRepeatType = "count"
	EndRepeatTypeNever EndRepeatType = "never"
	EndRepeatTypeDate  EndRepeatType = "date"
)

// String returns the value as the API spells it, or "EndRepeatType(v)" for
// values outside the enumeration.
func (v EndRepeatType) String() string {
	switch v {
	case EndRepeatTypeCount:
		return "count"
	case EndRepeatTypeNever:
		return "never"
	case EndRepeatTypeDate:
		return "date"
	}
	return fmt.Sprintf("EndRepeatType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v EndRepeatType) IsKnown() bool {
	switch v {
	case EndRepeatTypeCount:
		return true
	case EndRepeatTypeNever:
		return true
	case EndRepeatTypeDate:
		return true
	}
	return false
}

// EndRepeatTypeValues returns every value the specification declares, in
// specification order.
func EndRepeatTypeValues() []EndRepeatType {
	return []EndRepeatType{
		EndRepeatTypeCount,
		EndRepeatTypeNever,
		EndRepeatTypeDate,
	}
}

// IntervalType is an enumeration from the OpenAPI specification. Repeat
// options interval type It is open: values outside the enumeration decode and
// compare as their underlying string.
type IntervalType string

// IntervalType values.
const (
	IntervalTypeDay   IntervalType = "day"
	IntervalTypeWeek  IntervalType = "week"
	IntervalTypeMonth IntervalType = "month"
)

// String returns the value as the API spells it, or "IntervalType(v)" for
// values outside the enumeration.
func (v IntervalType) String() string {
	switch v {
	case IntervalTypeDay:
		return "day"
	case IntervalTypeWeek:
		return "week"
	case IntervalTypeMonth:
		return "month"
	}
	return fmt.Sprintf("IntervalType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v IntervalType) IsKnown() bool {
	switch v {
	case IntervalTypeDay:
		return true
	case IntervalTypeWeek:
		return true
	case IntervalTypeMonth:
		return true
	}
	return false
}

// IntervalTypeValues returns every value the specification declares, in
// specification order.
func IntervalTypeValues() []IntervalType {
	return []IntervalType{
		IntervalTypeDay,
		IntervalTypeWeek,
		IntervalTypeMonth,
	}
}

// RepeatType is an enumeration from the OpenAPI specification. Repeat options
// type. It is open: values outside the enumeration decode and compare as their
// underlying string.
type RepeatType string

// RepeatType values.
const (
	RepeatTypeDay    RepeatType = "day"
	RepeatTypeWeek   RepeatType = "week"
	RepeatTypeMonth  RepeatType = "month"
	RepeatTypeCustom RepeatType = "custom"
)

// String returns the value as the API spells it, or "RepeatType(v)" for
// values outside the enumeration.
func (v RepeatType) String() string {
	switch v {
	case RepeatTypeDay:
		return "day"
	case RepeatTypeWeek:
		return "week"
	case RepeatTypeMonth:
		return "month"
	case RepeatTypeCustom:
		return "custom"
	}
	return fmt.Sprintf("RepeatType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v RepeatType) IsKnown() bool {
	switch v {
	case RepeatTypeDay:
		return true
	case RepeatTypeWeek:
		return true
	case RepeatTypeMonth:
		return true
	case RepeatTypeCustom:
		return true
	}
	return false
}

// RepeatTypeValues returns every value the specification declares, in
// specification order.
func RepeatTypeValues() []RepeatType {
	return []RepeatType{
		RepeatTypeDay,
		RepeatTypeWeek,
		RepeatTypeMonth,
		RepeatTypeCustom,
	}
}

// TestInterval is an enumeration from the OpenAPI specification. Interval
// between test runs in seconds. It is open: values outside the enumeration
// decode and compare as their underlying int.
type TestInterval int

// TestInterval values.
const (
	TestIntervalN60   TestInterval = 60
	TestIntervalN120  TestInterval = 120
	TestIntervalN300  TestInterval = 300
	TestIntervalN600  TestInterval = 600
	TestIntervalN900  TestInterval = 900
	TestIntervalN1800 TestInterval = 1800
	TestIntervalN3600 TestInterval = 3600
)

// String returns the value as the API spells it, or "TestInterval(v)" for
// values outside the enumeration.
func (v TestInterval) String() string {
	switch v {
	case TestIntervalN60:
		return "60"
	case TestIntervalN120:
		return "120"
	case TestIntervalN300:
		return "300"
	case TestIntervalN600:
		return "600"
	case TestIntervalN900:
		return "900"
	case TestIntervalN1800:
		return "1800"
	case TestIntervalN3600:
		return "3600"
	}
	return fmt.Sprintf("TestInterval(%v)", int(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestInterval) IsKnown() bool {
	switch v {
	case TestIntervalN60:
		return true
	case TestIntervalN120:
		return true
	case TestIntervalN300:
		return true
	case TestIntervalN600:
		return true
	case TestIntervalN900:
		return true
	case TestIntervalN1800:
		return true
	case TestIntervalN3600:
		return true
	}
	return false
}

// TestIntervalValues returns every value the specification declares, in
// specification order.
func TestIntervalValues() []TestInterval {
	return []TestInterval{
		TestIntervalN60,
		TestIntervalN120,
		TestIntervalN300,
		TestIntervalN600,
		TestIntervalN900,
		TestIntervalN1800,
		TestIntervalN3600,
	}
}

// TestType is an enumeration from the OpenAPI specification. This is a read
// only value, as test type is implicit in the test creation url. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestType string

// TestType values.
const (
	TestTypeApi             TestType = "api"
	TestTypeAgentToAgent    TestType = "agent-to-agent"
	TestTypeAgentToServer   TestType = "agent-to-server"
	TestTypeBgp             TestType = "bgp"
	TestTypeHttpServer      TestType = "http-server"
	TestTypePageLoad        TestType = "page-load"
	TestTypeWebTransactions TestType = "web-transactions"
	TestTypeFtpServer       TestType = "ftp-server"
	TestTypeDnsTrace        TestType = "dns-trace"
	TestTypeDnsServer       TestType = "dns-server"
	TestTypeDnssec          TestType = "dnssec"
	TestTypeSipServer       TestType = "sip-server"
	TestTypeVoice           TestType = "voice"
)

// String returns the value as the API spells it, or "TestType(v)" for
// values outside the enumeration.
func (v TestType) String() string {
	switch v {
	case TestTypeApi:
		return "api"
	case TestTypeAgentToAgent:
		return "agent-to-agent"
	case TestTypeAgentToServer:
		return "agent-to-server"
	case TestTypeBgp:
		return "bgp"
	case TestTypeHttpServer:
		return "http-server"
	case TestTypePageLoad:
		return "page-load"
	case TestTypeWebTransactions:
		return "web-transactions"
	case TestTypeFtpServer:
		return "ftp-server"
	case TestTypeDnsTrace:
		return "dns-trace"
	case TestTypeDnsServer:
		return "dns-server"
	case TestTypeDnssec:
		return "dnssec"
	case TestTypeSipServer:
		return "sip-server"
	case TestTypeVoice:
		return "voice"
	}
	return fmt.Sprintf("TestType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestType) IsKnown() bool {
	switch v {
	case TestTypeApi:
		return true
	case TestTypeAgentToAgent:
		return true
	case TestTypeAgentToServer:
		return true
	case TestTypeBgp:
		return true
	case TestTypeHttpServer:
		return true
	case TestTypePageLoad:
		return true
	case TestTypeWebTransactions:
		return true
	case TestTypeFtpServer:
		return true
	case TestTypeDnsTrace:
		return true
	case TestTypeDnsServer:
		return true
	case TestTypeDnssec:
		return true
	case TestTypeSipServer:
		return true
	case TestTypeVoice:
		return true
	}
	return false
}

// TestTypeValues returns every value the specification declares, in
// specification order.
func TestTypeValues() []TestType {
	return []TestType{
		TestTypeApi,
		TestTypeAgentToAgent,
		TestTypeAgentToServer,
		TestTypeBgp,
		TestTypeHttpServer,
		TestTypePageLoad,
		TestTypeWebTransactions,
		TestTypeFtpServer,
		TestTypeDnsTrace,
		TestTypeDnsServer,
		TestTypeDnssec,
		TestTypeSipServer,
		TestTypeVoice,
	}
}
