// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.103)

package agent_proxies

// ResourceAgentProxies is generated from the OpenAPI specification.
type ResourceAgentProxies struct {
	Links        *SelfLinks   `json:"_links,omitempty"`
	AgentProxies []AgentProxy `json:"agentProxies,omitempty"`
}

// AgentProxy is generated from the OpenAPI specification.
type AgentProxy struct {
	// Account id that this proxy configuration belongs to
	AID      *string       `json:"aid,omitempty"`
	AuthType ProxyAuthType `json:"authType,omitempty"`
	// A list of hostnames, network prefixes, or wildcards used to determine which
	// test targets should not be proxied.
	BypassList []string `json:"bypassList,omitempty"`
	// Set to `true` if this proxy configuration comes from the agent’s config
	// file.
	IsLocalConfigured *bool `json:"isLocalConfigured,omitempty"`
	// Last modification timestamp of the proxy.
	LastModified *string `json:"lastModified,omitempty"`
	// The location of the proxy.
	Location *string `json:"location,omitempty"`
	// Expression of agent notification rule.
	Name *string `json:"name,omitempty"`
	// Password for proxy authentication
	Password *string `json:"password,omitempty"`
	// Agent proxy's unique ID.
	ProxyID *string   `json:"proxyId,omitempty"`
	Type    ProxyType `json:"type,omitempty"`
	// Username for proxy authentication.
	User *string `json:"user,omitempty"`
}

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self *Link `json:"self,omitempty"`
}
