// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package agent_proxies

import (
	"context"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// AgentProxies handles communication with the Agent Proxies methods of the
	// ThousandEyes API.
	AgentProxies struct {
		client client.Client
	}
)

// NewAgentProxies returns a Agent Proxies service bound to client.
func NewAgentProxies(client client.Client) *AgentProxies {
	return &AgentProxies{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Agent Proxies
// -----------------------------------------------------------------------------

// GetAgentsProxies list Enterprise Agent Proxies.
// URL: GET /agents/proxies
//
// List all enterprise agent proxies available under the account group.
func (s *AgentProxies) GetAgentsProxies(ctx context.Context, opts ...client.RequestOption) (*ResourceAgentProxies, *resty.Response, error) {

	endpoint := "/agents/proxies"

	var result ResourceAgentProxies

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
