// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.98)

package alerts

import "fmt"

// AlertType is an enumeration from the OpenAPI specification. Type of alert
// being triggered. It is open: values outside the enumeration decode and
// compare as their underlying string.
type AlertType string

// AlertType values.
const (
	AlertTypePageLoad                           AlertType = "page-load"
	AlertTypeHttpServer                         AlertType = "http-server"
	AlertTypeEndToEndServer                     AlertType = "end-to-end-server"
	AlertTypeEndToEndAgent                      AlertType = "end-to-end-agent"
	AlertTypeVoice                              AlertType = "voice"
	AlertTypeDnsServer                          AlertType = "dns-server"
	AlertTypeDnsTrace                           AlertType = "dns-trace"
	AlertTypeDnssec                             AlertType = "dnssec"
	AlertTypeBgp                                AlertType = "bgp"
	AlertTypePathTrace                          AlertType = "path-trace"
	AlertTypeFtp                                AlertType = "ftp"
	AlertTypeSipServer                          AlertType = "sip-server"
	AlertTypeTransactions                       AlertType = "transactions"
	AlertTypeWebTransactions                    AlertType = "web-transactions"
	AlertTypeAgent                              AlertType = "agent"
	AlertTypeNetworkOutage                      AlertType = "network-outage"
	AlertTypeApplicationOutage                  AlertType = "application-outage"
	AlertTypeDeviceDevice                       AlertType = "device-device"
	AlertTypeDeviceInterface                    AlertType = "device-interface"
	AlertTypeEndpointNetworkServer              AlertType = "endpoint-network-server"
	AlertTypeEndpointHttpServer                 AlertType = "endpoint-http-server"
	AlertTypeEndpointPathTrace                  AlertType = "endpoint-path-trace"
	AlertTypeEndpointBrowserSessionsAgent       AlertType = "endpoint-browser-sessions-agent"
	AlertTypeEndpointBrowserSessionsApplication AlertType = "endpoint-browser-sessions-application"
	AlertTypeApi                                AlertType = "api"
	AlertTypeWebTransaction                     AlertType = "web-transaction"
	AlertTypeUnknown                            AlertType = "unknown"
)

// String returns the value as the API spells it, or "AlertType(v)" for
// values outside the enumeration.
func (v AlertType) String() string {
	switch v {
	case AlertTypePageLoad:
		return "page-load"
	case AlertTypeHttpServer:
		return "http-server"
	case AlertTypeEndToEndServer:
		return "end-to-end-server"
	case AlertTypeEndToEndAgent:
		return "end-to-end-agent"
	case AlertTypeVoice:
		return "voice"
	case AlertTypeDnsServer:
		return "dns-server"
	case AlertTypeDnsTrace:
		return "dns-trace"
	case AlertTypeDnssec:
		return "dnssec"
	case AlertTypeBgp:
		return "bgp"
	case AlertTypePathTrace:
		return "path-trace"
	case AlertTypeFtp:
		return "ftp"
	case AlertTypeSipServer:
		return "sip-server"
	case AlertTypeTransactions:
		return "transactions"
	case AlertTypeWebTransactions:
		return "web-transactions"
	case AlertTypeAgent:
		return "agent"
	case AlertTypeNetworkOutage:
		return "network-outage"
	case AlertTypeApplicationOutage:
		return "application-outage"
	case AlertTypeDeviceDevice:
		return "device-device"
	case AlertTypeDeviceInterface:
		return "device-interface"
	case AlertTypeEndpointNetworkServer:
		return "endpoint-network-server"
	case AlertTypeEndpointHttpServer:
		return "endpoint-http-server"
	case AlertTypeEndpointPathTrace:
		return "endpoint-path-trace"
	case AlertTypeEndpointBrowserSessionsAgent:
		return "endpoint-browser-sessions-agent"
	case AlertTypeEndpointBrowserSessionsApplication:
		return "endpoint-browser-sessions-application"
	case AlertTypeApi:
		return "api"
	case AlertTypeWebTransaction:
		return "web-transaction"
	case AlertTypeUnknown:
		return "unknown"
	}
	return fmt.Sprintf("AlertType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v AlertType) IsKnown() bool {
	switch v {
	case AlertTypePageLoad:
		return true
	case AlertTypeHttpServer:
		return true
	case AlertTypeEndToEndServer:
		return true
	case AlertTypeEndToEndAgent:
		return true
	case AlertTypeVoice:
		return true
	case AlertTypeDnsServer:
		return true
	case AlertTypeDnsTrace:
		return true
	case AlertTypeDnssec:
		return true
	case AlertTypeBgp:
		return true
	case AlertTypePathTrace:
		return true
	case AlertTypeFtp:
		return true
	case AlertTypeSipServer:
		return true
	case AlertTypeTransactions:
		return true
	case AlertTypeWebTransactions:
		return true
	case AlertTypeAgent:
		return true
	case AlertTypeNetworkOutage:
		return true
	case AlertTypeApplicationOutage:
		return true
	case AlertTypeDeviceDevice:
		return true
	case AlertTypeDeviceInterface:
		return true
	case AlertTypeEndpointNetworkServer:
		return true
	case AlertTypeEndpointHttpServer:
		return true
	case AlertTypeEndpointPathTrace:
		return true
	case AlertTypeEndpointBrowserSessionsAgent:
		return true
	case AlertTypeEndpointBrowserSessionsApplication:
		return true
	case AlertTypeApi:
		return true
	case AlertTypeWebTransaction:
		return true
	case AlertTypeUnknown:
		return true
	}
	return false
}

// AlertTypeValues returns every value the specification declares, in
// specification order.
func AlertTypeValues() []AlertType {
	return []AlertType{
		AlertTypePageLoad,
		AlertTypeHttpServer,
		AlertTypeEndToEndServer,
		AlertTypeEndToEndAgent,
		AlertTypeVoice,
		AlertTypeDnsServer,
		AlertTypeDnsTrace,
		AlertTypeDnssec,
		AlertTypeBgp,
		AlertTypePathTrace,
		AlertTypeFtp,
		AlertTypeSipServer,
		AlertTypeTransactions,
		AlertTypeWebTransactions,
		AlertTypeAgent,
		AlertTypeNetworkOutage,
		AlertTypeApplicationOutage,
		AlertTypeDeviceDevice,
		AlertTypeDeviceInterface,
		AlertTypeEndpointNetworkServer,
		AlertTypeEndpointHttpServer,
		AlertTypeEndpointPathTrace,
		AlertTypeEndpointBrowserSessionsAgent,
		AlertTypeEndpointBrowserSessionsApplication,
		AlertTypeApi,
		AlertTypeWebTransaction,
		AlertTypeUnknown,
	}
}

// Severity is an enumeration from the OpenAPI specification. The severity of
// the alert. It is open: values outside the enumeration decode and compare as
// their underlying string.
type Severity string

// Severity values.
const (
	SeverityInfo     Severity = "info"
	SeverityMajor    Severity = "major"
	SeverityMinor    Severity = "minor"
	SeverityCritical Severity = "critical"
	SeverityUnknown  Severity = "unknown"
)

// String returns the value as the API spells it, or "Severity(v)" for
// values outside the enumeration.
func (v Severity) String() string {
	switch v {
	case SeverityInfo:
		return "info"
	case SeverityMajor:
		return "major"
	case SeverityMinor:
		return "minor"
	case SeverityCritical:
		return "critical"
	case SeverityUnknown:
		return "unknown"
	}
	return fmt.Sprintf("Severity(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v Severity) IsKnown() bool {
	switch v {
	case SeverityInfo:
		return true
	case SeverityMajor:
		return true
	case SeverityMinor:
		return true
	case SeverityCritical:
		return true
	case SeverityUnknown:
		return true
	}
	return false
}

// SeverityValues returns every value the specification declares, in
// specification order.
func SeverityValues() []Severity {
	return []Severity{
		SeverityInfo,
		SeverityMajor,
		SeverityMinor,
		SeverityCritical,
		SeverityUnknown,
	}
}

// State is an enumeration from the OpenAPI specification. Current state of the
// alert. It is open: values outside the enumeration decode and compare as
// their underlying string.
type State string

// State values.
const (
	StateClear   State = "clear"
	StateTrigger State = "trigger"
)

// String returns the value as the API spells it, or "State(v)" for
// values outside the enumeration.
func (v State) String() string {
	switch v {
	case StateClear:
		return "clear"
	case StateTrigger:
		return "trigger"
	}
	return fmt.Sprintf("State(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v State) IsKnown() bool {
	switch v {
	case StateClear:
		return true
	case StateTrigger:
		return true
	}
	return false
}

// StateValues returns every value the specification declares, in
// specification order.
func StateValues() []State {
	return []State{
		StateClear,
		StateTrigger,
	}
}
