// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package account_groups

// AccountGroup is generated from the OpenAPI specification.
type AccountGroup struct {
	// Account group name
	AccountGroupName *string        `json:"accountGroupName,omitempty"`
	AID              AccountGroupId `json:"aid,omitempty"`
}

// AccountGroupDetail is generated from the OpenAPI specification.
type AccountGroupDetail struct {
	Links SelfLinks `json:"_links,omitempty"`
	// Account group name
	AccountGroupName *string           `json:"accountGroupName,omitempty"`
	AccountToken     AccountGroupToken `json:"accountToken,omitempty"`
	Agents           []EnterpriseAgent `json:"agents,omitempty"`
	AID              AccountGroupId    `json:"aid,omitempty"`
	// Indicates whether the requested aid is the context of the current account.
	IsCurrentAccountGroup *bool `json:"isCurrentAccountGroup,omitempty"`
	// Indicates whether the aid is the default one for the requesting user.
	IsDefaultAccountGroup *bool `json:"isDefaultAccountGroup,omitempty"`
	// (Optional) The ID for the organization associated with the account group.
	OrgID *string `json:"orgId,omitempty"`
	// (Optional) The name of the organization associated with the account group.
	OrganizationName *string            `json:"organizationName,omitempty"`
	Users            []UserAccountGroup `json:"users,omitempty"`
}

// AccountGroupId A unique identifier associated with your account group. You
// can retrieve your `AccountGroupId` from the `/account-groups` endpoint.
type AccountGroupId string

// AccountGroupInfo is generated from the OpenAPI specification.
type AccountGroupInfo struct {
	// Account group name
	AccountGroupName *string        `json:"accountGroupName,omitempty"`
	AID              AccountGroupId `json:"aid,omitempty"`
	// Indicates whether the requested aid is the context of the current account.
	IsCurrentAccountGroup *bool `json:"isCurrentAccountGroup,omitempty"`
	// Indicates whether the aid is the default one for the requesting user.
	IsDefaultAccountGroup *bool `json:"isDefaultAccountGroup,omitempty"`
	// (Optional) The ID for the organization associated with the account group.
	OrgID *string `json:"orgId,omitempty"`
	// (Optional) The name of the organization associated with the account group.
	OrganizationName *string `json:"organizationName,omitempty"`
}

// AccountGroupRequest is generated from the OpenAPI specification.
type AccountGroupRequest struct {
	// The name of the account group
	AccountGroupName string `json:"accountGroupName"`
	// To grant access to enterprise agents, specify the agent list.
	Agents []string `json:"agents,omitempty"`
}

// AccountGroupToken The account group token is an alphanumeric string used to
// bind an Enterprise Agent to a specific account group. This token is not a
// password that must be kept secret. You can retrieve your `AccountGroupToken`
// from the `/account-groups/{id}` endpoint.
type AccountGroupToken string

// ResourceAccountGroups is generated from the OpenAPI specification.
type ResourceAccountGroups struct {
	Links                 SelfLinks          `json:"_links,omitempty"`
	ResourceAccountGroups []AccountGroupInfo `json:"accountGroups,omitempty"`
}

// ClusterMember is generated from the OpenAPI specification.
type ClusterMember struct {
	AgentState EnterpriseAgentState `json:"agentState,omitempty"`
	// If an enterprise agent or a cluster member presents at least one error, the
	// errors will be shown as an array of entries in the errorDetails field
	// (Enterprise Agents and Enterprise Cluster members only)
	ErrorDetails []ErrorDetail `json:"errorDetails,omitempty"`
	// Array of private IP addresses.
	IpAddresses []string `json:"ipAddresses,omitempty"`
	// UTC last seen date (ISO date-time format).
	LastSeen *string `json:"lastSeen,omitempty"`
	// Unique ID of the cluster member
	MemberID *string `json:"memberId,omitempty"`
	// Name of the cluster member
	Name *string `json:"name,omitempty"`
	// Network (including ASN) of agent’s public IP.
	Network *string `json:"network,omitempty"`
	// Array of public IP addresses.
	PublicIpAddresses []string                    `json:"publicIpAddresses,omitempty"`
	SerialNumber      EnterpriseAgentSerialNumber `json:"serialNumber,omitempty"`
	// Test target IP address.
	TargetForTests *string `json:"targetForTests,omitempty"`
	// Shows overall utilization percentage (online Enterprise Agents and
	// Enterprise Clusters only).
	Utilization *int `json:"utilization,omitempty"`
}

// ClusterMembers If an enterprise agent is clustered, detailed information
// about each cluster member will be shown as array entries in the
// clusterMembers field. This field is not shown for Enterprise Agents in
// standalone mode, or for Cloud Agents.
type ClusterMembers []ClusterMember

// Coordinates Geographic coordinates for agent location.
type Coordinates struct {
	// The latitude of the agent location in decimal degrees
	Latitude *float64 `json:"latitude,omitempty"`
	// The longitude of the agent location in decimal degrees
	Longitude *float64 `json:"longitude,omitempty"`
}

// CreatedAccountGroup is generated from the OpenAPI specification.
type CreatedAccountGroup struct {
	Links SelfLinks `json:"_links,omitempty"`
	// Account group name
	AccountGroupName *string        `json:"accountGroupName,omitempty"`
	AID              AccountGroupId `json:"aid,omitempty"`
	// Indicates whether the requested aid is the context of the current account.
	IsCurrentAccountGroup *bool `json:"isCurrentAccountGroup,omitempty"`
	// Indicates whether the aid is the default one for the requesting user.
	IsDefaultAccountGroup *bool `json:"isDefaultAccountGroup,omitempty"`
	// (Optional) The ID for the organization associated with the account group.
	OrgID *string `json:"orgId,omitempty"`
	// (Optional) The name of the organization associated with the account group.
	OrganizationName *string            `json:"organizationName,omitempty"`
	Users            []UserAccountGroup `json:"users,omitempty"`
}

// Enabled Test is enabled.
type Enabled bool

// EnterpriseAgent is generated from the OpenAPI specification.
type EnterpriseAgent struct {
	// List of account groups.
	ResourceAccountGroups []AccountGroup `json:"accountGroups,omitempty"`
	// Unique ID of the agent.
	AgentID *string `json:"agentId,omitempty"`
	// Name of the agent.
	AgentName      *string                  `json:"agentName,omitempty"`
	AgentState     EnterpriseAgentState     `json:"agentState,omitempty"`
	AgentType      CloudEnterpriseAgentType `json:"agentType"`
	ClusterMembers ClusterMembers           `json:"clusterMembers,omitempty"`
	Coordinates    Coordinates              `json:"coordinates,omitempty"`
	// 2-digit ISO country code
	CountryID *string `json:"countryId,omitempty"`
	// UTC Agent creation date (ISO date-time format).
	CreatedDate *string `json:"createdDate,omitempty"`
	// Flag indicating if the agent is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// If an enterprise agent or a cluster member presents at least one error, the
	// errors will be shown as an array of entries in the errorDetails field
	// (Enterprise Agents and Enterprise Cluster members only)
	ErrorDetails []ErrorDetail `json:"errorDetails,omitempty"`
	// Fully qualified domain name of the agent (Enterprise Agents only)
	Hostname           *string              `json:"hostname,omitempty"`
	InterfaceIpMapping []InterfaceIpMapping `json:"interfaceIpMapping,omitempty"`
	// Array of private IP addresses.
	IpAddresses []string                  `json:"ipAddresses,omitempty"`
	Ipv6Policy  EnterpriseAgentIpv6Policy `json:"ipv6Policy,omitempty"`
	// Flag indicating if the agent retains cache.
	KeepBrowserCache *bool `json:"keepBrowserCache,omitempty"`
	// UTC last seen date (ISO date-time format).
	LastSeen *string `json:"lastSeen,omitempty"`
	// To perform rDNS lookups for public IP ranges, this field represents the
	// public IP ranges.
	LocalResolutionPrefixes []string `json:"localResolutionPrefixes,omitempty"`
	// Location of the agent.
	Location *string `json:"location,omitempty"`
	// Network (including ASN) of agent’s public IP.
	Network             *string             `json:"network,omitempty"`
	NetworkProviderInfo NetworkProviderInfo `json:"networkProviderInfo,omitempty"`
	// Prefix containing agents public IP address.
	Prefix *string `json:"prefix,omitempty"`
	// Array of public IP addresses.
	PublicIpAddresses []string                    `json:"publicIpAddresses,omitempty"`
	SerialNumber      EnterpriseAgentSerialNumber `json:"serialNumber,omitempty"`
	// Test target IP address.
	TargetForTests *string `json:"targetForTests,omitempty"`
	TestIds        TestIds `json:"testIds,omitempty"`
	// List of tests.
	Tests []SimpleTest `json:"tests,omitempty"`
	// Shows overall utilization percentage (online Enterprise Agents and
	// Enterprise Clusters only).
	Utilization *int `json:"utilization,omitempty"`
	// Flag indicating if has normal SSL operations or if instead it's set to
	// ignore SSL errors on browserbot-based tests.
	VerifySslCertificates *bool `json:"verifySslCertificates,omitempty"`
}

// EnterpriseAgentSerialNumber Serial number of an enterprise agent or cluster
// member device. This field is not available for Cloud Agents.
type EnterpriseAgentSerialNumber string

// ErrorDetail is generated from the OpenAPI specification.
type ErrorDetail struct {
	Code ErrorDetailCode `json:"code,omitempty"`
	// Description for the agent error.
	Description *string `json:"description,omitempty"`
}

// InterfaceIpMapping is generated from the OpenAPI specification.
type InterfaceIpMapping struct {
	// Name of the mapping
	InterfaceName *string `json:"interfaceName,omitempty"`
	// Array of ipAddress entries
	IpAddresses []string `json:"ipAddresses,omitempty"`
}

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// NetworkProviderInfo Information about the network provider that owns the
// agent's public IP prefix.
type NetworkProviderInfo struct {
	// Autonomous System Number (ASN) announcing the agent's public IP prefix.
	Asn *int64 `json:"asn,omitempty"`
	// Name of the network provider organization.
	Name *string             `json:"name,omitempty"`
	Type NetworkProviderType `json:"type,omitempty"`
}

// Role is generated from the OpenAPI specification.
type Role struct {
	// Flag indicating whether the user has management permissions.
	HasManagementPermissions *bool `json:"hasManagementPermissions,omitempty"`
	// Flag indicating if the role is built-in (Account Admin, Organization Admin,
	// Regular User).
	IsBuiltin *bool `json:"isBuiltin,omitempty"`
	// Name of the role.
	Name *string `json:"name,omitempty"`
	// Unique ID representing the role.
	RoleID *string `json:"roleId,omitempty"`
}

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self Link `json:"self,omitempty"`
}

// SimpleTest Each test includes additional fields depending on its `type`.
// Refer `/tests/{type}` endpoint to know the set of fields returned by a given
// `type`.
type SimpleTest struct {
	Links TestLinks `json:"_links,omitempty"`
	// Indicates if alerts are enabled.
	AlertsEnabled *bool           `json:"alertsEnabled,omitempty"`
	CreatedBy     TestCreatedBy   `json:"createdBy,omitempty"`
	CreatedDate   TestCreatedDate `json:"createdDate,omitempty"`
	// A description of the test.
	Description *string      `json:"description,omitempty"`
	Enabled     Enabled      `json:"enabled,omitempty"`
	Interval    TestInterval `json:"interval,omitempty"`
	// Indicates if the test is shared with the account group.
	LiveShare *bool `json:"liveShare,omitempty"`
	// User that modified the test.
	ModifiedBy *string `json:"modifiedBy,omitempty"`
	// UTC last modification date (ISO date-time format).
	ModifiedDate *string `json:"modifiedDate,omitempty"`
	// Indicates if the test is a saved event.
	SavedEvent *bool `json:"savedEvent,omitempty"`
	// Each test is assigned an unique ID; this is used to access test information
	// and results from other endpoints.
	TestID *string `json:"testId,omitempty"`
	// The name of the test.
	TestName *string  `json:"testName,omitempty"`
	Type     TestType `json:"type,omitempty"`
}

// TestCreatedBy User that created the test.
type TestCreatedBy string

// TestCreatedDate UTC created date (ISO date-time format).
type TestCreatedDate string

// TestIds List of test IDs assigned to the agent.
type TestIds []int64

// TestLinks A list of links that can be accessed to get more information
type TestLinks struct {
	Self        TestSelfLink `json:"self,omitempty"`
	TestResults TestResults  `json:"testResults,omitempty"`
}

// TestResults Reference to the test results.
type TestResults []Link

// TestSelfLink is generated from the OpenAPI specification.
type TestSelfLink struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// UserAccountGroup is generated from the OpenAPI specification.
type UserAccountGroup struct {
	// User's UTC registration date (ISO date-time format).
	DateRegistered *string `json:"dateRegistered,omitempty"`
	// User's email address.
	Email *string `json:"email,omitempty"`
	// User's UTC last login date (ISO date-time format).
	LastLogin *string `json:"lastLogin,omitempty"`
	// User's display name.
	Name  *string `json:"name,omitempty"`
	Roles []Role  `json:"roles,omitempty"`
	// Unique ID representing the user.
	Uid *string `json:"uid,omitempty"`
}
