// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.98)

package users

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// Users handles communication with the Users methods of the
	// ThousandEyes API.
	Users struct {
		client client.Client
	}
)

// NewUsers returns a Users service bound to client.
func NewUsers(client client.Client) *Users {
	return &Users{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Users
// -----------------------------------------------------------------------------

// GetUsers list users.
// URL: GET /users
//
// Retrieves a list of users in the organization the account group ID belongs
// to.
func (s *Users) GetUsers(ctx context.Context, opts ...client.RequestOption) (*ResourceUsers, *resty.Response, error) {

	endpoint := "/users"

	var result ResourceUsers

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateUser create user.
// URL: POST /users
//
// Creates a new user.
func (s *Users) CreateUser(ctx context.Context, request *UserRequest, opts ...client.RequestOption) (*CreatedUser, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/users"

	var result CreatedUser

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetCurrentUser retrieve current user.
// URL: GET /users/current
//
// Retrieves detailed information about the current user.
func (s *Users) GetCurrentUser(ctx context.Context, opts ...client.RequestOption) (*UserDetail, *resty.Response, error) {

	endpoint := "/users/current"

	var result UserDetail

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteUser delete user.
// URL: DELETE /users/{id}
//
// Deletes a user using the user ID.
func (s *Users) DeleteUser(ctx context.Context, id string, opts ...client.RequestOption) (*resty.Response, error) {
	if id == "" {
		return nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/users/%s", id)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetUser retrieve user.
// URL: GET /users/{id}
//
// Retrieves detailed information about a user.
func (s *Users) GetUser(ctx context.Context, id string, opts ...client.RequestOption) (*UserDetail, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/users/%s", id)

	var result UserDetail

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateUser update user.
// URL: PUT /users/{id}
//
// Updates a user using the user ID.
func (s *Users) UpdateUser(ctx context.Context, id string, request *UserRequest, opts ...client.RequestOption) (*UserDetail, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/users/%s", id)

	var result UserDetail

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
