// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package panorama_connectors

// Assignments A list of assigned items.
type Assignments struct {
	Links *SelfLinks `json:"_links,omitempty"`
	Items []string   `json:"items,omitempty"`
}

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// PanoramaConnector Palo Alto Networks Panorama connector configuration.
type PanoramaConnector struct {
	Links          *SelfLinks            `json:"_links,omitempty"`
	Authentication PanoramaConnectorAuth `json:"authentication"`
	// Unique ID of the Panorama connector.
	ID *string `json:"id,omitempty"`
	// Time when the connector was last modified, in milliseconds since the Unix
	// epoch.
	LastModifiedDate *int64 `json:"lastModifiedDate,omitempty"`
	// Name of the Panorama connector.
	Name string `json:"name"`
	// URL of the Panorama instance.
	Target string `json:"target"`
	// Connector type.
	Type string `json:"type"`
}

// ResourcePanoramaConnectors Collection of Panorama connectors.
type ResourcePanoramaConnectors struct {
	Links *SelfLinks          `json:"_links,omitempty"`
	Items []PanoramaConnector `json:"items,omitempty"`
}

// PanoramaKeyGenAuthentication Authentication using credentials to generate a
// Panorama API key.
type PanoramaKeyGenAuthentication struct {
	// Time to live for the generated Panorama API key, in minutes.
	KeyTtl int64 `json:"keyTtl"`
	// Password used to generate the Panorama API key.
	Password string `json:"password"`
	Type     string `json:"type"`
	// Username used to generate the Panorama API key.
	Username string `json:"username"`
}

// PanoramaTokenAuthentication Authentication using an existing Panorama API
// key.
type PanoramaTokenAuthentication struct {
	// Panorama API key used for authentication.
	Token string `json:"token"`
	// Authentication type.
	Type string `json:"type"`
}

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self *Link `json:"self,omitempty"`
}
