// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package cloud_and_enterprise_agents

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// CloudAndEnterpriseAgents handles communication with the Cloud and Enterprise Agents methods of the
	// ThousandEyes API.
	CloudAndEnterpriseAgents struct {
		client client.Client
	}
)

// NewCloudAndEnterpriseAgents returns a Cloud and Enterprise Agents service bound to client.
func NewCloudAndEnterpriseAgents(client client.Client) *CloudAndEnterpriseAgents {
	return &CloudAndEnterpriseAgents{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Cloud and Enterprise Agents
// -----------------------------------------------------------------------------

// GetAgents list Cloud and Enterprise Agents.
// URL: GET /agents
// Optional query params: expand, agentTypes, labels, tagKeys
//
// List the Cloud and Enterprise Agents available to your account in
// ThousandEyes.
func (s *CloudAndEnterpriseAgents) GetAgents(ctx context.Context, opts ...client.RequestOption) (*CloudEnterpriseAgents, *resty.Response, error) {

	endpoint := "/agents"

	var result CloudEnterpriseAgents

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteAgent delete Enterprise Agent.
// URL: DELETE /agents/{agentId}
//
// Deletes an Enterprise Agent.
func (s *CloudAndEnterpriseAgents) DeleteAgent(ctx context.Context, agentId string, opts ...client.RequestOption) (*resty.Response, error) {
	if agentId == "" {
		return nil, fmt.Errorf("agentId is required")
	}

	endpoint := fmt.Sprintf("/agents/%s", agentId)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetAgent retrieve Cloud and Enterprise Agent.
// URL: GET /agents/{agentId}
// Optional query params: expand
//
// Returns details for an agent, including assigned tests.
func (s *CloudAndEnterpriseAgents) GetAgent(ctx context.Context, agentId string, opts ...client.RequestOption) (*AgentDetails, *resty.Response, error) {
	if agentId == "" {
		return nil, nil, fmt.Errorf("agentId is required")
	}

	endpoint := fmt.Sprintf("/agents/%s", agentId)

	var result AgentDetails

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateAgent update Enterprise Agent.
// URL: PUT /agents/{agentId}
// Optional query params: expand
//
// Updates details for an Enterprise Agent.
func (s *CloudAndEnterpriseAgents) UpdateAgent(ctx context.Context, agentId string, request *AgentRequest, opts ...client.RequestOption) (*AgentDetails, *resty.Response, error) {
	if agentId == "" {
		return nil, nil, fmt.Errorf("agentId is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/agents/%s", agentId)

	var result AgentDetails

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
