// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.101)

package tests

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// Tests handles communication with the Tests methods of the
	// ThousandEyes API.
	Tests struct {
		client client.Client
	}
)

// NewTests returns a Tests service bound to client.
func NewTests(client client.Client) *Tests {
	return &Tests{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Tests
// -----------------------------------------------------------------------------

// GetTests list configured tests.
// URL: GET /tests
//
// Returns configured tests and saved events.
func (s *Tests) GetTests(ctx context.Context, opts ...client.RequestOption) (*ResourceTests, *resty.Response, error) {

	endpoint := "/tests"

	var result ResourceTests

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetTestVersionHistory get test version history.
// URL: GET /tests/{testId}/history
// Optional query params: limit
//
// Retrieve the version history of a specific test.
func (s *Tests) GetTestVersionHistory(ctx context.Context, testId string, opts ...client.RequestOption) (*TestVersionHistoryResponse, *resty.Response, error) {
	if testId == "" {
		return nil, nil, fmt.Errorf("testId is required")
	}

	endpoint := fmt.Sprintf("/tests/%s/history", testId)

	var result TestVersionHistoryResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
