// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package dashboards

// ActiveWithin Timespan in which alerts must have been active to appear in the
// widget.
type ActiveWithin struct {
	Unit  LegacyDurationUnit `json:"unit,omitempty"`
	Value DurationValue      `json:"value,omitempty"`
}

// AgentStatusWidgetType Agent Status widget type.
type AgentStatusWidgetType string

// AgentWidgetShow is generated from the OpenAPI specification.
type AgentWidgetShow LegacyAgentWidgetShow

// AgentWidgetType is generated from the OpenAPI specification.
type AgentWidgetType LegacyAgentWidgetType

// AlertListWidgetType Alert List widget type.
type AlertListWidgetType string

// ApiAgentLocation Location of the agent.
type ApiAgentLocation struct {
	// Latitude of the agent.
	Latitude *float64 `json:"latitude,omitempty"`
	// Name of the agent location.
	LocationName *string `json:"locationName,omitempty"`
	// Longitude of the agent.
	Longitude *float64 `json:"longitude,omitempty"`
}

// ApiAgentStatusAgent Agent shown in agent status widget.
type ApiAgentStatusAgent struct {
	// Identifier of the agent.
	AgentID *string `json:"agentId,omitempty"`
	// Name of the agent
	AgentName *string              `json:"agentName,omitempty"`
	IpInfo    ApiAgentStatusIpInfo `json:"ipInfo,omitempty"`
	Location  ApiAgentLocation     `json:"location,omitempty"`
	Status    EnterpriseAgentState `json:"status,omitempty"`
}

// ApiAgentStatusIpInfo IP information of the agent.
type ApiAgentStatusIpInfo struct {
	Ipv6                   *string `json:"ipv6,omitempty"`
	OperativeSystemVersion *string `json:"operativeSystemVersion,omitempty"`
	// Private IP of the agent.
	PrivateIP *string `json:"privateIp,omitempty"`
	// Public IP of the agent.
	PublicIP *string `json:"publicIp,omitempty"`
}

// ApiAgentStatusSummary Summary of the agent status.
type ApiAgentStatusSummary struct {
	// Shows the number of agents with disabled status.
	Disabled *int `json:"disabled,omitempty"`
	// Shows the number of agents with an offline status.
	Offline *int `json:"offline,omitempty"`
	// Shows the number of agents with an online status.
	Online *int `json:"online,omitempty"`
}

// ApiAgentStatusWidget is generated from the OpenAPI specification.
type ApiAgentStatusWidget struct {
	Links      SelfLinks                `json:"_links,omitempty"`
	Agents     AgentWidgetType          `json:"agents,omitempty"`
	ApiLink    *string                  `json:"apiLink,omitempty"`
	DataSource AgentStatusDatasource    `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string       `json:"embedUrl,omitempty"`
	Filters       WidgetFilters `json:"filters,omitempty"`
	FixedTimespan ApiDuration   `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded  *bool            `json:"isEmbedded,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool           `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	Show                                 AgentWidgetShow `json:"show,omitempty"`
	// Title of the widget
	Title      *string               `json:"title,omitempty"`
	Type       AgentStatusWidgetType `json:"type"`
	VisualMode VisualMode            `json:"visualMode,omitempty"`
}

// ApiAlertListAlert Alert shown in the alert list widget.
type ApiAlertListAlert struct {
	// Set to `true` if alert is active, `false` otherwise.
	Active *bool `json:"active,omitempty"`
	// Identifier of the alert.
	AlertID *string `json:"alertId,omitempty"`
	// Name of the alert rule that this alert belongs to.
	AlertRule *string `json:"alertRule,omitempty"`
	// Name of the agent, monitor or device producing the alert.
	AlertSource *string            `json:"alertSource,omitempty"`
	AlertType   AlertListAlertType `json:"alertType,omitempty"`
	// Number of seconds the alert was active.
	DurationInSeconds *int64 `json:"durationInSeconds,omitempty"`
	// Identifier of the rule.
	RuleID *string `json:"ruleId,omitempty"`
	// UTC date when the alert was first active.
	StartTime *string `json:"startTime,omitempty"`
	// Identifier of the test.
	TestID *string `json:"testId,omitempty"`
}

// ApiAlertListAlertType is generated from the OpenAPI specification.
type ApiAlertListAlertType LegacyAlertListAlertType

// ApiAlertListWidget A widget that displays a list of alerts based on
// specified criteria, such as alert type and time frame.
type ApiAlertListWidget struct {
	Links        SelfLinks    `json:"_links,omitempty"`
	ActiveWithin ActiveWithin `json:"activeWithin,omitempty"`
	// List of alert types configured in the widget, an empty list means all alert
	// types.
	AlertTypes []ApiAlertListAlertType  `json:"alertTypes,omitempty"`
	ApiLink    *string                  `json:"apiLink,omitempty"`
	DataSource AlertListDatasource      `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string       `json:"embedUrl,omitempty"`
	Filters       WidgetFilters `json:"filters,omitempty"`
	FixedTimespan ApiDuration   `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded *bool `json:"isEmbedded,omitempty"`
	// Limit the number of alerts displayed in the widget.
	LimitTo     *int             `json:"limitTo,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	// Title of the widget
	Title      *string             `json:"title,omitempty"`
	Type       AlertListWidgetType `json:"type"`
	VisualMode VisualMode          `json:"visualMode,omitempty"`
}

// ApiBoxAndWhiskersWidget A widget that displays a box and whisker plot,
// mapping data points over time with key statistics: median, range, and
// quartiles.
type ApiBoxAndWhiskersWidget struct {
	Links      SelfLinks                `json:"_links,omitempty"`
	ApiLink    *string                  `json:"apiLink,omitempty"`
	DataSource BoxAndWhiskersDatasource `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string              `json:"embedUrl,omitempty"`
	Filters       WidgetFilters        `json:"filters,omitempty"`
	FixedTimespan ApiDuration          `json:"fixedTimespan,omitempty"`
	GroupBy       ApiAggregateProperty `json:"groupBy,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded *bool `json:"isEmbedded,omitempty"`
	// Maximum scale configured in the widget.
	MaxScale    *float64         `json:"maxScale,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Minimum scale configured in the widget.
	MinScale *float64 `json:"minScale,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	// Title of the widget
	Title      *string                    `json:"title,omitempty"`
	Type       BoxAndWhiskersWidgetType   `json:"type"`
	Unit       ApiWidgetFixedYScalePrefix `json:"unit,omitempty"`
	VisualMode VisualMode                 `json:"visualMode,omitempty"`
}

// ApiColorGridWidget The Color Grid widget displays colored cards arranged in
// rows and columns.
type ApiColorGridWidget struct {
	Links   SelfLinks            `json:"_links,omitempty"`
	ApiLink *string              `json:"apiLink,omitempty"`
	Cards   ApiAggregateProperty `json:"cards,omitempty"`
	// Number of columns: 1 or 2.
	Columns    *int                     `json:"columns,omitempty"`
	DataSource ColorGridDatasource      `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string              `json:"embedUrl,omitempty"`
	Filters       WidgetFilters        `json:"filters,omitempty"`
	FixedTimespan ApiDuration          `json:"fixedTimespan,omitempty"`
	GroupCardsBy  ApiAggregateProperty `json:"groupCardsBy,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded *bool       `json:"isEmbedded,omitempty"`
	Limit      WidgetLimit `json:"limit,omitempty"`
	// Maximum scale configured in the widget.
	MaxScale    *float64         `json:"maxScale,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Minimum scale configured in the widget.
	MinScale *float64 `json:"minScale,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool               `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	SortBy                               WidgetSortProperty  `json:"sortBy,omitempty"`
	SortDirection                        WidgetSortDirection `json:"sortDirection,omitempty"`
	SortGroupBy                          WidgetSortProperty  `json:"sortGroupBy,omitempty"`
	SortGroupDirection                   WidgetSortDirection `json:"sortGroupDirection,omitempty"`
	// Title of the widget
	Title      *string                    `json:"title,omitempty"`
	Type       ColorGridWidgetType        `json:"type"`
	Unit       ApiWidgetFixedYScalePrefix `json:"unit,omitempty"`
	VisualMode VisualMode                 `json:"visualMode,omitempty"`
}

// ApiDashboard Dashboard upon which this dashboard snapshot is based upon.
type ApiDashboard struct {
	Links DashboardLinks `json:"_links,omitempty"`
	// Identifier for the account group associated with a dashboard.
	AccountID *int64 `json:"accountId,omitempty"`
	// Identifier for the account group associated with a dashboard.
	AID *string `json:"aid,omitempty"`
	// A links array containing the self and the snapshots links.
	ApiLink []map[string]any `json:"apiLink,omitempty"`
	// Identifier for the user that created a dashboard.
	CreatedBy *int64 `json:"createdBy,omitempty"`
	// Identifier for the user that created a dashboard.
	DashboardCreatedBy *string `json:"dashboardCreatedBy,omitempty"`
	// Identifier of a dashboard.
	DashboardID *string `json:"dashboardId,omitempty"`
	// Identifier for the user that last modified a dashboard.
	DashboardModifiedBy *string `json:"dashboardModifiedBy,omitempty"`
	// UTC date/time when a dashboard was last modified (ISO date-time format).
	DashboardModifiedDate *string         `json:"dashboardModifiedDate,omitempty"`
	DefaultTimespan       DefaultTimespan `json:"defaultTimespan,omitempty"`
	// A text description of the dashboard's purpose and functionality.
	Description *string `json:"description,omitempty"`
	// Default global dashboard filter ID (obtained from `/dashboards/filters`
	// endpoint).
	GlobalFilterID *string `json:"globalFilterId,omitempty"`
	// When set to `true`, the defaultTimespan is used and overrides the widget's
	// timespan.
	GlobalOverride *bool `json:"globalOverride,omitempty"`
	// Indicates if a dashboard is built-in.
	IsBuiltIn *bool `json:"isBuiltIn,omitempty"`
	// Indicates whether this dashboard is the account group's default.
	IsDefaultForAccount *bool `json:"isDefaultForAccount,omitempty"`
	// Indicates whether this dashboard is the user's default.
	IsDefaultForUser *bool `json:"isDefaultForUser,omitempty"`
	// When set to `true`, the defaultTimespan is used and overrides the widget's
	// timespan.
	IsGlobalOverride *bool `json:"isGlobalOverride,omitempty"`
	// True if this dashboard was previously a report.
	IsMigratedReport *bool `json:"isMigratedReport,omitempty"`
	// A dashboard can be viewed by other users in the account.
	IsPrivate *bool           `json:"isPrivate,omitempty"`
	Layout    DashboardLayout `json:"layout,omitempty"`
	// True if this dashboard was previously a report.
	MigratedReport *bool `json:"migratedReport,omitempty"`
	// Identifier for the user that last modified a dashboard.
	ModifiedBy *int64 `json:"modifiedBy,omitempty"`
	// UTC date/time when a dashboard was last modified.
	ModifiedDate *string `json:"modifiedDate,omitempty"`
	// Title of a dashboard.
	Title   *string     `json:"title,omitempty"`
	Widgets []ApiWidget `json:"widgets,omitempty"`
}

// ApiDashboardAsw Alert suppression window shown in a widget.
type ApiDashboardAsw struct {
	DurationInSeconds *int64 `json:"durationInSeconds,omitempty"`
	// Identifier of the alert suppression window.
	ID *string `json:"id,omitempty"`
	// Name of the alert suppression window.
	Name        *string       `json:"name,omitempty"`
	Repeat      AswRepeat     `json:"repeat,omitempty"`
	RepeatEvery *int          `json:"repeatEvery,omitempty"`
	RepeatUnit  AswRepeatUnit `json:"repeatUnit,omitempty"`
	StartTimes  []string      `json:"startTimes,omitempty"`
	TestIds     []string      `json:"testIds,omitempty"`
}

// ApiDashboards is generated from the OpenAPI specification.
type ApiDashboards []ApiDashboard

// ApiDataPointGroup Group of data points.
type ApiDataPointGroup struct {
	// Defines the criterion used to aggregate data points under specific group
	// values.
	GroupProperty *string `json:"groupProperty,omitempty"`
	// The value of a group.
	GroupValue *string `json:"groupValue,omitempty"`
}

// ApiDuration Specifies a fixed timespan for data aggregation.
type ApiDuration struct {
	Unit  LegacyDurationUnit `json:"unit,omitempty"`
	Value DurationValue      `json:"value,omitempty"`
}

// ApiGeoMapWidget Displays data on a geographic map, highlighting information
// across different regions.
type ApiGeoMapWidget struct {
	Links      SelfLinks                `json:"_links,omitempty"`
	ApiLink    *string                  `json:"apiLink,omitempty"`
	DataSource GeoMapDatasource         `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string              `json:"embedUrl,omitempty"`
	Filters       WidgetFilters        `json:"filters,omitempty"`
	FixedTimespan ApiDuration          `json:"fixedTimespan,omitempty"`
	GroupBy       ApiAggregateProperty `json:"groupBy,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded *bool `json:"isEmbedded,omitempty"`
	// Indicates whether a separate map is displayed for each test within the
	// widget.
	IsGeoMapPerTest *bool `json:"isGeoMapPerTest,omitempty"`
	// Maximum scale configured in the widget.
	MaxScale    *float64         `json:"maxScale,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Minimum scale configured in the widget.
	MinScale *float64 `json:"minScale,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool               `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	SortBy                               WidgetSortProperty  `json:"sortBy,omitempty"`
	SortDirection                        WidgetSortDirection `json:"sortDirection,omitempty"`
	// Title of the widget
	Title      *string                    `json:"title,omitempty"`
	Type       MapWidgetType              `json:"type"`
	Unit       ApiWidgetFixedYScalePrefix `json:"unit,omitempty"`
	VisualMode VisualMode                 `json:"visualMode,omitempty"`
}

// ApiGraphletPoint A data point on a graphlet.
type ApiGraphletPoint struct {
	// Timestamp of the data point.
	X *int64 `json:"x,omitempty"`
	// Value of the data point.
	Y *float64 `json:"y,omitempty"`
}

// ApiGroupedBarchartWidget Displays grouped bars, each representing multiple
// data points. You can configure the bars to align horizontally or vertically.
type ApiGroupedBarchartWidget struct {
	Links       SelfLinks                 `json:"_links,omitempty"`
	ApiLink     *string                   `json:"apiLink,omitempty"`
	AxisGroupBy ApiAggregateProperty      `json:"axisGroupBy,omitempty"`
	DataSource  GroupedBarChartDatasource `json:"dataSource,omitempty"`
	Direction   DashboardMetricDirection  `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string              `json:"embedUrl,omitempty"`
	Filters       WidgetFilters        `json:"filters,omitempty"`
	FixedTimespan ApiDuration          `json:"fixedTimespan,omitempty"`
	GroupBy       ApiAggregateProperty `json:"groupBy,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded           *bool            `json:"isEmbedded,omitempty"`
	IsHorizontalBarChart *bool            `json:"isHorizontalBarChart,omitempty"`
	Limit                WidgetLimit      `json:"limit,omitempty"`
	Measure              ApiWidgetMeasure `json:"measure,omitempty"`
	Metric               DashboardMetric  `json:"metric,omitempty"`
	MetricGroup          MetricGroup      `json:"metricGroup,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	// Displays labels on each bar when set to `true`.
	ShowLabels    *bool               `json:"showLabels,omitempty"`
	SortBy        WidgetSortProperty  `json:"sortBy,omitempty"`
	SortDirection WidgetSortDirection `json:"sortDirection,omitempty"`
	// Title of the widget
	Title      *string                   `json:"title,omitempty"`
	Type       BarChartGroupedWidgetType `json:"type"`
	VisualMode VisualMode                `json:"visualMode,omitempty"`
}

// ApiHeatmapWidget Displays metric intensity across row and column groupings
// in a grid to help compare relative values across two dimensions.
type ApiHeatmapWidget struct {
	Links         SelfLinks                `json:"_links,omitempty"`
	ApiLink       *string                  `json:"apiLink,omitempty"`
	ColumnGroupBy ApiAggregateProperty     `json:"columnGroupBy,omitempty"`
	DataSource    HeatmapDatasource        `json:"dataSource,omitempty"`
	Direction     DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string       `json:"embedUrl,omitempty"`
	Filters       WidgetFilters `json:"filters,omitempty"`
	FixedTimespan ApiDuration   `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded  *bool                `json:"isEmbedded,omitempty"`
	Limit       WidgetLimit          `json:"limit,omitempty"`
	Measure     ApiWidgetMeasure     `json:"measure,omitempty"`
	Metric      DashboardMetric      `json:"metric,omitempty"`
	MetricGroup MetricGroup          `json:"metricGroup,omitempty"`
	RowGroupBy  ApiAggregateProperty `json:"rowGroupBy,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool               `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	SortBy                               WidgetSortProperty  `json:"sortBy,omitempty"`
	SortDirection                        WidgetSortDirection `json:"sortDirection,omitempty"`
	// Title of the widget
	Title      *string           `json:"title,omitempty"`
	Type       HeatmapWidgetType `json:"type"`
	VisualMode VisualMode        `json:"visualMode,omitempty"`
}

// ApiListWidget A widget that displays a list of items, such as events. It can
// use a time range to limit the items shown.
type ApiListWidget struct {
	Links        SelfLinks                `json:"_links,omitempty"`
	ActiveWithin ActiveWithin             `json:"activeWithin,omitempty"`
	ApiLink      *string                  `json:"apiLink,omitempty"`
	DataSource   ListDatasource           `json:"dataSource,omitempty"`
	Direction    DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string       `json:"embedUrl,omitempty"`
	Filters       WidgetFilters `json:"filters,omitempty"`
	FixedTimespan ApiDuration   `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded  *bool            `json:"isEmbedded,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool               `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	SortDirection                        WidgetSortDirection `json:"sortDirection,omitempty"`
	// Title of the widget
	Title      *string        `json:"title,omitempty"`
	Type       ListWidgetType `json:"type"`
	VisualMode VisualMode     `json:"visualMode,omitempty"`
}

// ApiMultiMetricColumn Defines a column within a table that aggregates and
// displays various metrics (Multi-Metric table).
type ApiMultiMetricColumn struct {
	Links       SelfLinks                   `json:"_links,omitempty"`
	DataSource  MultiMetricsTableDatasource `json:"dataSource,omitempty"`
	Direction   DashboardMetricDirection    `json:"direction,omitempty"`
	Filters     WidgetFilters               `json:"filters,omitempty"`
	ID          *string                     `json:"id,omitempty"`
	Measure     ApiWidgetMeasure            `json:"measure,omitempty"`
	Metric      DashboardMetric             `json:"metric,omitempty"`
	MetricGroup MetricGroup                 `json:"metricGroup,omitempty"`
}

// ApiMultiMetricColumnData The data presented within a single column of a
// Multi-Metric table.
type ApiMultiMetricColumnData struct {
	Links                   SelfLinks         `json:"_links,omitempty"`
	AlertSuppressionWindows []ApiDashboardAsw `json:"alertSuppressionWindows,omitempty"`
	BinSize                 BinSize           `json:"binSize,omitempty"`
	// Identifier of the column.
	ColumnID *string              `json:"columnId,omitempty"`
	Points   []ApiWidgetDataPoint `json:"points,omitempty"`
	Status   WidgetStatus         `json:"status,omitempty"`
}

// ApiMultiMetricTableWidget A Multi-Metric table widget with columns, each
// representing a different metric, offering a comprehensive view rather than
// restricting to a single metric.
type ApiMultiMetricTableWidget struct {
	Links   SelfLinks `json:"_links,omitempty"`
	ApiLink *string   `json:"apiLink,omitempty"`
	// Enables comparison of the current metric value with the previous value.
	CompareToPreviousValue *bool                       `json:"compareToPreviousValue,omitempty"`
	DataSource             MultiMetricsTableDatasource `json:"dataSource,omitempty"`
	Direction              DashboardMetricDirection    `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string       `json:"embedUrl,omitempty"`
	Filters       WidgetFilters `json:"filters,omitempty"`
	FixedTimespan ApiDuration   `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded         *bool                  `json:"isEmbedded,omitempty"`
	Limit              WidgetLimit            `json:"limit,omitempty"`
	Measure            ApiWidgetMeasure       `json:"measure,omitempty"`
	Metric             DashboardMetric        `json:"metric,omitempty"`
	MetricGroup        MetricGroup            `json:"metricGroup,omitempty"`
	MultiMetricColumns []ApiMultiMetricColumn `json:"multiMetricColumns,omitempty"`
	RowGroupBy         ApiAggregateProperty   `json:"rowGroupBy,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool               `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	SortBy                               WidgetSortProperty  `json:"sortBy,omitempty"`
	SortDirection                        WidgetSortDirection `json:"sortDirection,omitempty"`
	// Title of the widget
	Title      *string                    `json:"title,omitempty"`
	Type       MultiMetricTableWidgetType `json:"type"`
	VisualMode VisualMode                 `json:"visualMode,omitempty"`
}

// ApiMultiSearchFilterApiTestTableFilterKey A multi search filter key within
// the Multi-Metric table widget. The key represents the filter name, and the
// value specifies the filter value.
type ApiMultiSearchFilterApiTestTableFilterKey struct {
	Key   TestTableFilterKey `json:"key,omitempty"`
	Value *string            `json:"value,omitempty"`
}

// ApiNumbersCard An individual number card within the numbers card widget.
type ApiNumbersCard struct {
	Links                  SelfLinks             `json:"_links,omitempty"`
	CompareToPreviousValue *bool                 `json:"compareToPreviousValue,omitempty"`
	DataSource             NumbersCardDatasource `json:"dataSource,omitempty"`
	// Description of the number card.
	Description   *string                  `json:"description,omitempty"`
	Direction     DashboardMetricDirection `json:"direction,omitempty"`
	Filters       WidgetFilters            `json:"filters,omitempty"`
	FixedTimespan ApiDuration              `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Maximum scale configured in the widget.
	MaxScale    *float64         `json:"maxScale,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Minimum scale configured in the widget.
	MinScale *float64 `json:"minScale,omitempty"`
	// Excludes alert suppression windows from the widget when set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool                      `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	Unit                                 ApiWidgetFixedYScalePrefix `json:"unit,omitempty"`
}

// ApiNumbersCardData The data displayed on a numbers card.
type ApiNumbersCardData struct {
	Links                   SelfLinks         `json:"_links,omitempty"`
	AlertSuppressionWindows []ApiDashboardAsw `json:"alertSuppressionWindows,omitempty"`
	BinSize                 BinSize           `json:"binSize,omitempty"`
	// Identifier of the card.
	CardID *string `json:"cardId,omitempty"`
	// Name of the card.
	CardName *string `json:"cardName,omitempty"`
	// UTC end date of the data shown in the API output (ISO date-time format).
	EndDate *string `json:"endDate,omitempty"`
	// Number of points aggregated into the data point
	NumberOfDataPoints *int64 `json:"numberOfDataPoints,omitempty"`
	// Previous value if `compareToPreviousValue == true` in configuration.
	PreviousValue *float64 `json:"previousValue,omitempty"`
	// UTC start date of the data shown in the API output (ISO date-time format).
	StartDate *string      `json:"startDate,omitempty"`
	Status    WidgetStatus `json:"status,omitempty"`
	Timestamp Timestamp    `json:"timestamp,omitempty"`
	Value     WidgetValue  `json:"value,omitempty"`
}

// ApiNumbersCardWidget A widget composed of multiple cards, each presenting a
// singular metric, such as average packet loss, page load time, or alert
// count.
type ApiNumbersCardWidget struct {
	Links      SelfLinks                `json:"_links,omitempty"`
	ApiLink    *string                  `json:"apiLink,omitempty"`
	DataSource NumbersCardDatasource    `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string       `json:"embedUrl,omitempty"`
	Filters       WidgetFilters `json:"filters,omitempty"`
	FixedTimespan ApiDuration   `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded  *bool            `json:"isEmbedded,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	NumberCards []ApiNumbersCard `json:"numberCards,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	// Title of the widget
	Title      *string          `json:"title,omitempty"`
	Type       NumberWidgetType `json:"type"`
	VisualMode VisualMode       `json:"visualMode,omitempty"`
}

// ApiPieChartWidget Displays data as segments of a pie, with each slice
// representing a portion of the total value.
type ApiPieChartWidget struct {
	Links      SelfLinks                `json:"_links,omitempty"`
	ApiLink    *string                  `json:"apiLink,omitempty"`
	DataSource PieChartDatasource       `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string              `json:"embedUrl,omitempty"`
	Filters       WidgetFilters        `json:"filters,omitempty"`
	FixedTimespan ApiDuration          `json:"fixedTimespan,omitempty"`
	GroupBy       ApiAggregateProperty `json:"groupBy,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded  *bool            `json:"isEmbedded,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool          `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	ShowSubmetrics                       ShowSubmetrics `json:"showSubmetrics,omitempty"`
	// Title of the widget
	Title      *string            `json:"title,omitempty"`
	Type       PieChartWidgetType `json:"type"`
	VisualMode VisualMode         `json:"visualMode,omitempty"`
}

// ApiReportDataComponentLabelMap Map of group labels.
type ApiReportDataComponentLabelMap struct {
	// List of group labels.
	GroupLabels []ApiReportDataComponentLabelMapEntry `json:"groupLabels,omitempty"`
	// Defines the criterion used to aggregate data points under specific group
	// values.
	GroupProperty *string `json:"groupProperty,omitempty"`
}

// ApiReportDataComponentLabelMapEntry Represents a mapping entry of a group
// label.
type ApiReportDataComponentLabelMapEntry struct {
	// Identifier of the group.
	GroupID *string `json:"groupId,omitempty"`
	// Label of the group.
	GroupLabel *string `json:"groupLabel,omitempty"`
}

// ApiStackedAreaChartWidget Displays line plots over time, stacking quantities
// vertically to showcase cumulative data trends, similar to stacked bar
// charts. Ideal for visualizing changes in response times, error counts, and
// other metrics, revealing the progression of values across a timeline. Use
// this chart to replace stacked bar charts for temporal data analysis.
type ApiStackedAreaChartWidget struct {
	Links      SelfLinks                  `json:"_links,omitempty"`
	ApiLink    *string                    `json:"apiLink,omitempty"`
	DataSource StackedAreaChartDatasource `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection   `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string              `json:"embedUrl,omitempty"`
	Filters       WidgetFilters        `json:"filters,omitempty"`
	FixedTimespan ApiDuration          `json:"fixedTimespan,omitempty"`
	GroupBy       ApiAggregateProperty `json:"groupBy,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded *bool `json:"isEmbedded,omitempty"`
	// Maximum scale configured in the widget.
	MaxScale    *float64         `json:"maxScale,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Minimum scale configured in the widget.
	MinScale *float64 `json:"minScale,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool          `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	ShowSubmetrics                       ShowSubmetrics `json:"showSubmetrics,omitempty"`
	// Title of the widget
	Title      *string                         `json:"title,omitempty"`
	Type       TimeSeriesStackedAreaWidgetType `json:"type"`
	Unit       ApiWidgetFixedYScalePrefix      `json:"unit,omitempty"`
	VisualMode VisualMode                      `json:"visualMode,omitempty"`
}

// ApiStackedBarchartWidget is generated from the OpenAPI specification.
type ApiStackedBarchartWidget struct {
	Links       SelfLinks                 `json:"_links,omitempty"`
	ApiLink     *string                   `json:"apiLink,omitempty"`
	AxisGroupBy ApiAggregateProperty      `json:"axisGroupBy,omitempty"`
	DataSource  StackedBarChartDatasource `json:"dataSource,omitempty"`
	Direction   DashboardMetricDirection  `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string       `json:"embedUrl,omitempty"`
	Filters       WidgetFilters `json:"filters,omitempty"`
	FixedTimespan ApiDuration   `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded *bool `json:"isEmbedded,omitempty"`
	// Set to `true` to display bars horizontally in the widget.
	IsHorizontalBarChart *bool            `json:"isHorizontalBarChart,omitempty"`
	Limit                WidgetLimit      `json:"limit,omitempty"`
	Measure              ApiWidgetMeasure `json:"measure,omitempty"`
	Metric               DashboardMetric  `json:"metric,omitempty"`
	MetricGroup          MetricGroup      `json:"metricGroup,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool               `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	ShowLabels                           *bool               `json:"showLabels,omitempty"`
	SortBy                               WidgetSortProperty  `json:"sortBy,omitempty"`
	SortDirection                        WidgetSortDirection `json:"sortDirection,omitempty"`
	// Title of the widget
	Title      *string                   `json:"title,omitempty"`
	Type       BarChartStackedWidgetType `json:"type"`
	VisualMode VisualMode                `json:"visualMode,omitempty"`
}

// ApiTableWidget Organizes data in rows and columns, with options to list by
// test, geographic location, data source, or aggregated categories.
type ApiTableWidget struct {
	Links                  SelfLinks                `json:"_links,omitempty"`
	ApiLink                *string                  `json:"apiLink,omitempty"`
	ColumnGroupBy          ApiAggregateProperty     `json:"columnGroupBy,omitempty"`
	CompareToPreviousValue *bool                    `json:"compareToPreviousValue,omitempty"`
	DataSource             TableDatasource          `json:"dataSource,omitempty"`
	Direction              DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string       `json:"embedUrl,omitempty"`
	Filters       WidgetFilters `json:"filters,omitempty"`
	FixedTimespan ApiDuration   `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded  *bool                `json:"isEmbedded,omitempty"`
	Limit       WidgetLimit          `json:"limit,omitempty"`
	Measure     ApiWidgetMeasure     `json:"measure,omitempty"`
	Metric      DashboardMetric      `json:"metric,omitempty"`
	MetricGroup MetricGroup          `json:"metricGroup,omitempty"`
	RowGroupBy  ApiAggregateProperty `json:"rowGroupBy,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool               `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	SortBy                               WidgetSortProperty  `json:"sortBy,omitempty"`
	SortDirection                        WidgetSortDirection `json:"sortDirection,omitempty"`
	// Title of the widget
	Title      *string         `json:"title,omitempty"`
	Type       TableWidgetType `json:"type"`
	VisualMode VisualMode      `json:"visualMode,omitempty"`
}

// ApiTestTableData Data shown in a test table widget.
type ApiTestTableData struct {
	// Number of active alerts of the test.
	AlertCount *int64 `json:"alertCount,omitempty"`
	// List of time series points for test metrics in the last 12 hours.
	Graphlets []ApiTestTableGraphletsData `json:"graphlets,omitempty"`
	// Set to `true` if test is shared, `false` otherwise.
	IsShared *bool `json:"isShared,omitempty"`
	// Configured target of the test.
	Target *string `json:"target,omitempty"`
	// Identifier of the test.
	TestID *string `json:"testId,omitempty"`
	// Name of the test.
	TestName *string `json:"testName,omitempty"`
	// Type of the test.
	TestType *string `json:"testType,omitempty"`
}

// ApiTestTableGraphletsData Information displayed within a mini-graph
// associated with a specific test in a table.
type ApiTestTableGraphletsData struct {
	// Name of the metric.
	Metric *string            `json:"metric,omitempty"`
	Points []ApiGraphletPoint `json:"points,omitempty"`
	// Identifier of the test.
	TestID *string `json:"testId,omitempty"`
}

// ApiTestTableWidget Displays tests and statuses with options to sort and
// filter. It can be set to show only certain tests, like those with specific
// labels or failing tests.
type ApiTestTableWidget struct {
	Links      SelfLinks                `json:"_links,omitempty"`
	ApiLink    *string                  `json:"apiLink,omitempty"`
	DataSource TestTableDatasource      `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string                              `json:"embedUrl,omitempty"`
	Exclude       ApiWidgetFilterApiTestTableFilterKey `json:"exclude,omitempty"`
	Filter        ApiWidgetFilterApiTestTableFilterKey `json:"filter,omitempty"`
	Filters       WidgetFilters                        `json:"filters,omitempty"`
	FixedTimespan ApiDuration                          `json:"fixedTimespan,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded  *bool            `json:"isEmbedded,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	// Title of the widget
	Title      *string             `json:"title,omitempty"`
	Type       TestTableWidgetType `json:"type"`
	VisualMode VisualMode          `json:"visualMode,omitempty"`
}

// ApiTimeseriesWidget The Timeseries widget graphs data over time, with the
// chosen metric displayed on the vertical axis. vertical axis
type ApiTimeseriesWidget struct {
	Links      SelfLinks                `json:"_links,omitempty"`
	ApiLink    *string                  `json:"apiLink,omitempty"`
	DataSource TimeseriesDatasource     `json:"dataSource,omitempty"`
	Direction  DashboardMetricDirection `json:"direction,omitempty"`
	// When `isEmbedded` is set to `true`, an `embedUrl` is provided.
	EmbedURL      *string              `json:"embedUrl,omitempty"`
	Filters       WidgetFilters        `json:"filters,omitempty"`
	FixedTimespan ApiDuration          `json:"fixedTimespan,omitempty"`
	GroupBy       ApiAggregateProperty `json:"groupBy,omitempty"`
	// Identifier of the widget.
	ID *string `json:"id,omitempty"`
	// Set to `true` if widget is marked as embedded; otherwise, set to `false`.
	IsEmbedded *bool `json:"isEmbedded,omitempty"`
	// Displays a separate chart for each line if set to `true`.
	IsTimeseriesOneChartPerLine *bool `json:"isTimeseriesOneChartPerLine,omitempty"`
	// Maximum scale configured in the widget.
	MaxScale    *float64         `json:"maxScale,omitempty"`
	Measure     ApiWidgetMeasure `json:"measure,omitempty"`
	Metric      DashboardMetric  `json:"metric,omitempty"`
	MetricGroup MetricGroup      `json:"metricGroup,omitempty"`
	// Minimum scale configured in the widget.
	MinScale *float64 `json:"minScale,omitempty"`
	// Excludes alert suppression window data if set to `true`.
	ShouldExcludeAlertSuppressionWindows *bool `json:"shouldExcludeAlertSuppressionWindows,omitempty"`
	// Displays the overall baseline if set to `true`.
	ShowTimeseriesOverallBaseline *bool `json:"showTimeseriesOverallBaseline,omitempty"`
	// Title of the widget
	Title      *string                    `json:"title,omitempty"`
	Type       TimeSeriesLineWidgetType   `json:"type"`
	Unit       ApiWidgetFixedYScalePrefix `json:"unit,omitempty"`
	VisualMode VisualMode                 `json:"visualMode,omitempty"`
}

// ApiWidgetDataPoint Data point of a widget.
type ApiWidgetDataPoint struct {
	Groups []ApiDataPointGroup `json:"groups,omitempty"`
	// Number of test data points aggregated into the widget data point.
	NumberOfDataPoints *int64      `json:"numberOfDataPoints,omitempty"`
	Timestamp          Timestamp   `json:"timestamp,omitempty"`
	Value              WidgetValue `json:"value,omitempty"`
}

// ApiWidgetDataResponse is generated from the OpenAPI specification.
type ApiWidgetDataResponse struct {
	Links       PaginationLinks                  `json:"_links,omitempty"`
	BinSize     BinSize                          `json:"binSize,omitempty"`
	Data        ApiWidgetsDataV2                 `json:"data,omitempty"`
	EndDate     EndDate                          `json:"endDate,omitempty"`
	GroupLabels []ApiReportDataComponentLabelMap `json:"groupLabels,omitempty"`
	StartDate   StartDate                        `json:"startDate,omitempty"`
}

// ApiWidgetFilterApiTestTableFilterKey is generated from the OpenAPI specification.
type ApiWidgetFilterApiTestTableFilterKey struct {
	Filters []ApiMultiSearchFilterApiTestTableFilterKey `json:"filters,omitempty"`
	Type    TestTableFilterType                         `json:"type,omitempty"`
}

// ApiWidgetMeasure Determines how to aggregate the the metric.
type ApiWidgetMeasure struct {
	// The percentile value to use when `type == NTH_PERCENTILE`.
	PercentileValue *float64          `json:"percentileValue,omitempty"`
	Type            WidgetMeasureType `json:"type,omitempty"`
}

// ApiWidgetsDataV2 Data of a widget.
type ApiWidgetsDataV2 struct {
	// Total number of currently active alerts.
	ActiveAlerts            *int64                     `json:"activeAlerts,omitempty"`
	Agents                  []ApiAgentStatusAgent      `json:"agents,omitempty"`
	AlertSuppressionWindows []ApiDashboardAsw          `json:"alertSuppressionWindows,omitempty"`
	Alerts                  []ApiAlertListAlert        `json:"alerts,omitempty"`
	Cards                   []ApiNumbersCardData       `json:"cards,omitempty"`
	Columns                 []ApiMultiMetricColumnData `json:"columns,omitempty"`
	Points                  []ApiWidgetDataPoint       `json:"points,omitempty"`
	// Epoch time (seconds) indicating the start time of the round.
	StartRound *int64                `json:"startRound,omitempty"`
	Status     WidgetStatus          `json:"status,omitempty"`
	Summary    ApiAgentStatusSummary `json:"summary,omitempty"`
	Tests      []ApiTestTableData    `json:"tests,omitempty"`
	// Total number of active alerts within configured timespan.
	TotalAlerts *int64 `json:"totalAlerts,omitempty"`
}

// BarChartGroupedWidgetType Bar Chart: Grouped widget type.
type BarChartGroupedWidgetType string

// BarChartStackedWidgetType Bar Chart: Stacked widget type.
type BarChartStackedWidgetType string

// BinSize Duration of each bin.
type BinSize int64

// BoxAndWhiskersWidgetType Box and Whiskers widget type.
type BoxAndWhiskersWidgetType string

// ColorGridWidgetType Color Grid widget type.
type ColorGridWidgetType string

// Dashboard Dashboard upon which this dashboard snapshot is based upon.
type Dashboard struct {
	Links DashboardLinks `json:"_links,omitempty"`
	// Identifier for the account group associated with a dashboard.
	AID *string `json:"aid,omitempty"`
	// Identifier for the user that created a dashboard.
	CreatedBy *string `json:"createdBy,omitempty"`
	// Identifier of a dashboard.
	DashboardID     *string         `json:"dashboardId,omitempty"`
	DefaultTimespan DefaultTimespan `json:"defaultTimespan,omitempty"`
	// A text description of the dashboard's purpose and functionality.
	Description *string `json:"description,omitempty"`
	// Default global dashboard filter ID (obtained from `/dashboards/filters`
	// endpoint).
	GlobalFilterID *string `json:"globalFilterId,omitempty"`
	// Indicates if a dashboard is built-in.
	IsBuiltIn *bool `json:"isBuiltIn,omitempty"`
	// Indicates whether this dashboard is the account group's default.
	IsDefaultForAccount *bool `json:"isDefaultForAccount,omitempty"`
	// Indicates whether this dashboard is the user's default.
	IsDefaultForUser *bool `json:"isDefaultForUser,omitempty"`
	// When set to `true`, the defaultTimespan is used and overrides the widget's
	// timespan.
	IsGlobalOverride *bool `json:"isGlobalOverride,omitempty"`
	// True if this dashboard was previously a report.
	IsMigratedReport *bool `json:"isMigratedReport,omitempty"`
	// A dashboard can be viewed by other users in the account.
	IsPrivate *bool           `json:"isPrivate,omitempty"`
	Layout    DashboardLayout `json:"layout,omitempty"`
	// Identifier for the user that last modified a dashboard.
	ModifiedBy *string `json:"modifiedBy,omitempty"`
	// UTC date/time when a dashboard was last modified (ISO date-time format).
	ModifiedDate *string `json:"modifiedDate,omitempty"`
	// Title of a dashboard.
	Title   *string     `json:"title,omitempty"`
	Widgets []ApiWidget `json:"widgets,omitempty"`
}

// DashboardLayout Dashboard layout configuration for arranging widgets.
type DashboardLayout struct {
	Details DashboardLayoutDetails `json:"details,omitempty"`
	// Unique identifier for the layout.
	LayoutID *string             `json:"layoutId,omitempty"`
	Type     DashboardLayoutType `json:"type"`
}

// DashboardLayoutDetails Layout details including widget positioning.
type DashboardLayoutDetails struct {
	// List of widget positions within the layout.
	WidgetPositioning []WidgetPosition `json:"widgetPositioning,omitempty"`
}

// DashboardLinks A links object containing the self and the snapshots links.
type DashboardLinks struct {
	Self      Link `json:"self,omitempty"`
	Snapshots Link `json:"snapshots,omitempty"`
}

// DefaultTimespan is generated from the OpenAPI specification.
type DefaultTimespan struct {
	// Relative timespan in seconds.
	Duration *int64 `json:"duration,omitempty"`
	// UTC end date of the timespan range (ISO date-time format).
	End *string `json:"end,omitempty"`
	// UTC start date of the timespan range (ISO date-time format).
	Start *string `json:"start,omitempty"`
	// Relative timespan in seconds.
	TimespanDuration *int64 `json:"timespanDuration,omitempty"`
	// UTC end date of the timespan range.
	TimespanEnd *string `json:"timespanEnd,omitempty"`
	// UTC start date of the timespan range.
	TimespanStart *string `json:"timespanStart,omitempty"`
}

// DurationValue Timespan value.
type DurationValue int

// EndDate (Optional) When passing `window` or `endDate` parameter, the client
// will also receive the `endDate` field indicating the UTC end date of the
// data's time range being retrieved (ISO date-time format).
type EndDate string

// HeatmapWidgetType Heatmap widget type.
type HeatmapWidgetType string

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// ListWidgetType List widget type. Currently supports only `List`.
type ListWidgetType string

// MapWidgetType Map widget type.
type MapWidgetType string

// MultiMetricTableWidgetType Multi Metric Table widget type.
type MultiMetricTableWidgetType string

// NumberWidgetType Number widget type.
type NumberWidgetType string

// PaginationLinks A links object containing pagination related link(s).
type PaginationLinks struct {
	Next     Link `json:"next,omitempty"`
	Previous Link `json:"previous,omitempty"`
	Self     Link `json:"self,omitempty"`
}

// PieChartWidgetType Pie Chart widget type
type PieChartWidgetType string

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self Link `json:"self,omitempty"`
}

// ShowSubmetrics Controls how metrics with submetric components are displayed.
// If `true` (default), the widget displays one chart per group. If `false`,
// the widget displays all submetrics in a single chart. For metrics without
// submetric components, this field is ignored and returned as `null`.
type ShowSubmetrics bool

// StartDate (Optional) When passing `window` or `startDate` parameter, the
// client will also receive the `startDate` field indicating the UTC start date
// of the data's time range being retrieved (ISO date-time format).
type StartDate string

// TableWidgetType Table widget type.
type TableWidgetType string

// TestTableWidgetType Test Table widget type,
type TestTableWidgetType string

// TimeSeriesLineWidgetType Time Series: Line widget type.
type TimeSeriesLineWidgetType string

// TimeSeriesStackedAreaWidgetType Time Series: Stacked Area widget type
type TimeSeriesStackedAreaWidgetType string

// Timestamp Timestamp of the aggregated data point.
type Timestamp int64

// WidgetFilters (Optional) Specifies the filters applied to the widget. When
// present, the `filters` property displays. Each filter object has two
// properties: `filterProperty` and `filterValue`. The `filterProperty` can be
// values like `AGENT`, `ENDPOINT_MACHINE_ID`, `TEST`, `MONITOR`, etc. The
// `filterValue` represents an identifier array of the selected property.
type WidgetFilters map[string][]any

// WidgetLimit Limit configured in the widget.
type WidgetLimit int

// WidgetPosition Position and size of a widget in the layout grid.
type WidgetPosition struct {
	// Height in grid units.
	H int `json:"h"`
	// Identifier of the widget this position applies to.
	ID *string `json:"id,omitempty"`
	// Width in grid units.
	W int `json:"w"`
	// Horizontal position.
	X int `json:"x"`
	// Vertical position.
	Y int `json:"y"`
}

// WidgetSortDirection is generated from the OpenAPI specification.
type WidgetSortDirection LegacyWidgetSortDirection

// WidgetSortProperty is generated from the OpenAPI specification.
type WidgetSortProperty LegacyWidgetSortProperty

// WidgetStatus Message for not fully configured card or no data.
type WidgetStatus string

// WidgetValue Aggregated value.
type WidgetValue float64
