// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.98)

package dashboards

import (
	"encoding/json"
	"fmt"
)

// ApiWidget is a discriminated union from the OpenAPI specification. The type
// property selects which variant is populated.
//
// Build one with a NewApiWidgetFrom… constructor, which sets the discriminator
// and the variant together. Setting them by hand risks disagreement, which
// MarshalJSON reports rather than silently dropping.
type ApiWidget struct {
	// Type names which variant below is populated.
	Type ApiWidgetType `json:"type"`

	// AgentStatus is set when type is "Agent Status".
	AgentStatus *ApiAgentStatusWidget `json:"-"`
	// AlertList is set when type is "Alert List".
	AlertList *ApiAlertListWidget `json:"-"`
	// BarChartGrouped is set when type is "Bar Chart: Grouped".
	BarChartGrouped *ApiGroupedBarchartWidget `json:"-"`
	// BarChartStacked is set when type is "Bar Chart: Stacked".
	BarChartStacked *ApiStackedBarchartWidget `json:"-"`
	// BoxAndWhiskers is set when type is "Box and Whiskers".
	BoxAndWhiskers *ApiBoxAndWhiskersWidget `json:"-"`
	// ColorGrid is set when type is "Color Grid".
	ColorGrid *ApiColorGridWidget `json:"-"`
	// Heatmap is set when type is "Heatmap".
	Heatmap *ApiHeatmapWidget `json:"-"`
	// List is set when type is "List".
	List *ApiListWidget `json:"-"`
	// Map is set when type is "Map".
	Map *ApiGeoMapWidget `json:"-"`
	// MultiMetricTable is set when type is "Multi Metric Table".
	MultiMetricTable *ApiMultiMetricTableWidget `json:"-"`
	// Number is set when type is "Number".
	Number *ApiNumbersCardWidget `json:"-"`
	// PieChart is set when type is "Pie Chart".
	PieChart *ApiPieChartWidget `json:"-"`
	// Table is set when type is "Table".
	Table *ApiTableWidget `json:"-"`
	// TestTable is set when type is "Test Table".
	TestTable *ApiTestTableWidget `json:"-"`
	// TimeSeriesLine is set when type is "Time Series: Line".
	TimeSeriesLine *ApiTimeseriesWidget `json:"-"`
	// TimeSeriesStackedArea is set when type is "Time Series: Stacked Area".
	TimeSeriesStackedArea *ApiStackedAreaChartWidget `json:"-"`

	// Raw is the payload as received. It is always populated, and is the only
	// way to reach a variant added to the API after this code was generated.
	Raw json.RawMessage `json:"-"`
}

// NewApiWidgetFromAgentStatus returns a ApiWidget holding v.
func NewApiWidgetFromAgentStatus(v ApiAgentStatusWidget) ApiWidget {
	return ApiWidget{
		Type:        ApiWidgetTypeAgentStatus,
		AgentStatus: &v,
	}
}

// IsAgentStatus reports whether the discriminator selects the
// "Agent Status" variant.
func (u ApiWidget) IsAgentStatus() bool {
	return u.Type == ApiWidgetTypeAgentStatus
}

// GetAgentStatus returns the "Agent Status" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetAgentStatus() (*ApiAgentStatusWidget, bool) {
	if !u.IsAgentStatus() || u.AgentStatus == nil {
		return nil, false
	}
	return u.AgentStatus, true
}

// NewApiWidgetFromAlertList returns a ApiWidget holding v.
func NewApiWidgetFromAlertList(v ApiAlertListWidget) ApiWidget {
	return ApiWidget{
		Type:      ApiWidgetTypeAlertList,
		AlertList: &v,
	}
}

// IsAlertList reports whether the discriminator selects the
// "Alert List" variant.
func (u ApiWidget) IsAlertList() bool {
	return u.Type == ApiWidgetTypeAlertList
}

// GetAlertList returns the "Alert List" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetAlertList() (*ApiAlertListWidget, bool) {
	if !u.IsAlertList() || u.AlertList == nil {
		return nil, false
	}
	return u.AlertList, true
}

// NewApiWidgetFromBarChartGrouped returns a ApiWidget holding v.
func NewApiWidgetFromBarChartGrouped(v ApiGroupedBarchartWidget) ApiWidget {
	return ApiWidget{
		Type:            ApiWidgetTypeBarChartGrouped,
		BarChartGrouped: &v,
	}
}

// IsBarChartGrouped reports whether the discriminator selects the
// "Bar Chart: Grouped" variant.
func (u ApiWidget) IsBarChartGrouped() bool {
	return u.Type == ApiWidgetTypeBarChartGrouped
}

// GetBarChartGrouped returns the "Bar Chart: Grouped" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetBarChartGrouped() (*ApiGroupedBarchartWidget, bool) {
	if !u.IsBarChartGrouped() || u.BarChartGrouped == nil {
		return nil, false
	}
	return u.BarChartGrouped, true
}

// NewApiWidgetFromBarChartStacked returns a ApiWidget holding v.
func NewApiWidgetFromBarChartStacked(v ApiStackedBarchartWidget) ApiWidget {
	return ApiWidget{
		Type:            ApiWidgetTypeBarChartStacked,
		BarChartStacked: &v,
	}
}

// IsBarChartStacked reports whether the discriminator selects the
// "Bar Chart: Stacked" variant.
func (u ApiWidget) IsBarChartStacked() bool {
	return u.Type == ApiWidgetTypeBarChartStacked
}

// GetBarChartStacked returns the "Bar Chart: Stacked" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetBarChartStacked() (*ApiStackedBarchartWidget, bool) {
	if !u.IsBarChartStacked() || u.BarChartStacked == nil {
		return nil, false
	}
	return u.BarChartStacked, true
}

// NewApiWidgetFromBoxAndWhiskers returns a ApiWidget holding v.
func NewApiWidgetFromBoxAndWhiskers(v ApiBoxAndWhiskersWidget) ApiWidget {
	return ApiWidget{
		Type:           ApiWidgetTypeBoxAndWhiskers,
		BoxAndWhiskers: &v,
	}
}

// IsBoxAndWhiskers reports whether the discriminator selects the
// "Box and Whiskers" variant.
func (u ApiWidget) IsBoxAndWhiskers() bool {
	return u.Type == ApiWidgetTypeBoxAndWhiskers
}

// GetBoxAndWhiskers returns the "Box and Whiskers" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetBoxAndWhiskers() (*ApiBoxAndWhiskersWidget, bool) {
	if !u.IsBoxAndWhiskers() || u.BoxAndWhiskers == nil {
		return nil, false
	}
	return u.BoxAndWhiskers, true
}

// NewApiWidgetFromColorGrid returns a ApiWidget holding v.
func NewApiWidgetFromColorGrid(v ApiColorGridWidget) ApiWidget {
	return ApiWidget{
		Type:      ApiWidgetTypeColorGrid,
		ColorGrid: &v,
	}
}

// IsColorGrid reports whether the discriminator selects the
// "Color Grid" variant.
func (u ApiWidget) IsColorGrid() bool {
	return u.Type == ApiWidgetTypeColorGrid
}

// GetColorGrid returns the "Color Grid" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetColorGrid() (*ApiColorGridWidget, bool) {
	if !u.IsColorGrid() || u.ColorGrid == nil {
		return nil, false
	}
	return u.ColorGrid, true
}

// NewApiWidgetFromHeatmap returns a ApiWidget holding v.
func NewApiWidgetFromHeatmap(v ApiHeatmapWidget) ApiWidget {
	return ApiWidget{
		Type:    ApiWidgetTypeHeatmap,
		Heatmap: &v,
	}
}

// IsHeatmap reports whether the discriminator selects the
// "Heatmap" variant.
func (u ApiWidget) IsHeatmap() bool {
	return u.Type == ApiWidgetTypeHeatmap
}

// GetHeatmap returns the "Heatmap" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetHeatmap() (*ApiHeatmapWidget, bool) {
	if !u.IsHeatmap() || u.Heatmap == nil {
		return nil, false
	}
	return u.Heatmap, true
}

// NewApiWidgetFromList returns a ApiWidget holding v.
func NewApiWidgetFromList(v ApiListWidget) ApiWidget {
	return ApiWidget{
		Type: ApiWidgetTypeList,
		List: &v,
	}
}

// IsList reports whether the discriminator selects the
// "List" variant.
func (u ApiWidget) IsList() bool {
	return u.Type == ApiWidgetTypeList
}

// GetList returns the "List" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetList() (*ApiListWidget, bool) {
	if !u.IsList() || u.List == nil {
		return nil, false
	}
	return u.List, true
}

// NewApiWidgetFromMap returns a ApiWidget holding v.
func NewApiWidgetFromMap(v ApiGeoMapWidget) ApiWidget {
	return ApiWidget{
		Type: ApiWidgetTypeMap,
		Map:  &v,
	}
}

// IsMap reports whether the discriminator selects the
// "Map" variant.
func (u ApiWidget) IsMap() bool {
	return u.Type == ApiWidgetTypeMap
}

// GetMap returns the "Map" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetMap() (*ApiGeoMapWidget, bool) {
	if !u.IsMap() || u.Map == nil {
		return nil, false
	}
	return u.Map, true
}

// NewApiWidgetFromMultiMetricTable returns a ApiWidget holding v.
func NewApiWidgetFromMultiMetricTable(v ApiMultiMetricTableWidget) ApiWidget {
	return ApiWidget{
		Type:             ApiWidgetTypeMultiMetricTable,
		MultiMetricTable: &v,
	}
}

// IsMultiMetricTable reports whether the discriminator selects the
// "Multi Metric Table" variant.
func (u ApiWidget) IsMultiMetricTable() bool {
	return u.Type == ApiWidgetTypeMultiMetricTable
}

// GetMultiMetricTable returns the "Multi Metric Table" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetMultiMetricTable() (*ApiMultiMetricTableWidget, bool) {
	if !u.IsMultiMetricTable() || u.MultiMetricTable == nil {
		return nil, false
	}
	return u.MultiMetricTable, true
}

// NewApiWidgetFromNumber returns a ApiWidget holding v.
func NewApiWidgetFromNumber(v ApiNumbersCardWidget) ApiWidget {
	return ApiWidget{
		Type:   ApiWidgetTypeNumber,
		Number: &v,
	}
}

// IsNumber reports whether the discriminator selects the
// "Number" variant.
func (u ApiWidget) IsNumber() bool {
	return u.Type == ApiWidgetTypeNumber
}

// GetNumber returns the "Number" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetNumber() (*ApiNumbersCardWidget, bool) {
	if !u.IsNumber() || u.Number == nil {
		return nil, false
	}
	return u.Number, true
}

// NewApiWidgetFromPieChart returns a ApiWidget holding v.
func NewApiWidgetFromPieChart(v ApiPieChartWidget) ApiWidget {
	return ApiWidget{
		Type:     ApiWidgetTypePieChart,
		PieChart: &v,
	}
}

// IsPieChart reports whether the discriminator selects the
// "Pie Chart" variant.
func (u ApiWidget) IsPieChart() bool {
	return u.Type == ApiWidgetTypePieChart
}

// GetPieChart returns the "Pie Chart" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetPieChart() (*ApiPieChartWidget, bool) {
	if !u.IsPieChart() || u.PieChart == nil {
		return nil, false
	}
	return u.PieChart, true
}

// NewApiWidgetFromTable returns a ApiWidget holding v.
func NewApiWidgetFromTable(v ApiTableWidget) ApiWidget {
	return ApiWidget{
		Type:  ApiWidgetTypeTable,
		Table: &v,
	}
}

// IsTable reports whether the discriminator selects the
// "Table" variant.
func (u ApiWidget) IsTable() bool {
	return u.Type == ApiWidgetTypeTable
}

// GetTable returns the "Table" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetTable() (*ApiTableWidget, bool) {
	if !u.IsTable() || u.Table == nil {
		return nil, false
	}
	return u.Table, true
}

// NewApiWidgetFromTestTable returns a ApiWidget holding v.
func NewApiWidgetFromTestTable(v ApiTestTableWidget) ApiWidget {
	return ApiWidget{
		Type:      ApiWidgetTypeTestTable,
		TestTable: &v,
	}
}

// IsTestTable reports whether the discriminator selects the
// "Test Table" variant.
func (u ApiWidget) IsTestTable() bool {
	return u.Type == ApiWidgetTypeTestTable
}

// GetTestTable returns the "Test Table" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetTestTable() (*ApiTestTableWidget, bool) {
	if !u.IsTestTable() || u.TestTable == nil {
		return nil, false
	}
	return u.TestTable, true
}

// NewApiWidgetFromTimeSeriesLine returns a ApiWidget holding v.
func NewApiWidgetFromTimeSeriesLine(v ApiTimeseriesWidget) ApiWidget {
	return ApiWidget{
		Type:           ApiWidgetTypeTimeSeriesLine,
		TimeSeriesLine: &v,
	}
}

// IsTimeSeriesLine reports whether the discriminator selects the
// "Time Series: Line" variant.
func (u ApiWidget) IsTimeSeriesLine() bool {
	return u.Type == ApiWidgetTypeTimeSeriesLine
}

// GetTimeSeriesLine returns the "Time Series: Line" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetTimeSeriesLine() (*ApiTimeseriesWidget, bool) {
	if !u.IsTimeSeriesLine() || u.TimeSeriesLine == nil {
		return nil, false
	}
	return u.TimeSeriesLine, true
}

// NewApiWidgetFromTimeSeriesStackedArea returns a ApiWidget holding v.
func NewApiWidgetFromTimeSeriesStackedArea(v ApiStackedAreaChartWidget) ApiWidget {
	return ApiWidget{
		Type:                  ApiWidgetTypeTimeSeriesStackedArea,
		TimeSeriesStackedArea: &v,
	}
}

// IsTimeSeriesStackedArea reports whether the discriminator selects the
// "Time Series: Stacked Area" variant.
func (u ApiWidget) IsTimeSeriesStackedArea() bool {
	return u.Type == ApiWidgetTypeTimeSeriesStackedArea
}

// GetTimeSeriesStackedArea returns the "Time Series: Stacked Area" variant and whether it
// is populated. A false result with a matching discriminator means the payload
// did not decode into this variant.
func (u ApiWidget) GetTimeSeriesStackedArea() (*ApiStackedAreaChartWidget, bool) {
	if !u.IsTimeSeriesStackedArea() || u.TimeSeriesStackedArea == nil {
		return nil, false
	}
	return u.TimeSeriesStackedArea, true
}

// UnmarshalJSON decodes the variant selected by type.
//
// An unrecognised discriminator is not an error. The API adds variants without
// a major version change, and failing the whole response because one field is
// new would be worse than leaving that field unpopulated; Raw still holds it.
func (u *ApiWidget) UnmarshalJSON(data []byte) error {
	u.Raw = append(u.Raw[:0], data...)

	var tag struct {
		Value ApiWidgetType `json:"type"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return fmt.Errorf("reading ApiWidget discriminator: %w", err)
	}
	u.Type = tag.Value

	switch tag.Value {
	case ApiWidgetTypeAgentStatus:
		var v ApiAgentStatusWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.AgentStatus = &v
	case ApiWidgetTypeAlertList:
		var v ApiAlertListWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.AlertList = &v
	case ApiWidgetTypeBarChartGrouped:
		var v ApiGroupedBarchartWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.BarChartGrouped = &v
	case ApiWidgetTypeBarChartStacked:
		var v ApiStackedBarchartWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.BarChartStacked = &v
	case ApiWidgetTypeBoxAndWhiskers:
		var v ApiBoxAndWhiskersWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.BoxAndWhiskers = &v
	case ApiWidgetTypeColorGrid:
		var v ApiColorGridWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.ColorGrid = &v
	case ApiWidgetTypeHeatmap:
		var v ApiHeatmapWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.Heatmap = &v
	case ApiWidgetTypeList:
		var v ApiListWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.List = &v
	case ApiWidgetTypeMap:
		var v ApiGeoMapWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.Map = &v
	case ApiWidgetTypeMultiMetricTable:
		var v ApiMultiMetricTableWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.MultiMetricTable = &v
	case ApiWidgetTypeNumber:
		var v ApiNumbersCardWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.Number = &v
	case ApiWidgetTypePieChart:
		var v ApiPieChartWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.PieChart = &v
	case ApiWidgetTypeTable:
		var v ApiTableWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.Table = &v
	case ApiWidgetTypeTestTable:
		var v ApiTestTableWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.TestTable = &v
	case ApiWidgetTypeTimeSeriesLine:
		var v ApiTimeseriesWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.TimeSeriesLine = &v
	case ApiWidgetTypeTimeSeriesStackedArea:
		var v ApiStackedAreaChartWidget
		if err := json.Unmarshal(data, &v); err != nil {
			return fmt.Errorf("decoding ApiWidget variant %q: %w", tag.Value, err)
		}
		u.TimeSeriesStackedArea = &v
	}

	return nil
}

// MarshalJSON encodes the variant the discriminator selects.
//
// A discriminator naming a variant that is not populated is an error rather
// than a silent fallback: emitting Raw or null there would send the server
// something the caller did not ask for.
func (u ApiWidget) MarshalJSON() ([]byte, error) {
	switch u.Type {
	case ApiWidgetTypeAgentStatus:
		if u.AgentStatus == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but AgentStatus is not set",
				u.Type)
		}
		return marshalVariant(u.AgentStatus, "type", string(u.Type))
	case ApiWidgetTypeAlertList:
		if u.AlertList == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but AlertList is not set",
				u.Type)
		}
		return marshalVariant(u.AlertList, "type", string(u.Type))
	case ApiWidgetTypeBarChartGrouped:
		if u.BarChartGrouped == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but BarChartGrouped is not set",
				u.Type)
		}
		return marshalVariant(u.BarChartGrouped, "type", string(u.Type))
	case ApiWidgetTypeBarChartStacked:
		if u.BarChartStacked == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but BarChartStacked is not set",
				u.Type)
		}
		return marshalVariant(u.BarChartStacked, "type", string(u.Type))
	case ApiWidgetTypeBoxAndWhiskers:
		if u.BoxAndWhiskers == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but BoxAndWhiskers is not set",
				u.Type)
		}
		return marshalVariant(u.BoxAndWhiskers, "type", string(u.Type))
	case ApiWidgetTypeColorGrid:
		if u.ColorGrid == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but ColorGrid is not set",
				u.Type)
		}
		return marshalVariant(u.ColorGrid, "type", string(u.Type))
	case ApiWidgetTypeHeatmap:
		if u.Heatmap == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but Heatmap is not set",
				u.Type)
		}
		return marshalVariant(u.Heatmap, "type", string(u.Type))
	case ApiWidgetTypeList:
		if u.List == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but List is not set",
				u.Type)
		}
		return marshalVariant(u.List, "type", string(u.Type))
	case ApiWidgetTypeMap:
		if u.Map == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but Map is not set",
				u.Type)
		}
		return marshalVariant(u.Map, "type", string(u.Type))
	case ApiWidgetTypeMultiMetricTable:
		if u.MultiMetricTable == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but MultiMetricTable is not set",
				u.Type)
		}
		return marshalVariant(u.MultiMetricTable, "type", string(u.Type))
	case ApiWidgetTypeNumber:
		if u.Number == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but Number is not set",
				u.Type)
		}
		return marshalVariant(u.Number, "type", string(u.Type))
	case ApiWidgetTypePieChart:
		if u.PieChart == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but PieChart is not set",
				u.Type)
		}
		return marshalVariant(u.PieChart, "type", string(u.Type))
	case ApiWidgetTypeTable:
		if u.Table == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but Table is not set",
				u.Type)
		}
		return marshalVariant(u.Table, "type", string(u.Type))
	case ApiWidgetTypeTestTable:
		if u.TestTable == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but TestTable is not set",
				u.Type)
		}
		return marshalVariant(u.TestTable, "type", string(u.Type))
	case ApiWidgetTypeTimeSeriesLine:
		if u.TimeSeriesLine == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but TimeSeriesLine is not set",
				u.Type)
		}
		return marshalVariant(u.TimeSeriesLine, "type", string(u.Type))
	case ApiWidgetTypeTimeSeriesStackedArea:
		if u.TimeSeriesStackedArea == nil {
			return nil, fmt.Errorf(
				"ApiWidget: type is %q but TimeSeriesStackedArea is not set",
				u.Type)
		}
		return marshalVariant(u.TimeSeriesStackedArea, "type", string(u.Type))
	}

	// The discriminator is one this SDK does not know. Round-trip what arrived
	// rather than rejecting a payload the server considers valid.
	if len(u.Raw) > 0 {
		return u.Raw, nil
	}
	if u.Type == "" {
		return []byte("null"), nil
	}
	return nil, fmt.Errorf(
		"ApiWidget: unknown type %q and no raw payload to fall back on",
		u.Type)
}

// marshalVariant encodes a union variant with its discriminator reinstated,
// since the variant types do not carry the tag themselves.
func marshalVariant(variant any, property, value string) ([]byte, error) {
	encoded, err := json.Marshal(variant)
	if err != nil {
		return nil, fmt.Errorf("encoding variant: %w", err)
	}

	fields := map[string]json.RawMessage{}
	if err := json.Unmarshal(encoded, &fields); err != nil {
		// Not an object, so there is nowhere to reinstate the discriminator.
		return encoded, nil
	}

	tag, err := json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("encoding discriminator: %w", err)
	}
	fields[property] = tag

	return json.Marshal(fields)
}
