// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package http_server_instant_tests

import "fmt"

// CloudEnterpriseAgentType is an enumeration from the OpenAPI specification.
// Type of the agent. It is open: values outside the enumeration decode and
// compare as their underlying string.
type CloudEnterpriseAgentType string

// CloudEnterpriseAgentType values.
const (
	CloudEnterpriseAgentTypeCloud             CloudEnterpriseAgentType = "cloud"
	CloudEnterpriseAgentTypeEnterpriseCluster CloudEnterpriseAgentType = "enterprise-cluster"
	CloudEnterpriseAgentTypeEnterprise        CloudEnterpriseAgentType = "enterprise"
)

// String returns the value as the API spells it, or "CloudEnterpriseAgentType(v)" for
// values outside the enumeration.
func (v CloudEnterpriseAgentType) String() string {
	switch v {
	case CloudEnterpriseAgentTypeCloud:
		return "cloud"
	case CloudEnterpriseAgentTypeEnterpriseCluster:
		return "enterprise-cluster"
	case CloudEnterpriseAgentTypeEnterprise:
		return "enterprise"
	}
	return fmt.Sprintf("CloudEnterpriseAgentType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v CloudEnterpriseAgentType) IsKnown() bool {
	switch v {
	case CloudEnterpriseAgentTypeCloud:
		return true
	case CloudEnterpriseAgentTypeEnterpriseCluster:
		return true
	case CloudEnterpriseAgentTypeEnterprise:
		return true
	}
	return false
}

// CloudEnterpriseAgentTypeValues returns every value the specification declares, in
// specification order.
func CloudEnterpriseAgentTypeValues() []CloudEnterpriseAgentType {
	return []CloudEnterpriseAgentType{
		CloudEnterpriseAgentTypeCloud,
		CloudEnterpriseAgentTypeEnterpriseCluster,
		CloudEnterpriseAgentTypeEnterprise,
	}
}

// NetworkProviderType is an enumeration from the OpenAPI specification.
// Classification of the agent's network provider. It is open: values outside
// the enumeration decode and compare as their underlying string.
type NetworkProviderType string

// NetworkProviderType values.
const (
	NetworkProviderTypeUnknown       NetworkProviderType = "unknown"
	NetworkProviderTypeIsp           NetworkProviderType = "isp"
	NetworkProviderTypeCdn           NetworkProviderType = "cdn"
	NetworkProviderTypeStub          NetworkProviderType = "stub"
	NetworkProviderTypeCloudProvider NetworkProviderType = "cloud-provider"
	NetworkProviderTypeCarrier       NetworkProviderType = "carrier"
)

// String returns the value as the API spells it, or "NetworkProviderType(v)" for
// values outside the enumeration.
func (v NetworkProviderType) String() string {
	switch v {
	case NetworkProviderTypeUnknown:
		return "unknown"
	case NetworkProviderTypeIsp:
		return "isp"
	case NetworkProviderTypeCdn:
		return "cdn"
	case NetworkProviderTypeStub:
		return "stub"
	case NetworkProviderTypeCloudProvider:
		return "cloud-provider"
	case NetworkProviderTypeCarrier:
		return "carrier"
	}
	return fmt.Sprintf("NetworkProviderType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v NetworkProviderType) IsKnown() bool {
	switch v {
	case NetworkProviderTypeUnknown:
		return true
	case NetworkProviderTypeIsp:
		return true
	case NetworkProviderTypeCdn:
		return true
	case NetworkProviderTypeStub:
		return true
	case NetworkProviderTypeCloudProvider:
		return true
	case NetworkProviderTypeCarrier:
		return true
	}
	return false
}

// NetworkProviderTypeValues returns every value the specification declares, in
// specification order.
func NetworkProviderTypeValues() []NetworkProviderType {
	return []NetworkProviderType{
		NetworkProviderTypeUnknown,
		NetworkProviderTypeIsp,
		NetworkProviderTypeCdn,
		NetworkProviderTypeStub,
		NetworkProviderTypeCloudProvider,
		NetworkProviderTypeCarrier,
	}
}

// OAuthAuthType is an enumeration from the OpenAPI specification. HTTP
// authentication type used for the OAuth request. It is open: values outside
// the enumeration decode and compare as their underlying string.
type OAuthAuthType string

// OAuthAuthType values.
const (
	OAuthAuthTypeNone  OAuthAuthType = "none"
	OAuthAuthTypeBasic OAuthAuthType = "basic"
	OAuthAuthTypeNtlm  OAuthAuthType = "ntlm"
)

// String returns the value as the API spells it, or "OAuthAuthType(v)" for
// values outside the enumeration.
func (v OAuthAuthType) String() string {
	switch v {
	case OAuthAuthTypeNone:
		return "none"
	case OAuthAuthTypeBasic:
		return "basic"
	case OAuthAuthTypeNtlm:
		return "ntlm"
	}
	return fmt.Sprintf("OAuthAuthType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v OAuthAuthType) IsKnown() bool {
	switch v {
	case OAuthAuthTypeNone:
		return true
	case OAuthAuthTypeBasic:
		return true
	case OAuthAuthTypeNtlm:
		return true
	}
	return false
}

// OAuthAuthTypeValues returns every value the specification declares, in
// specification order.
func OAuthAuthTypeValues() []OAuthAuthType {
	return []OAuthAuthType{
		OAuthAuthTypeNone,
		OAuthAuthTypeBasic,
		OAuthAuthTypeNtlm,
	}
}

// RequestMethod is an enumeration from the OpenAPI specification. HTTP request
// method. It is open: values outside the enumeration decode and compare as
// their underlying string.
type RequestMethod string

// RequestMethod values.
const (
	RequestMethodGet  RequestMethod = "get"
	RequestMethodPost RequestMethod = "post"
)

// String returns the value as the API spells it, or "RequestMethod(v)" for
// values outside the enumeration.
func (v RequestMethod) String() string {
	switch v {
	case RequestMethodGet:
		return "get"
	case RequestMethodPost:
		return "post"
	}
	return fmt.Sprintf("RequestMethod(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v RequestMethod) IsKnown() bool {
	switch v {
	case RequestMethodGet:
		return true
	case RequestMethodPost:
		return true
	}
	return false
}

// RequestMethodValues returns every value the specification declares, in
// specification order.
func RequestMethodValues() []RequestMethod {
	return []RequestMethod{
		RequestMethodGet,
		RequestMethodPost,
	}
}

// TestAuthType is an enumeration from the OpenAPI specification. HTTP
// authentication type. It is open: values outside the enumeration decode and
// compare as their underlying string.
type TestAuthType string

// TestAuthType values.
const (
	TestAuthTypeNone     TestAuthType = "none"
	TestAuthTypeBasic    TestAuthType = "basic"
	TestAuthTypeNtlm     TestAuthType = "ntlm"
	TestAuthTypeKerberos TestAuthType = "kerberos"
	TestAuthTypeOauth    TestAuthType = "oauth"
)

// String returns the value as the API spells it, or "TestAuthType(v)" for
// values outside the enumeration.
func (v TestAuthType) String() string {
	switch v {
	case TestAuthTypeNone:
		return "none"
	case TestAuthTypeBasic:
		return "basic"
	case TestAuthTypeNtlm:
		return "ntlm"
	case TestAuthTypeKerberos:
		return "kerberos"
	case TestAuthTypeOauth:
		return "oauth"
	}
	return fmt.Sprintf("TestAuthType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestAuthType) IsKnown() bool {
	switch v {
	case TestAuthTypeNone:
		return true
	case TestAuthTypeBasic:
		return true
	case TestAuthTypeNtlm:
		return true
	case TestAuthTypeKerberos:
		return true
	case TestAuthTypeOauth:
		return true
	}
	return false
}

// TestAuthTypeValues returns every value the specification declares, in
// specification order.
func TestAuthTypeValues() []TestAuthType {
	return []TestAuthType{
		TestAuthTypeNone,
		TestAuthTypeBasic,
		TestAuthTypeNtlm,
		TestAuthTypeKerberos,
		TestAuthTypeOauth,
	}
}

// TestIpv6Policy is an enumeration from the OpenAPI specification. IP version
// policy. It is open: values outside the enumeration decode and compare as
// their underlying string.
type TestIpv6Policy string

// TestIpv6Policy values.
const (
	TestIpv6PolicyForceIpv4      TestIpv6Policy = "force-ipv4"
	TestIpv6PolicyPreferIpv6     TestIpv6Policy = "prefer-ipv6"
	TestIpv6PolicyForceIpv6      TestIpv6Policy = "force-ipv6"
	TestIpv6PolicyUseAgentPolicy TestIpv6Policy = "use-agent-policy"
)

// String returns the value as the API spells it, or "TestIpv6Policy(v)" for
// values outside the enumeration.
func (v TestIpv6Policy) String() string {
	switch v {
	case TestIpv6PolicyForceIpv4:
		return "force-ipv4"
	case TestIpv6PolicyPreferIpv6:
		return "prefer-ipv6"
	case TestIpv6PolicyForceIpv6:
		return "force-ipv6"
	case TestIpv6PolicyUseAgentPolicy:
		return "use-agent-policy"
	}
	return fmt.Sprintf("TestIpv6Policy(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestIpv6Policy) IsKnown() bool {
	switch v {
	case TestIpv6PolicyForceIpv4:
		return true
	case TestIpv6PolicyPreferIpv6:
		return true
	case TestIpv6PolicyForceIpv6:
		return true
	case TestIpv6PolicyUseAgentPolicy:
		return true
	}
	return false
}

// TestIpv6PolicyValues returns every value the specification declares, in
// specification order.
func TestIpv6PolicyValues() []TestIpv6Policy {
	return []TestIpv6Policy{
		TestIpv6PolicyForceIpv4,
		TestIpv6PolicyPreferIpv6,
		TestIpv6PolicyForceIpv6,
		TestIpv6PolicyUseAgentPolicy,
	}
}

// TestPathTraceMode is an enumeration from the OpenAPI specification. Select
// `inSession` to perform the path trace within a TCP session. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestPathTraceMode string

// TestPathTraceMode values.
const (
	TestPathTraceModeClassic   TestPathTraceMode = "classic"
	TestPathTraceModeInSession TestPathTraceMode = "in-session"
)

// String returns the value as the API spells it, or "TestPathTraceMode(v)" for
// values outside the enumeration.
func (v TestPathTraceMode) String() string {
	switch v {
	case TestPathTraceModeClassic:
		return "classic"
	case TestPathTraceModeInSession:
		return "in-session"
	}
	return fmt.Sprintf("TestPathTraceMode(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestPathTraceMode) IsKnown() bool {
	switch v {
	case TestPathTraceModeClassic:
		return true
	case TestPathTraceModeInSession:
		return true
	}
	return false
}

// TestPathTraceModeValues returns every value the specification declares, in
// specification order.
func TestPathTraceModeValues() []TestPathTraceMode {
	return []TestPathTraceMode{
		TestPathTraceModeClassic,
		TestPathTraceModeInSession,
	}
}

// TestProbeMode is an enumeration from the OpenAPI specification. Probe mode
// used by network test, only valid when the protocol is set to TCP. It is
// open: values outside the enumeration decode and compare as their underlying
// string.
type TestProbeMode string

// TestProbeMode values.
const (
	TestProbeModeAuto TestProbeMode = "auto"
	TestProbeModeSack TestProbeMode = "sack"
	TestProbeModeSyn  TestProbeMode = "syn"
)

// String returns the value as the API spells it, or "TestProbeMode(v)" for
// values outside the enumeration.
func (v TestProbeMode) String() string {
	switch v {
	case TestProbeModeAuto:
		return "auto"
	case TestProbeModeSack:
		return "sack"
	case TestProbeModeSyn:
		return "syn"
	}
	return fmt.Sprintf("TestProbeMode(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestProbeMode) IsKnown() bool {
	switch v {
	case TestProbeModeAuto:
		return true
	case TestProbeModeSack:
		return true
	case TestProbeModeSyn:
		return true
	}
	return false
}

// TestProbeModeValues returns every value the specification declares, in
// specification order.
func TestProbeModeValues() []TestProbeMode {
	return []TestProbeMode{
		TestProbeModeAuto,
		TestProbeModeSack,
		TestProbeModeSyn,
	}
}

// TestProtocol is an enumeration from the OpenAPI specification. Protocol used
// by dependent network tests (end-to-end, path trace, PMTUD). It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestProtocol string

// TestProtocol values.
const (
	TestProtocolTcp  TestProtocol = "tcp"
	TestProtocolIcmp TestProtocol = "icmp"
	TestProtocolUdp  TestProtocol = "udp"
)

// String returns the value as the API spells it, or "TestProtocol(v)" for
// values outside the enumeration.
func (v TestProtocol) String() string {
	switch v {
	case TestProtocolTcp:
		return "tcp"
	case TestProtocolIcmp:
		return "icmp"
	case TestProtocolUdp:
		return "udp"
	}
	return fmt.Sprintf("TestProtocol(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestProtocol) IsKnown() bool {
	switch v {
	case TestProtocolTcp:
		return true
	case TestProtocolIcmp:
		return true
	case TestProtocolUdp:
		return true
	}
	return false
}

// TestProtocolValues returns every value the specification declares, in
// specification order.
func TestProtocolValues() []TestProtocol {
	return []TestProtocol{
		TestProtocolTcp,
		TestProtocolIcmp,
		TestProtocolUdp,
	}
}

// TestSslVersionId is an enumeration from the OpenAPI specification. SSL
// version options: * Use '0' for automatic selection. It is open: values
// outside the enumeration decode and compare as their underlying string.
type TestSslVersionId string

// TestSslVersionId values.
const (
	TestSslVersionIdN0 TestSslVersionId = "0"
	TestSslVersionIdN3 TestSslVersionId = "3"
	TestSslVersionIdN4 TestSslVersionId = "4"
	TestSslVersionIdN5 TestSslVersionId = "5"
	TestSslVersionIdN6 TestSslVersionId = "6"
	TestSslVersionIdN7 TestSslVersionId = "7"
)

// String returns the value as the API spells it, or "TestSslVersionId(v)" for
// values outside the enumeration.
func (v TestSslVersionId) String() string {
	switch v {
	case TestSslVersionIdN0:
		return "0"
	case TestSslVersionIdN3:
		return "3"
	case TestSslVersionIdN4:
		return "4"
	case TestSslVersionIdN5:
		return "5"
	case TestSslVersionIdN6:
		return "6"
	case TestSslVersionIdN7:
		return "7"
	}
	return fmt.Sprintf("TestSslVersionId(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestSslVersionId) IsKnown() bool {
	switch v {
	case TestSslVersionIdN0:
		return true
	case TestSslVersionIdN3:
		return true
	case TestSslVersionIdN4:
		return true
	case TestSslVersionIdN5:
		return true
	case TestSslVersionIdN6:
		return true
	case TestSslVersionIdN7:
		return true
	}
	return false
}

// TestSslVersionIdValues returns every value the specification declares, in
// specification order.
func TestSslVersionIdValues() []TestSslVersionId {
	return []TestSslVersionId{
		TestSslVersionIdN0,
		TestSslVersionIdN3,
		TestSslVersionIdN4,
		TestSslVersionIdN5,
		TestSslVersionIdN6,
		TestSslVersionIdN7,
	}
}

// TestVaultCredentialTarget is an enumeration from the OpenAPI specification.
// The target setting that the credential should be used for. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestVaultCredentialTarget string

// TestVaultCredentialTarget values.
const (
	TestVaultCredentialTargetUsername TestVaultCredentialTarget = "username"
	TestVaultCredentialTargetPassword TestVaultCredentialTarget = "password"
	TestVaultCredentialTargetScript   TestVaultCredentialTarget = "script"
)

// String returns the value as the API spells it, or "TestVaultCredentialTarget(v)" for
// values outside the enumeration.
func (v TestVaultCredentialTarget) String() string {
	switch v {
	case TestVaultCredentialTargetUsername:
		return "username"
	case TestVaultCredentialTargetPassword:
		return "password"
	case TestVaultCredentialTargetScript:
		return "script"
	}
	return fmt.Sprintf("TestVaultCredentialTarget(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestVaultCredentialTarget) IsKnown() bool {
	switch v {
	case TestVaultCredentialTargetUsername:
		return true
	case TestVaultCredentialTargetPassword:
		return true
	case TestVaultCredentialTargetScript:
		return true
	}
	return false
}

// TestVaultCredentialTargetValues returns every value the specification declares, in
// specification order.
func TestVaultCredentialTargetValues() []TestVaultCredentialTarget {
	return []TestVaultCredentialTarget{
		TestVaultCredentialTargetUsername,
		TestVaultCredentialTargetPassword,
		TestVaultCredentialTargetScript,
	}
}
