// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package http_server_instant_tests

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// HTTPServerInstantTests handles communication with the HTTP Server Instant Tests methods of the
	// ThousandEyes API.
	HTTPServerInstantTests struct {
		client client.Client
	}
)

// NewHTTPServerInstantTests returns a HTTP Server Instant Tests service bound to client.
func NewHTTPServerInstantTests(client client.Client) *HTTPServerInstantTests {
	return &HTTPServerInstantTests{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - HTTP Server Instant Tests
// -----------------------------------------------------------------------------

// CreateHttpServerInstantTest create HTTP server instant test.
// URL: POST /tests/http-server/instant
// Optional query params: expand
//
// Creates and runs a new HTTP server instant test.
func (s *HTTPServerInstantTests) CreateHttpServerInstantTest(ctx context.Context, request *HttpServerInstantTestRequest, opts ...client.RequestOption) (*HttpServerInstantTestResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/tests/http-server/instant"

	var result HttpServerInstantTestResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
