// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.109)

package api_keys

import (
	"context"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// APIKeys handles communication with the API Keys methods of the
	// ThousandEyes API.
	APIKeys struct {
		client client.Client
	}
)

// NewAPIKeys returns a API Keys service bound to client.
func NewAPIKeys(client client.Client) *APIKeys {
	return &APIKeys{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - API Keys
// -----------------------------------------------------------------------------

// RegenerateApiKey regenerate API Key.
// URL: POST /api-keys/regenerate
//
// Regenerates the API Key used to authenticate this request.
func (s *APIKeys) RegenerateApiKey(ctx context.Context, opts ...client.RequestOption) (*RegenerateApiKeyResponse, *resty.Response, error) {

	endpoint := "/api-keys/regenerate"

	var result RegenerateApiKeyResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
