// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package dnssec_tests

// AgentResponse is generated from the OpenAPI specification.
type AgentResponse struct {
	// Unique ID of the agent.
	AgentID *string `json:"agentId,omitempty"`
	// Name of the agent.
	AgentName   *string                  `json:"agentName,omitempty"`
	AgentType   CloudEnterpriseAgentType `json:"agentType"`
	Coordinates Coordinates              `json:"coordinates,omitempty"`
	// 2-digit ISO country code
	CountryID *string `json:"countryId,omitempty"`
	// Flag indicating if the agent is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// Array of private IP addresses.
	IpAddresses []string `json:"ipAddresses,omitempty"`
	// Location of the agent.
	Location *string `json:"location,omitempty"`
	// Network (including ASN) of agent’s public IP.
	Network             *string             `json:"network,omitempty"`
	NetworkProviderInfo NetworkProviderInfo `json:"networkProviderInfo,omitempty"`
	// Prefix containing agents public IP address.
	Prefix *string `json:"prefix,omitempty"`
	// Array of public IP addresses.
	PublicIpAddresses []string `json:"publicIpAddresses,omitempty"`
	// Flag indicating if has normal SSL operations or if instead it's set to
	// ignore SSL errors on browserbot-based tests.
	VerifySslCertificates *bool `json:"verifySslCertificates,omitempty"`
}

// AlertRule is generated from the OpenAPI specification.
type AlertRule struct {
	AlertType AlertType      `json:"alertType,omitempty"`
	Direction AlertDirection `json:"direction,omitempty"`
	// String expression of alert rule
	Expression *string `json:"expression,omitempty"`
	// Alert rules allow up to 1 alert rule to be selected as a default for each
	// type.
	IsDefault *bool `json:"isDefault,omitempty"`
	// The minimum number of agents or monitors that must meet the specified
	// criteria in order to trigger the alert
	MinimumSources *int `json:"minimumSources,omitempty"`
	// the minimum percentage of all assigned agents or monitors that must meet the
	// specified criteria in order to trigger the alert
	MinimumSourcesPct   *int                     `json:"minimumSourcesPct,omitempty"`
	RoundsViolatingMode AlertRoundsViolationMode `json:"roundsViolatingMode,omitempty"`
	// Specifies the divisor (y value) for the “X of Y times” condition.
	RoundsViolatingOutOf *int `json:"roundsViolatingOutOf,omitempty"`
	// Specifies the numerator (x value) for the “X of Y times” condition
	RoundsViolatingRequired *int   `json:"roundsViolatingRequired,omitempty"`
	RuleID                  RuleId `json:"ruleId,omitempty"`
	// Name of the alert rule
	RuleName         *string          `json:"ruleName,omitempty"`
	SensitivityLevel SensitivityLevel `json:"sensitivityLevel,omitempty"`
	Severity         Severity         `json:"severity,omitempty"`
}

// Coordinates Geographic coordinates for agent location.
type Coordinates struct {
	// The latitude of the agent location in decimal degrees
	Latitude *float64 `json:"latitude,omitempty"`
	// The longitude of the agent location in decimal degrees
	Longitude *float64 `json:"longitude,omitempty"`
}

// DnsSecTestRequest is generated from the OpenAPI specification.
type DnsSecTestRequest struct {
	Links  TestLinks         `json:"_links,omitempty"`
	Agents TestAgentsRequest `json:"agents"`
	// List of alert rules IDs to apply to the test (get `ruleId` from
	// `/alerts/rules` endpoint.
	AlertRules []string `json:"alertRules,omitempty"`
	// Indicates if alerts are enabled.
	AlertsEnabled *bool           `json:"alertsEnabled,omitempty"`
	CreatedBy     TestCreatedBy   `json:"createdBy,omitempty"`
	CreatedDate   TestCreatedDate `json:"createdDate,omitempty"`
	// A description of the test.
	Description   *string       `json:"description,omitempty"`
	DnsQueryClass DnsQueryClass `json:"dnsQueryClass,omitempty"`
	Domain        TestDomain    `json:"domain"`
	Enabled       Enabled       `json:"enabled,omitempty"`
	Interval      TestInterval  `json:"interval"`
	// Contains list of test label IDs (get `labelId` from `/labels` endpoint)
	Labels []string `json:"labels,omitempty"`
	// Indicates if the test is shared with the account group.
	LiveShare *bool `json:"liveShare,omitempty"`
	// User that modified the test.
	ModifiedBy *string `json:"modifiedBy,omitempty"`
	// UTC last modification date (ISO date-time format).
	ModifiedDate        *string                 `json:"modifiedDate,omitempty"`
	RandomizedStartTime TestRandomizedStartTime `json:"randomizedStartTime,omitempty"`
	// Indicates if the test is a saved event.
	SavedEvent *bool `json:"savedEvent,omitempty"`
	// Contains list of account group IDs.
	SharedWithAccounts []string `json:"sharedWithAccounts,omitempty"`
	// Contains list of test tag IDs (get `id` from `/tags` endpoint).
	Tags []string `json:"tags,omitempty"`
	// Each test is assigned an unique ID; this is used to access test information
	// and results from other endpoints.
	TestID *string `json:"testId,omitempty"`
	// The name of the test.
	TestName *string `json:"testName,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// DnsSecTestResponse is generated from the OpenAPI specification.
type DnsSecTestResponse struct {
	Links  TestLinks          `json:"_links,omitempty"`
	Agents TestAgentsResponse `json:"agents,omitempty"`
	// Contains list of enabled alert rule objects.
	AlertRules []AlertRule `json:"alertRules,omitempty"`
	// Indicates if alerts are enabled.
	AlertsEnabled *bool           `json:"alertsEnabled,omitempty"`
	CreatedBy     TestCreatedBy   `json:"createdBy,omitempty"`
	CreatedDate   TestCreatedDate `json:"createdDate,omitempty"`
	// A description of the test.
	Description   *string       `json:"description,omitempty"`
	DnsQueryClass DnsQueryClass `json:"dnsQueryClass,omitempty"`
	Domain        TestDomain    `json:"domain"`
	Enabled       Enabled       `json:"enabled,omitempty"`
	Interval      TestInterval  `json:"interval"`
	Labels        TestLabels    `json:"labels,omitempty"`
	// Indicates if the test is shared with the account group.
	LiveShare *bool `json:"liveShare,omitempty"`
	// User that modified the test.
	ModifiedBy *string `json:"modifiedBy,omitempty"`
	// UTC last modification date (ISO date-time format).
	ModifiedDate        *string                 `json:"modifiedDate,omitempty"`
	RandomizedStartTime TestRandomizedStartTime `json:"randomizedStartTime,omitempty"`
	// Indicates if the test is a saved event.
	SavedEvent         *bool              `json:"savedEvent,omitempty"`
	SharedWithAccounts TestSharedAccounts `json:"sharedWithAccounts,omitempty"`
	Tags               TestTags           `json:"tags,omitempty"`
	// Each test is assigned an unique ID; this is used to access test information
	// and results from other endpoints.
	TestID *string `json:"testId,omitempty"`
	// The name of the test.
	TestName *string `json:"testName,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// DnsSecTests is generated from the OpenAPI specification.
type DnsSecTests struct {
	Links SelfLinks              `json:"_links,omitempty"`
	Tests []UnexpandedDnsSecTest `json:"tests,omitempty"`
}

// Enabled Test is enabled.
type Enabled bool

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// NetworkProviderInfo Information about the network provider that owns the
// agent's public IP prefix.
type NetworkProviderInfo struct {
	// Autonomous System Number (ASN) announcing the agent's public IP prefix.
	Asn *int64 `json:"asn,omitempty"`
	// Name of the network provider organization.
	Name *string             `json:"name,omitempty"`
	Type NetworkProviderType `json:"type,omitempty"`
}

// RuleId Unique ID of the rule.
type RuleId string

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self Link `json:"self,omitempty"`
}

// SharedWithAccount is generated from the OpenAPI specification.
type SharedWithAccount struct {
	// Account group ID.
	AID *string `json:"aid,omitempty"`
	// Account group name.
	Name *string `json:"name,omitempty"`
}

// TestAgentRequest is generated from the OpenAPI specification.
type TestAgentRequest struct {
	// The agent ID.
	AgentID string `json:"agentId"`
	// The IP address from the `ipAddresses` field in agent details, used for
	// interface selection.
	SourceIpAddress *string `json:"sourceIpAddress,omitempty"`
}

// TestAgentsRequest Contains list of Agent IDs (get `agentId` from `/agents`
// endpoint).
type TestAgentsRequest []TestAgentRequest

// TestAgentsResponse Contains list of agents.
type TestAgentsResponse []AgentResponse

// TestCreatedBy User that created the test.
type TestCreatedBy string

// TestCreatedDate UTC created date (ISO date-time format).
type TestCreatedDate string

// TestDomain The target record for the test, with the record type suffixed. If
// no record type is specified, the test defaults to an ANY record.
type TestDomain string

// TestLabel is generated from the OpenAPI specification.
type TestLabel struct {
	// Value indicating if the label in question is BuiltIn (Account Admin,
	// Organization Admin, Regular User).
	IsBuiltin *bool `json:"isBuiltin,omitempty"`
	// Label ID.
	LabelID *string `json:"labelId,omitempty"`
	// Name of the label.
	Name *string `json:"name,omitempty"`
}

// TestLabels Labels to which the test is assigned. This field is not returned
// for Instant Tests.
type TestLabels []TestLabel

// TestLinks A list of links that can be accessed to get more information
type TestLinks struct {
	Self        TestSelfLink `json:"self,omitempty"`
	TestResults TestResults  `json:"testResults,omitempty"`
}

// TestRandomizedStartTime Indicates whether agents should randomize the start
// time in each test round.
type TestRandomizedStartTime bool

// TestResults Reference to the test results.
type TestResults []Link

// TestSelfLink is generated from the OpenAPI specification.
type TestSelfLink struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// TestSharedAccounts is generated from the OpenAPI specification.
type TestSharedAccounts []SharedWithAccount

// TestTag is generated from the OpenAPI specification.
type TestTag struct {
	// Unique tag ID.
	ID *string `json:"id,omitempty"`
	// Tag key.
	Key *string `json:"key,omitempty"`
	// Tag value.
	Value *string `json:"value,omitempty"`
}

// TestTags Tags assigned to the test. Returned only when `expand=tag` is
// specified. This field is not returned for Instant Tests. For more
// information, see `/tags`.
type TestTags []TestTag

// UnexpandedDnsSecTest is generated from the OpenAPI specification.
type UnexpandedDnsSecTest struct {
	Links TestLinks `json:"_links,omitempty"`
	// Indicates if alerts are enabled.
	AlertsEnabled *bool           `json:"alertsEnabled,omitempty"`
	CreatedBy     TestCreatedBy   `json:"createdBy,omitempty"`
	CreatedDate   TestCreatedDate `json:"createdDate,omitempty"`
	// A description of the test.
	Description   *string       `json:"description,omitempty"`
	DnsQueryClass DnsQueryClass `json:"dnsQueryClass,omitempty"`
	Domain        TestDomain    `json:"domain"`
	Enabled       Enabled       `json:"enabled,omitempty"`
	Interval      TestInterval  `json:"interval"`
	// Indicates if the test is shared with the account group.
	LiveShare *bool `json:"liveShare,omitempty"`
	// User that modified the test.
	ModifiedBy *string `json:"modifiedBy,omitempty"`
	// UTC last modification date (ISO date-time format).
	ModifiedDate        *string                 `json:"modifiedDate,omitempty"`
	RandomizedStartTime TestRandomizedStartTime `json:"randomizedStartTime,omitempty"`
	// Indicates if the test is a saved event.
	SavedEvent *bool `json:"savedEvent,omitempty"`
	// Each test is assigned an unique ID; this is used to access test information
	// and results from other endpoints.
	TestID *string `json:"testId,omitempty"`
	// The name of the test.
	TestName *string `json:"testName,omitempty"`
	Type     *string `json:"type,omitempty"`
}
