// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.103)

package api_instant_tests

import "fmt"

// ApiClientAuthentication is an enumeration from the OpenAPI specification.
// The OAuth2 client authentication location type. It is open: values outside
// the enumeration decode and compare as their underlying string.
type ApiClientAuthentication string

// ApiClientAuthentication values.
const (
	ApiClientAuthenticationBasicAuthHeader ApiClientAuthentication = "basic-auth-header"
	ApiClientAuthenticationInBody          ApiClientAuthentication = "in-body"
)

// String returns the value as the API spells it, or "ApiClientAuthentication(v)" for
// values outside the enumeration.
func (v ApiClientAuthentication) String() string {
	switch v {
	case ApiClientAuthenticationBasicAuthHeader:
		return "basic-auth-header"
	case ApiClientAuthenticationInBody:
		return "in-body"
	}
	return fmt.Sprintf("ApiClientAuthentication(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v ApiClientAuthentication) IsKnown() bool {
	switch v {
	case ApiClientAuthenticationBasicAuthHeader:
		return true
	case ApiClientAuthenticationInBody:
		return true
	}
	return false
}

// ApiClientAuthenticationValues returns every value the specification declares, in
// specification order.
func ApiClientAuthenticationValues() []ApiClientAuthentication {
	return []ApiClientAuthentication{
		ApiClientAuthenticationBasicAuthHeader,
		ApiClientAuthenticationInBody,
	}
}

// ApiRequestAssertionName is an enumeration from the OpenAPI specification.
// Set to `status-code` to assert the response status code. It is open: values
// outside the enumeration decode and compare as their underlying string.
type ApiRequestAssertionName string

// ApiRequestAssertionName values.
const (
	ApiRequestAssertionNameStatusCode   ApiRequestAssertionName = "status-code"
	ApiRequestAssertionNameResponseBody ApiRequestAssertionName = "response-body"
)

// String returns the value as the API spells it, or "ApiRequestAssertionName(v)" for
// values outside the enumeration.
func (v ApiRequestAssertionName) String() string {
	switch v {
	case ApiRequestAssertionNameStatusCode:
		return "status-code"
	case ApiRequestAssertionNameResponseBody:
		return "response-body"
	}
	return fmt.Sprintf("ApiRequestAssertionName(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v ApiRequestAssertionName) IsKnown() bool {
	switch v {
	case ApiRequestAssertionNameStatusCode:
		return true
	case ApiRequestAssertionNameResponseBody:
		return true
	}
	return false
}

// ApiRequestAssertionNameValues returns every value the specification declares, in
// specification order.
func ApiRequestAssertionNameValues() []ApiRequestAssertionName {
	return []ApiRequestAssertionName{
		ApiRequestAssertionNameStatusCode,
		ApiRequestAssertionNameResponseBody,
	}
}

// ApiRequestAssertionOperator is an enumeration from the OpenAPI
// specification. If `name = status-code“, accepted values are [is, is-not].
// It is open: values outside the enumeration decode and compare as their
// underlying string.
type ApiRequestAssertionOperator string

// ApiRequestAssertionOperator values.
const (
	ApiRequestAssertionOperatorIs          ApiRequestAssertionOperator = "is"
	ApiRequestAssertionOperatorIsNot       ApiRequestAssertionOperator = "is-not"
	ApiRequestAssertionOperatorIncludes    ApiRequestAssertionOperator = "includes"
	ApiRequestAssertionOperatorNotIncludes ApiRequestAssertionOperator = "not-includes"
	ApiRequestAssertionOperatorMatches     ApiRequestAssertionOperator = "matches"
	ApiRequestAssertionOperatorNotMatches  ApiRequestAssertionOperator = "not-matches"
)

// String returns the value as the API spells it, or "ApiRequestAssertionOperator(v)" for
// values outside the enumeration.
func (v ApiRequestAssertionOperator) String() string {
	switch v {
	case ApiRequestAssertionOperatorIs:
		return "is"
	case ApiRequestAssertionOperatorIsNot:
		return "is-not"
	case ApiRequestAssertionOperatorIncludes:
		return "includes"
	case ApiRequestAssertionOperatorNotIncludes:
		return "not-includes"
	case ApiRequestAssertionOperatorMatches:
		return "matches"
	case ApiRequestAssertionOperatorNotMatches:
		return "not-matches"
	}
	return fmt.Sprintf("ApiRequestAssertionOperator(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v ApiRequestAssertionOperator) IsKnown() bool {
	switch v {
	case ApiRequestAssertionOperatorIs:
		return true
	case ApiRequestAssertionOperatorIsNot:
		return true
	case ApiRequestAssertionOperatorIncludes:
		return true
	case ApiRequestAssertionOperatorNotIncludes:
		return true
	case ApiRequestAssertionOperatorMatches:
		return true
	case ApiRequestAssertionOperatorNotMatches:
		return true
	}
	return false
}

// ApiRequestAssertionOperatorValues returns every value the specification declares, in
// specification order.
func ApiRequestAssertionOperatorValues() []ApiRequestAssertionOperator {
	return []ApiRequestAssertionOperator{
		ApiRequestAssertionOperatorIs,
		ApiRequestAssertionOperatorIsNot,
		ApiRequestAssertionOperatorIncludes,
		ApiRequestAssertionOperatorNotIncludes,
		ApiRequestAssertionOperatorMatches,
		ApiRequestAssertionOperatorNotMatches,
	}
}

// ApiRequestAuthType is an enumeration from the OpenAPI specification. Will
// override the Authorization request header. It is open: values outside the
// enumeration decode and compare as their underlying string.
type ApiRequestAuthType string

// ApiRequestAuthType values.
const (
	ApiRequestAuthTypeNone        ApiRequestAuthType = "none"
	ApiRequestAuthTypeBasic       ApiRequestAuthType = "basic"
	ApiRequestAuthTypeBearerToken ApiRequestAuthType = "bearer-token"
	ApiRequestAuthTypeOauth2      ApiRequestAuthType = "oauth2"
)

// String returns the value as the API spells it, or "ApiRequestAuthType(v)" for
// values outside the enumeration.
func (v ApiRequestAuthType) String() string {
	switch v {
	case ApiRequestAuthTypeNone:
		return "none"
	case ApiRequestAuthTypeBasic:
		return "basic"
	case ApiRequestAuthTypeBearerToken:
		return "bearer-token"
	case ApiRequestAuthTypeOauth2:
		return "oauth2"
	}
	return fmt.Sprintf("ApiRequestAuthType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v ApiRequestAuthType) IsKnown() bool {
	switch v {
	case ApiRequestAuthTypeNone:
		return true
	case ApiRequestAuthTypeBasic:
		return true
	case ApiRequestAuthTypeBearerToken:
		return true
	case ApiRequestAuthTypeOauth2:
		return true
	}
	return false
}

// ApiRequestAuthTypeValues returns every value the specification declares, in
// specification order.
func ApiRequestAuthTypeValues() []ApiRequestAuthType {
	return []ApiRequestAuthType{
		ApiRequestAuthTypeNone,
		ApiRequestAuthTypeBasic,
		ApiRequestAuthTypeBearerToken,
		ApiRequestAuthTypeOauth2,
	}
}

// ApiRequestMethod is an enumeration from the OpenAPI specification. HTTP
// request method. It is open: values outside the enumeration decode and
// compare as their underlying string.
type ApiRequestMethod string

// ApiRequestMethod values.
const (
	ApiRequestMethodGet    ApiRequestMethod = "get"
	ApiRequestMethodPost   ApiRequestMethod = "post"
	ApiRequestMethodPut    ApiRequestMethod = "put"
	ApiRequestMethodDelete ApiRequestMethod = "delete"
	ApiRequestMethodPatch  ApiRequestMethod = "patch"
)

// String returns the value as the API spells it, or "ApiRequestMethod(v)" for
// values outside the enumeration.
func (v ApiRequestMethod) String() string {
	switch v {
	case ApiRequestMethodGet:
		return "get"
	case ApiRequestMethodPost:
		return "post"
	case ApiRequestMethodPut:
		return "put"
	case ApiRequestMethodDelete:
		return "delete"
	case ApiRequestMethodPatch:
		return "patch"
	}
	return fmt.Sprintf("ApiRequestMethod(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v ApiRequestMethod) IsKnown() bool {
	switch v {
	case ApiRequestMethodGet:
		return true
	case ApiRequestMethodPost:
		return true
	case ApiRequestMethodPut:
		return true
	case ApiRequestMethodDelete:
		return true
	case ApiRequestMethodPatch:
		return true
	}
	return false
}

// ApiRequestMethodValues returns every value the specification declares, in
// specification order.
func ApiRequestMethodValues() []ApiRequestMethod {
	return []ApiRequestMethod{
		ApiRequestMethodGet,
		ApiRequestMethodPost,
		ApiRequestMethodPut,
		ApiRequestMethodDelete,
		ApiRequestMethodPatch,
	}
}

// CloudEnterpriseAgentType is an enumeration from the OpenAPI specification.
// Type of the agent. It is open: values outside the enumeration decode and
// compare as their underlying string.
type CloudEnterpriseAgentType string

// CloudEnterpriseAgentType values.
const (
	CloudEnterpriseAgentTypeCloud             CloudEnterpriseAgentType = "cloud"
	CloudEnterpriseAgentTypeEnterpriseCluster CloudEnterpriseAgentType = "enterprise-cluster"
	CloudEnterpriseAgentTypeEnterprise        CloudEnterpriseAgentType = "enterprise"
)

// String returns the value as the API spells it, or "CloudEnterpriseAgentType(v)" for
// values outside the enumeration.
func (v CloudEnterpriseAgentType) String() string {
	switch v {
	case CloudEnterpriseAgentTypeCloud:
		return "cloud"
	case CloudEnterpriseAgentTypeEnterpriseCluster:
		return "enterprise-cluster"
	case CloudEnterpriseAgentTypeEnterprise:
		return "enterprise"
	}
	return fmt.Sprintf("CloudEnterpriseAgentType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v CloudEnterpriseAgentType) IsKnown() bool {
	switch v {
	case CloudEnterpriseAgentTypeCloud:
		return true
	case CloudEnterpriseAgentTypeEnterpriseCluster:
		return true
	case CloudEnterpriseAgentTypeEnterprise:
		return true
	}
	return false
}

// CloudEnterpriseAgentTypeValues returns every value the specification declares, in
// specification order.
func CloudEnterpriseAgentTypeValues() []CloudEnterpriseAgentType {
	return []CloudEnterpriseAgentType{
		CloudEnterpriseAgentTypeCloud,
		CloudEnterpriseAgentTypeEnterpriseCluster,
		CloudEnterpriseAgentTypeEnterprise,
	}
}

// NetworkProviderType is an enumeration from the OpenAPI specification.
// Classification of the agent's network provider. It is open: values outside
// the enumeration decode and compare as their underlying string.
type NetworkProviderType string

// NetworkProviderType values.
const (
	NetworkProviderTypeUnknown       NetworkProviderType = "unknown"
	NetworkProviderTypeIsp           NetworkProviderType = "isp"
	NetworkProviderTypeCdn           NetworkProviderType = "cdn"
	NetworkProviderTypeStub          NetworkProviderType = "stub"
	NetworkProviderTypeCloudProvider NetworkProviderType = "cloud-provider"
	NetworkProviderTypeCarrier       NetworkProviderType = "carrier"
)

// String returns the value as the API spells it, or "NetworkProviderType(v)" for
// values outside the enumeration.
func (v NetworkProviderType) String() string {
	switch v {
	case NetworkProviderTypeUnknown:
		return "unknown"
	case NetworkProviderTypeIsp:
		return "isp"
	case NetworkProviderTypeCdn:
		return "cdn"
	case NetworkProviderTypeStub:
		return "stub"
	case NetworkProviderTypeCloudProvider:
		return "cloud-provider"
	case NetworkProviderTypeCarrier:
		return "carrier"
	}
	return fmt.Sprintf("NetworkProviderType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v NetworkProviderType) IsKnown() bool {
	switch v {
	case NetworkProviderTypeUnknown:
		return true
	case NetworkProviderTypeIsp:
		return true
	case NetworkProviderTypeCdn:
		return true
	case NetworkProviderTypeStub:
		return true
	case NetworkProviderTypeCloudProvider:
		return true
	case NetworkProviderTypeCarrier:
		return true
	}
	return false
}

// NetworkProviderTypeValues returns every value the specification declares, in
// specification order.
func NetworkProviderTypeValues() []NetworkProviderType {
	return []NetworkProviderType{
		NetworkProviderTypeUnknown,
		NetworkProviderTypeIsp,
		NetworkProviderTypeCdn,
		NetworkProviderTypeStub,
		NetworkProviderTypeCloudProvider,
		NetworkProviderTypeCarrier,
	}
}

// TestPathTraceMode is an enumeration from the OpenAPI specification. Select
// `inSession` to perform the path trace within a TCP session. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestPathTraceMode string

// TestPathTraceMode values.
const (
	TestPathTraceModeClassic   TestPathTraceMode = "classic"
	TestPathTraceModeInSession TestPathTraceMode = "in-session"
)

// String returns the value as the API spells it, or "TestPathTraceMode(v)" for
// values outside the enumeration.
func (v TestPathTraceMode) String() string {
	switch v {
	case TestPathTraceModeClassic:
		return "classic"
	case TestPathTraceModeInSession:
		return "in-session"
	}
	return fmt.Sprintf("TestPathTraceMode(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestPathTraceMode) IsKnown() bool {
	switch v {
	case TestPathTraceModeClassic:
		return true
	case TestPathTraceModeInSession:
		return true
	}
	return false
}

// TestPathTraceModeValues returns every value the specification declares, in
// specification order.
func TestPathTraceModeValues() []TestPathTraceMode {
	return []TestPathTraceMode{
		TestPathTraceModeClassic,
		TestPathTraceModeInSession,
	}
}

// TestProbeMode is an enumeration from the OpenAPI specification. Probe mode
// used by network test, only valid when the protocol is set to TCP. It is
// open: values outside the enumeration decode and compare as their underlying
// string.
type TestProbeMode string

// TestProbeMode values.
const (
	TestProbeModeAuto TestProbeMode = "auto"
	TestProbeModeSack TestProbeMode = "sack"
	TestProbeModeSyn  TestProbeMode = "syn"
)

// String returns the value as the API spells it, or "TestProbeMode(v)" for
// values outside the enumeration.
func (v TestProbeMode) String() string {
	switch v {
	case TestProbeModeAuto:
		return "auto"
	case TestProbeModeSack:
		return "sack"
	case TestProbeModeSyn:
		return "syn"
	}
	return fmt.Sprintf("TestProbeMode(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestProbeMode) IsKnown() bool {
	switch v {
	case TestProbeModeAuto:
		return true
	case TestProbeModeSack:
		return true
	case TestProbeModeSyn:
		return true
	}
	return false
}

// TestProbeModeValues returns every value the specification declares, in
// specification order.
func TestProbeModeValues() []TestProbeMode {
	return []TestProbeMode{
		TestProbeModeAuto,
		TestProbeModeSack,
		TestProbeModeSyn,
	}
}

// TestProtocol is an enumeration from the OpenAPI specification. Protocol used
// by dependent network tests (end-to-end, path trace, PMTUD). It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestProtocol string

// TestProtocol values.
const (
	TestProtocolTcp  TestProtocol = "tcp"
	TestProtocolIcmp TestProtocol = "icmp"
	TestProtocolUdp  TestProtocol = "udp"
)

// String returns the value as the API spells it, or "TestProtocol(v)" for
// values outside the enumeration.
func (v TestProtocol) String() string {
	switch v {
	case TestProtocolTcp:
		return "tcp"
	case TestProtocolIcmp:
		return "icmp"
	case TestProtocolUdp:
		return "udp"
	}
	return fmt.Sprintf("TestProtocol(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestProtocol) IsKnown() bool {
	switch v {
	case TestProtocolTcp:
		return true
	case TestProtocolIcmp:
		return true
	case TestProtocolUdp:
		return true
	}
	return false
}

// TestProtocolValues returns every value the specification declares, in
// specification order.
func TestProtocolValues() []TestProtocol {
	return []TestProtocol{
		TestProtocolTcp,
		TestProtocolIcmp,
		TestProtocolUdp,
	}
}

// TestSslVersionId is an enumeration from the OpenAPI specification. SSL
// version options: * Use '0' for automatic selection. It is open: values
// outside the enumeration decode and compare as their underlying string.
type TestSslVersionId string

// TestSslVersionId values.
const (
	TestSslVersionIdN0 TestSslVersionId = "0"
	TestSslVersionIdN3 TestSslVersionId = "3"
	TestSslVersionIdN4 TestSslVersionId = "4"
	TestSslVersionIdN5 TestSslVersionId = "5"
	TestSslVersionIdN6 TestSslVersionId = "6"
	TestSslVersionIdN7 TestSslVersionId = "7"
)

// String returns the value as the API spells it, or "TestSslVersionId(v)" for
// values outside the enumeration.
func (v TestSslVersionId) String() string {
	switch v {
	case TestSslVersionIdN0:
		return "0"
	case TestSslVersionIdN3:
		return "3"
	case TestSslVersionIdN4:
		return "4"
	case TestSslVersionIdN5:
		return "5"
	case TestSslVersionIdN6:
		return "6"
	case TestSslVersionIdN7:
		return "7"
	}
	return fmt.Sprintf("TestSslVersionId(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestSslVersionId) IsKnown() bool {
	switch v {
	case TestSslVersionIdN0:
		return true
	case TestSslVersionIdN3:
		return true
	case TestSslVersionIdN4:
		return true
	case TestSslVersionIdN5:
		return true
	case TestSslVersionIdN6:
		return true
	case TestSslVersionIdN7:
		return true
	}
	return false
}

// TestSslVersionIdValues returns every value the specification declares, in
// specification order.
func TestSslVersionIdValues() []TestSslVersionId {
	return []TestSslVersionId{
		TestSslVersionIdN0,
		TestSslVersionIdN3,
		TestSslVersionIdN4,
		TestSslVersionIdN5,
		TestSslVersionIdN6,
		TestSslVersionIdN7,
	}
}

// TestVaultCredentialTarget is an enumeration from the OpenAPI specification.
// The target setting that the credential should be used for. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type TestVaultCredentialTarget string

// TestVaultCredentialTarget values.
const (
	TestVaultCredentialTargetUsername TestVaultCredentialTarget = "username"
	TestVaultCredentialTargetPassword TestVaultCredentialTarget = "password"
	TestVaultCredentialTargetScript   TestVaultCredentialTarget = "script"
)

// String returns the value as the API spells it, or "TestVaultCredentialTarget(v)" for
// values outside the enumeration.
func (v TestVaultCredentialTarget) String() string {
	switch v {
	case TestVaultCredentialTargetUsername:
		return "username"
	case TestVaultCredentialTargetPassword:
		return "password"
	case TestVaultCredentialTargetScript:
		return "script"
	}
	return fmt.Sprintf("TestVaultCredentialTarget(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TestVaultCredentialTarget) IsKnown() bool {
	switch v {
	case TestVaultCredentialTargetUsername:
		return true
	case TestVaultCredentialTargetPassword:
		return true
	case TestVaultCredentialTargetScript:
		return true
	}
	return false
}

// TestVaultCredentialTargetValues returns every value the specification declares, in
// specification order.
func TestVaultCredentialTargetValues() []TestVaultCredentialTarget {
	return []TestVaultCredentialTarget{
		TestVaultCredentialTargetUsername,
		TestVaultCredentialTargetPassword,
		TestVaultCredentialTargetScript,
	}
}
