// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.103)

package tags

import "fmt"

// AccessType is an enumeration from the OpenAPI specification. The access
// level of the tag. It is open: values outside the enumeration decode and
// compare as their underlying string.
type AccessType string

// AccessType values.
const (
	AccessTypeAll     AccessType = "all"
	AccessTypePartner AccessType = "partner"
	AccessTypeSystem  AccessType = "system"
)

// String returns the value as the API spells it, or "AccessType(v)" for
// values outside the enumeration.
func (v AccessType) String() string {
	switch v {
	case AccessTypeAll:
		return "all"
	case AccessTypePartner:
		return "partner"
	case AccessTypeSystem:
		return "system"
	}
	return fmt.Sprintf("AccessType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v AccessType) IsKnown() bool {
	switch v {
	case AccessTypeAll:
		return true
	case AccessTypePartner:
		return true
	case AccessTypeSystem:
		return true
	}
	return false
}

// AccessTypeValues returns every value the specification declares, in
// specification order.
func AccessTypeValues() []AccessType {
	return []AccessType{
		AccessTypeAll,
		AccessTypePartner,
		AccessTypeSystem,
	}
}

// AssignmentType is an enumeration from the OpenAPI specification. It is open:
// values outside the enumeration decode and compare as their underlying
// string.
type AssignmentType string

// AssignmentType values.
const (
	AssignmentTypeTest                 AssignmentType = "test"
	AssignmentTypeVAgent               AssignmentType = "v-agent"
	AssignmentTypeEndpointTest         AssignmentType = "endpoint-test"
	AssignmentTypeDashboard            AssignmentType = "dashboard"
	AssignmentTypeConnectedDevicesTest AssignmentType = "connected-devices-test"
)

// String returns the value as the API spells it, or "AssignmentType(v)" for
// values outside the enumeration.
func (v AssignmentType) String() string {
	switch v {
	case AssignmentTypeTest:
		return "test"
	case AssignmentTypeVAgent:
		return "v-agent"
	case AssignmentTypeEndpointTest:
		return "endpoint-test"
	case AssignmentTypeDashboard:
		return "dashboard"
	case AssignmentTypeConnectedDevicesTest:
		return "connected-devices-test"
	}
	return fmt.Sprintf("AssignmentType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v AssignmentType) IsKnown() bool {
	switch v {
	case AssignmentTypeTest:
		return true
	case AssignmentTypeVAgent:
		return true
	case AssignmentTypeEndpointTest:
		return true
	case AssignmentTypeDashboard:
		return true
	case AssignmentTypeConnectedDevicesTest:
		return true
	}
	return false
}

// AssignmentTypeValues returns every value the specification declares, in
// specification order.
func AssignmentTypeValues() []AssignmentType {
	return []AssignmentType{
		AssignmentTypeTest,
		AssignmentTypeVAgent,
		AssignmentTypeEndpointTest,
		AssignmentTypeDashboard,
		AssignmentTypeConnectedDevicesTest,
	}
}

// ObjectType is an enumeration from the OpenAPI specification. The object type
// associated with the tag It is open: values outside the enumeration decode
// and compare as their underlying string.
type ObjectType string

// ObjectType values.
const (
	ObjectTypeTest                 ObjectType = "test"
	ObjectTypeDashboard            ObjectType = "dashboard"
	ObjectTypeEndpointTest         ObjectType = "endpoint-test"
	ObjectTypeVAgent               ObjectType = "v-agent"
	ObjectTypeConnectedDevicesTest ObjectType = "connected-devices-test"
	ObjectTypeEndpointAgent        ObjectType = "endpoint-agent"
)

// String returns the value as the API spells it, or "ObjectType(v)" for
// values outside the enumeration.
func (v ObjectType) String() string {
	switch v {
	case ObjectTypeTest:
		return "test"
	case ObjectTypeDashboard:
		return "dashboard"
	case ObjectTypeEndpointTest:
		return "endpoint-test"
	case ObjectTypeVAgent:
		return "v-agent"
	case ObjectTypeConnectedDevicesTest:
		return "connected-devices-test"
	case ObjectTypeEndpointAgent:
		return "endpoint-agent"
	}
	return fmt.Sprintf("ObjectType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v ObjectType) IsKnown() bool {
	switch v {
	case ObjectTypeTest:
		return true
	case ObjectTypeDashboard:
		return true
	case ObjectTypeEndpointTest:
		return true
	case ObjectTypeVAgent:
		return true
	case ObjectTypeConnectedDevicesTest:
		return true
	case ObjectTypeEndpointAgent:
		return true
	}
	return false
}

// ObjectTypeValues returns every value the specification declares, in
// specification order.
func ObjectTypeValues() []ObjectType {
	return []ObjectType{
		ObjectTypeTest,
		ObjectTypeDashboard,
		ObjectTypeEndpointTest,
		ObjectTypeVAgent,
		ObjectTypeConnectedDevicesTest,
		ObjectTypeEndpointAgent,
	}
}

// TagFilterMode is an enumeration from the OpenAPI specification. Type of
// matching logic applied to the values: * `in`: The value on the agent must
// match one of the list of values provided. It is open: values outside the
// enumeration decode and compare as their underlying string.
type TagFilterMode string

// TagFilterMode values.
const (
	TagFilterModeIn    TagFilterMode = "in"
	TagFilterModeNotIn TagFilterMode = "not-in"
)

// String returns the value as the API spells it, or "TagFilterMode(v)" for
// values outside the enumeration.
func (v TagFilterMode) String() string {
	switch v {
	case TagFilterModeIn:
		return "in"
	case TagFilterModeNotIn:
		return "not-in"
	}
	return fmt.Sprintf("TagFilterMode(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TagFilterMode) IsKnown() bool {
	switch v {
	case TagFilterModeIn:
		return true
	case TagFilterModeNotIn:
		return true
	}
	return false
}

// TagFilterModeValues returns every value the specification declares, in
// specification order.
func TagFilterModeValues() []TagFilterMode {
	return []TagFilterMode{
		TagFilterModeIn,
		TagFilterModeNotIn,
	}
}

// TagFilterScope is an enumeration from the OpenAPI specification. Scope of
// the filter. It is open: values outside the enumeration decode and compare as
// their underlying string.
type TagFilterScope string

// TagFilterScope values.
const (
	TagFilterScopeDefault TagFilterScope = "default"
	TagFilterScopeCustom  TagFilterScope = "custom"
)

// String returns the value as the API spells it, or "TagFilterScope(v)" for
// values outside the enumeration.
func (v TagFilterScope) String() string {
	switch v {
	case TagFilterScopeDefault:
		return "default"
	case TagFilterScopeCustom:
		return "custom"
	}
	return fmt.Sprintf("TagFilterScope(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TagFilterScope) IsKnown() bool {
	switch v {
	case TagFilterScopeDefault:
		return true
	case TagFilterScopeCustom:
		return true
	}
	return false
}

// TagFilterScopeValues returns every value the specification declares, in
// specification order.
func TagFilterScopeValues() []TagFilterScope {
	return []TagFilterScope{
		TagFilterScopeDefault,
		TagFilterScopeCustom,
	}
}

// TagMatchType is an enumeration from the OpenAPI specification. Specifies how
// filters (tag keys) are applied (matched) to objects for tag assignment. It
// is open: values outside the enumeration decode and compare as their
// underlying string.
type TagMatchType string

// TagMatchType values.
const (
	TagMatchTypeAnd TagMatchType = "and"
	TagMatchTypeOr  TagMatchType = "or"
)

// String returns the value as the API spells it, or "TagMatchType(v)" for
// values outside the enumeration.
func (v TagMatchType) String() string {
	switch v {
	case TagMatchTypeAnd:
		return "and"
	case TagMatchTypeOr:
		return "or"
	}
	return fmt.Sprintf("TagMatchType(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v TagMatchType) IsKnown() bool {
	switch v {
	case TagMatchTypeAnd:
		return true
	case TagMatchTypeOr:
		return true
	}
	return false
}

// TagMatchTypeValues returns every value the specification declares, in
// specification order.
func TagMatchTypeValues() []TagMatchType {
	return []TagMatchType{
		TagMatchTypeAnd,
		TagMatchTypeOr,
	}
}

// Type is an enumeration from the OpenAPI specification. The nature of the tag
// - whether the tag is dynamically assigned to objects based on a filter rule
// or statically assigned to specified objects. It is open: values outside the
// enumeration decode and compare as their underlying string.
type Type string

// Type values.
const (
	TypeStatic  Type = "static"
	TypeDynamic Type = "dynamic"
)

// String returns the value as the API spells it, or "Type(v)" for
// values outside the enumeration.
func (v Type) String() string {
	switch v {
	case TypeStatic:
		return "static"
	case TypeDynamic:
		return "dynamic"
	}
	return fmt.Sprintf("Type(%v)", string(v))
}

// IsKnown reports whether v is one of the values the specification declares.
// A false result is not an error: the enumeration is open, and the API adds
// values without a major version change.
func (v Type) IsKnown() bool {
	switch v {
	case TypeStatic:
		return true
	case TypeDynamic:
		return true
	}
	return false
}

// TypeValues returns every value the specification declares, in
// specification order.
func TypeValues() []Type {
	return []Type{
		TypeStatic,
		TypeDynamic,
	}
}
