// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package tags

// Assignment is generated from the OpenAPI specification.
type Assignment struct {
	// Object Id
	ID   *string        `json:"id,omitempty"`
	Type AssignmentType `json:"type,omitempty"`
}

// BulkTagResponse is generated from the OpenAPI specification.
type BulkTagResponse struct {
	Links  *SelfLinks           `json:"_links,omitempty"`
	Errors []TagBulkCreateError `json:"errors,omitempty"`
	Tags   []Tag                `json:"tags,omitempty"`
}

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self *Link `json:"self,omitempty"`
}

// Tag is generated from the OpenAPI specification.
type Tag struct {
	Links      *SelfLinks `json:"_links,omitempty"`
	AccessType AccessType `json:"accessType,omitempty"`
	// The account group ID
	AID         *int64       `json:"aid,omitempty"`
	Assignments []Assignment `json:"assignments,omitempty"`
	// Indicates whether it is a built-in tag or a user-created (custom) tag.
	BuiltIn *bool `json:"builtIn,omitempty"`
	// Tag color
	Color *string `json:"color,omitempty"`
	// Tag creation date
	CreateDate *string `json:"createDate,omitempty"`
	// The tag's description.
	Description *string `json:"description,omitempty"`
	// The combination of filters (filter keys) dynamically assigned to an
	// `endpoint-agent` as determined by the matching logic (`and` or `or`).
	Filters []TagFilter `json:"filters,omitempty"`
	Icon    *string     `json:"icon,omitempty"`
	// The tag ID
	ID *string `json:"id,omitempty"`
	// The tags's key
	Key       *string      `json:"key,omitempty"`
	LegacyID  *float64     `json:"legacyId,omitempty"`
	MatchType TagMatchType `json:"matchType,omitempty"`
	// The date and time the tag was last modified.
	ModifiedDate *string    `json:"modifiedDate,omitempty"`
	ObjectType   ObjectType `json:"objectType,omitempty"`
	Type         Type       `json:"type,omitempty"`
	// The tag's value
	Value *string `json:"value,omitempty"`
}

// TagBulkCreateError is generated from the OpenAPI specification.
type TagBulkCreateError struct {
	// Status / error message
	Message *string `json:"message,omitempty"`
	// HTTP response code
	ResponseCode *int               `json:"responseCode,omitempty"`
	Tag          map[string]TagInfo `json:"tag,omitempty"`
}

// TagFilter is generated from the OpenAPI specification.
type TagFilter struct {
	// Filter key used for filtering.
	Key    *string        `json:"key,omitempty"`
	Mode   TagFilterMode  `json:"mode,omitempty"`
	Scope  TagFilterScope `json:"scope,omitempty"`
	Values []string       `json:"values,omitempty"`
}

// TagInfo is generated from the OpenAPI specification.
type TagInfo struct {
	AccessType AccessType `json:"accessType,omitempty"`
	// The account group ID
	AID         *int64       `json:"aid,omitempty"`
	Assignments []Assignment `json:"assignments,omitempty"`
	// Indicates whether it is a built-in tag or a user-created (custom) tag.
	BuiltIn *bool `json:"builtIn,omitempty"`
	// Tag color
	Color *string `json:"color,omitempty"`
	// Tag creation date
	CreateDate *string `json:"createDate,omitempty"`
	// The tag's description.
	Description *string `json:"description,omitempty"`
	// The combination of filters (filter keys) dynamically assigned to an
	// `endpoint-agent` as determined by the matching logic (`and` or `or`).
	Filters []TagFilter `json:"filters,omitempty"`
	Icon    *string     `json:"icon,omitempty"`
	// The tag ID
	ID *string `json:"id,omitempty"`
	// The tags's key
	Key       *string      `json:"key,omitempty"`
	LegacyID  *float64     `json:"legacyId,omitempty"`
	MatchType TagMatchType `json:"matchType,omitempty"`
	// The date and time the tag was last modified.
	ModifiedDate *string    `json:"modifiedDate,omitempty"`
	ObjectType   ObjectType `json:"objectType,omitempty"`
	Type         Type       `json:"type,omitempty"`
	// The tag's value
	Value *string `json:"value,omitempty"`
}

// ResourceTags is generated from the OpenAPI specification.
type ResourceTags struct {
	Links *SelfLinks `json:"_links,omitempty"`
	Tags  []Tag      `json:"tags,omitempty"`
}
