// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.99)

package tags

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// Tags handles communication with the Tags methods of the
	// ThousandEyes API.
	Tags struct {
		client client.Client
	}
)

// NewTags returns a Tags service bound to client.
func NewTags(client client.Client) *Tags {
	return &Tags{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - Tags
// -----------------------------------------------------------------------------

// GetTags list tags.
// URL: GET /tags
// Optional query params: expand
//
// This operation returns a list of tags in the specified account group
// (`aid`).
func (s *Tags) GetTags(ctx context.Context, opts ...client.RequestOption) (*ResourceTags, *resty.Response, error) {

	endpoint := "/tags"

	var result ResourceTags

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateTag create tag.
// URL: POST /tags
//
// Creates a new tag.
func (s *Tags) CreateTag(ctx context.Context, request *TagInfo, opts ...client.RequestOption) (*Tag, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/tags"

	var result Tag

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// CreateTags create multiple tags.
// URL: POST /tags/bulk
//
// Creates multiple tags.
func (s *Tags) CreateTags(ctx context.Context, request *BulkTagResponse, opts ...client.RequestOption) (*BulkTagResponse, *resty.Response, error) {
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := "/tags/bulk"

	var result BulkTagResponse

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Post(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteTag delete tag.
// URL: DELETE /tags/{id}
//
// Deletes a tag.
func (s *Tags) DeleteTag(ctx context.Context, id string, opts ...client.RequestOption) (*resty.Response, error) {
	if id == "" {
		return nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/tags/%s", id)

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Delete(endpoint)
	if err != nil {
		return resp, err
	}

	return resp, nil
}

// GetTag retrieve tag.
// URL: GET /tags/{id}
// Optional query params: expand
//
// Retrieves a tag using its ID.
func (s *Tags) GetTag(ctx context.Context, id string, opts ...client.RequestOption) (*Tag, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}

	endpoint := fmt.Sprintf("/tags/%s", id)

	var result Tag

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateTag update tag.
// URL: PUT /tags/{id}
//
// Updates a tag.
func (s *Tags) UpdateTag(ctx context.Context, id string, request *TagInfo, opts ...client.RequestOption) (*Tag, *resty.Response, error) {
	if id == "" {
		return nil, nil, fmt.Errorf("id is required")
	}
	if request == nil {
		return nil, nil, fmt.Errorf("request is required")
	}

	endpoint := fmt.Sprintf("/tags/%s", id)

	var result Tag

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetHeader("Content-Type", constants.ApplicationJSON).
		SetBody(request).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Put(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
