// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package bgp_monitors

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// Monitor is generated from the OpenAPI specification.
type Monitor struct {
	// Country ID
	CountryID *string `json:"countryId,omitempty"`
	// IP address of the BGP monitor
	IpAddress *string `json:"ipAddress,omitempty"`
	// BGP monitor ID
	MonitorID *string `json:"monitorId,omitempty"`
	// Display name of the BGP monitor
	MonitorName *string     `json:"monitorName,omitempty"`
	MonitorType MonitorType `json:"monitorType,omitempty"`
	// Name of the autonomous system in which the monitor is found
	Network *string `json:"network,omitempty"`
}

// Monitors is generated from the OpenAPI specification.
type Monitors struct {
	Links    *SelfLinks `json:"_links,omitempty"`
	Monitors []Monitor  `json:"monitors,omitempty"`
}

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self *Link `json:"self,omitempty"`
}
