// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package bgp_monitors

import (
	"context"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/client"
	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/constants"
	"resty.dev/v3"
)

type (
	// BGPMonitors handles communication with the BGP monitors methods of the
	// ThousandEyes API.
	BGPMonitors struct {
		client client.Client
	}
)

// NewBGPMonitors returns a BGP monitors service bound to client.
func NewBGPMonitors(client client.Client) *BGPMonitors {
	return &BGPMonitors{client: client}
}

// -----------------------------------------------------------------------------
// ThousandEyes API - BGP monitors
// -----------------------------------------------------------------------------

// GetBgpMonitors list BGP monitors.
// URL: GET /monitors
//
// Retrieves a list of BGP monitors available to your account in ThousandEyes,
// including public and private feeds.
func (s *BGPMonitors) GetBgpMonitors(ctx context.Context, opts ...client.RequestOption) (*Monitors, *resty.Response, error) {

	endpoint := "/monitors"

	var result Monitors

	req := s.client.NewRequest(ctx).
		SetHeader("Accept", constants.Accept).
		SetResult(&result).
		SetQueryParam("aid", s.client.AccountGroupID())

	// Optional query parameters and per-call overrides.
	for _, opt := range opts {
		opt(req)
	}

	resp, err := req.Get(endpoint)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
