// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.98)

package endpoint_agents

// AccountId A unique identifier associated with your account group. You can
// retrieve your `AccountGroupId` from the `/account-groups` endpoint.
type AccountId string

// AddressProfile A description of the IPs assigned to this machine.
type AddressProfile struct {
	AddressType AddressType `json:"addressType,omitempty"`
	// The default gateway for this interface.
	Gateway *string `json:"gateway,omitempty"`
	// IP address of this interface in the network it's currently connected to.
	IpAddress *string `json:"ipAddress,omitempty"`
	// The number of bits representing the network part of the `ipAddress`.
	PrefixLength *int `json:"prefixLength,omitempty"`
	// The router's MAC address resolved from an ARP request.
	RouterHardwareAddress *string `json:"routerHardwareAddress,omitempty"`
}

// AgentName Returns only agents with the specified name. This is an exact
// match only.
type AgentName string

// AgentSearchFilters is generated from the OpenAPI specification.
type AgentSearchFilters struct {
	// Returns only agents with the given name.
	AgentName []AgentName `json:"agentName,omitempty"`
	// IDs of devices that has the Cisco Secure Client deployed with the Internet
	// Security module.
	AnyConnectDeviceID []string `json:"anyConnectDeviceId,omitempty"`
	// Returns only agents with the given computer name.
	ComputerName []ComputerName `json:"computerName,omitempty"`
	// Returns only agents that are an exact match of the provided identifiers.
	ID []EndpointAgentId `json:"id,omitempty"`
	// Filter on the agent's license type
	LicenseType []AgentLicenseType `json:"licenseType,omitempty"`
	// This is a prefix match on the city name field.
	LocationCity []string `json:"locationCity,omitempty"`
	// Filter using the ISO country code of the location.
	LocationCountryISO []string `json:"locationCountryISO,omitempty"`
	// Filter using the code for the first level administrative division within the
	// country.
	LocationSubdivision1Code []string `json:"locationSubdivision1Code,omitempty"`
	// Returns only agents whose NIC driver version is an exact, case-sensitive
	// match for one of the provided values.
	NicDriverVersion []string `json:"nicDriverVersion,omitempty"`
	// Returns only agents whose NIC model is an exact, case-sensitive match for
	// one of the provided values.
	NicModel []string `json:"nicModel,omitempty"`
	// Case-insensitive prefix filter on the OS version.
	OsVersion []string `json:"osVersion,omitempty"`
	// Filter on the platform on which the agent is running.
	Platform []Platform `json:"platform,omitempty"`
	// Case-insensitive prefix filter on the serial number.
	SerialNumber []string `json:"serialNumber,omitempty"`
	// Returns only agents that have at least one user principal name, starting
	// with one of the provided strings.
	UserPrincipalName []string `json:"userPrincipalName,omitempty"`
	// Returns only agents that have at least one user with a name.
	Username []string `json:"username,omitempty"`
}

// AgentSearchRequest Parameters for filtering a list of agents.
type AgentSearchRequest struct {
	SearchFilters   AgentSearchFilters    `json:"searchFilters,omitempty"`
	SearchSort      []AgentSearchSort     `json:"searchSort,omitempty"`
	ThresholdFilter AgentThresholdFilters `json:"thresholdFilter,omitempty"`
}

// AgentSearchSort is generated from the OpenAPI specification.
type AgentSearchSort struct {
	Order SortOrder          `json:"order,omitempty"`
	Sort  AgentSearchSortKey `json:"sort,omitempty"`
}

// AgentThresholdFilter The metric is filtered based on the threshold value and
// operator provided.
type AgentThresholdFilter struct {
	Name     *string                 `json:"name,omitempty"`
	Operator ThresholdFilterOperator `json:"operator,omitempty"`
	// The threshold value.
	Value *float64 `json:"value,omitempty"`
}

// AgentThresholdFilters All filters are applied based on the conditional
// operator (and/or).
type AgentThresholdFilters struct {
	ConditionalOperator ConditionalOperator    `json:"conditionalOperator,omitempty"`
	Filters             []AgentThresholdFilter `json:"filters,omitempty"`
}

// BatteryMetrics Battery metrics for the endpoint agent.
type BatteryMetrics struct {
	// Battery health as a normalized percentage (0-1).
	BatteryHealthNormalizedPercent *float64     `json:"batteryHealthNormalizedPercent,omitempty"`
	BatteryLevel                   BatteryLevel `json:"batteryLevel"`
	// Battery level as a normalized percentage (0-1).
	BatteryLevelNormalizedPercent float64 `json:"batteryLevelNormalizedPercent"`
}

// CellularNetworkGen Cellular network generation.
type CellularNetworkGen string

// CellularProfile Cellular network profile information for a mobile endpoint
// agent.
type CellularProfile struct {
	AdvertisedNetworkGen CellularNetworkGen `json:"advertisedNetworkGen,omitempty"`
	// Advertised Network subtype
	AdvertisedNetworkSubtype *string `json:"advertisedNetworkSubtype,omitempty"`
	// Carrier name
	CarrierName *string            `json:"carrierName,omitempty"`
	NetworkGen  CellularNetworkGen `json:"networkGen,omitempty"`
	// A real network subtype.
	NetworkSubtype *string `json:"networkSubtype,omitempty"`
	// Received Signal Code Power in dBm.
	Rscp *float64 `json:"rscp,omitempty"`
	// Reference Signal Received Power in dBm.
	Rsrp *float64 `json:"rsrp,omitempty"`
	// Reference Signal Received Quality in dBm.
	Rsrq *float64 `json:"rsrq,omitempty"`
	// Received Signal Strength Indicator in dBm.
	Rssi *float64 `json:"rssi,omitempty"`
	// Signal to Interference and Noise Ratio in dBm.
	Sinr *float64 `json:"sinr,omitempty"`
}

// ComputerName Returns only agents with the specified computer name. This is
// an exact match only.
type ComputerName string

// ConnectionString is generated from the OpenAPI specification.
type ConnectionString struct {
	Links SelfLinks `json:"_links,omitempty"`
	// The connection string is used for some integrations and other client types.
	ConnectionString *string `json:"connectionString,omitempty"`
}

// EndpointAgent The `EndpointAgent` object, which may include multiple
// clients.
type EndpointAgent struct {
	Links           SelfLinks          `json:"_links,omitempty"`
	AgentType       *string            `json:"agentType,omitempty"`
	AID             AccountId          `json:"aid,omitempty"`
	AsnDetails      EndpointAsnDetails `json:"asnDetails,omitempty"`
	BatteryMetrics  BatteryMetrics     `json:"batteryMetrics,omitempty"`
	CellularProfile CellularProfile    `json:"cellularProfile,omitempty"`
	// List of clients (user accounts) that the agent works with.
	Clients          []EndpointClient `json:"clients,omitempty"`
	ComputerName     *string          `json:"computerName,omitempty"`
	CreatedAt        *string          `json:"createdAt,omitempty"`
	Deleted          *bool            `json:"deleted,omitempty"`
	ExternalMetadata ExternalMetadata `json:"externalMetadata,omitempty"`
	// Free storage space as a normalized percentage (0-1).
	FreeDiskSpaceNormalized *float64        `json:"freeDiskSpaceNormalized,omitempty"`
	ID                      EndpointAgentId `json:"id,omitempty"`
	KernelVersion           *string         `json:"kernelVersion,omitempty"`
	// The last time the agent checked-in.
	LastSeen     *string               `json:"lastSeen,omitempty"`
	LicenseType  AgentLicenseType      `json:"licenseType,omitempty"`
	Location     EndpointAgentLocation `json:"location,omitempty"`
	Manufacturer *string               `json:"manufacturer,omitempty"`
	Model        *string               `json:"model,omitempty"`
	// The name of the agent.
	Name *string `json:"name,omitempty"`
	// List of network interfaces on the agent.
	NetworkInterfaceProfiles []InterfaceProfile `json:"networkInterfaceProfiles,omitempty"`
	// Network interface card driver version.
	NicDriverVersion *string `json:"nicDriverVersion,omitempty"`
	// Network interface card model.
	NicModel *string `json:"nicModel,omitempty"`
	// For Windows agents, the version of the NPCAP driver that the agent has
	// loaded.
	NpcapVersion    *string  `json:"npcapVersion,omitempty"`
	NumberOfClients *int64   `json:"numberOfClients,omitempty"`
	OsVersion       *string  `json:"osVersion,omitempty"`
	Platform        Platform `json:"platform,omitempty"`
	PublicIP        *string  `json:"publicIP,omitempty"`
	SerialNumber    *string  `json:"serialNumber,omitempty"`
	Status          Status   `json:"status,omitempty"`
	// The latest available version of the agent.
	TargetVersion *string `json:"targetVersion,omitempty"`
	// Status of TCP test support on the agent.
	TcpDriverAvailable *bool   `json:"tcpDriverAvailable,omitempty"`
	TotalMemory        *string `json:"totalMemory,omitempty"`
	// Version of the agent software running.
	Version *string `json:"version,omitempty"`
	// List of VPN connections on the agent.
	VpnProfiles []EndpointVpnProfile `json:"vpnProfiles,omitempty"`
}

// EndpointAgentEthernetProfile Information about the ethernet connectivity of
// this device. Only present if the hardware type is `ethernet`.
type EndpointAgentEthernetProfile struct {
	// Link speed in Mbps.
	LinkSpeed *int `json:"linkSpeed,omitempty"`
}

// EndpointAgentId Unique ID of endpoint agent, from `/endpoint/agents`
// endpoint.
type EndpointAgentId string

// EndpointAgentLocation Approximate location of the agent.
type EndpointAgentLocation struct {
	Latitude     *float64 `json:"latitude,omitempty"`
	LocationName *string  `json:"locationName,omitempty"`
	Longitude    *float64 `json:"longitude,omitempty"`
}

// EndpointAgentUpdate The `EndpointAgentUpdate` object contains supported
// fields for updates.
type EndpointAgentUpdate struct {
	LicenseType AgentLicenseType `json:"licenseType,omitempty"`
	// New agent name.
	Name *string `json:"name,omitempty"`
}

// EndpointAsnDetails is generated from the OpenAPI specification.
type EndpointAsnDetails struct {
	// Name of autonomous system.
	AsName *string `json:"asName,omitempty"`
	// Autonomous system number.
	AsNumber int64 `json:"asNumber"`
}

// EndpointBrowserExtension is generated from the OpenAPI specification.
type EndpointBrowserExtension struct {
	// Flag indicating if there is communication between the extension and
	// ThousandEyes portal.
	Active  *bool       `json:"active,omitempty"`
	Browser BrowserType `json:"browser,omitempty"`
	// Indicates if the extension is disabled or enabled in the web browser.
	Enabled *bool `json:"enabled,omitempty"`
	// Contains any errors encountered while getting extension status.
	Error *string `json:"error,omitempty"`
	// Name of the browser profile where this extension is stored.
	Profile *string `json:"profile,omitempty"`
	// Endpoint agent browser extension version.
	Version *string `json:"version,omitempty"`
}

// EndpointClient Information about the user who has the agent installed.
type EndpointClient struct {
	BrowserExtensions []EndpointBrowserExtension `json:"browserExtensions,omitempty"`
	UserProfile       EndpointUserProfile        `json:"userProfile,omitempty"`
}

// EndpointUserProfile is generated from the OpenAPI specification.
type EndpointUserProfile struct {
	UserName          string  `json:"userName"`
	UserPrincipalName *string `json:"userPrincipalName,omitempty"`
}

// EndpointVpnProfile is generated from the OpenAPI specification.
type EndpointVpnProfile struct {
	// Interface name associated with `interfaceProfile`.
	InterfaceName *string `json:"interfaceName,omitempty"`
	// List of private IP addresses assigned to the device, by the VPN server.
	VpnClientAddresses []string `json:"vpnClientAddresses"`
	// List of private networks assigned to the device, by the VPN server.
	VpnClientNetworkRange []string `json:"vpnClientNetworkRange"`
	// IP address of the VPN gateway.
	VpnGatewayAddress *string `json:"vpnGatewayAddress,omitempty"`
	VpnType           VpnType `json:"vpnType,omitempty"`
}

// ExternalMetadata List of external metadata assigned to the endpoint agent.
// Visible only if the `expandAgent=externalMetadata` query parameter is
// included.
type ExternalMetadata []ExternalMetadataItem

// ExternalMetadataItem is generated from the OpenAPI specification.
type ExternalMetadataItem struct {
	// ID of the device that has the Cisco Secure Client deployed with the Internet
	// Security module.
	Key *string `json:"key,omitempty"`
	// Value of the external metadata property.
	Value *string `json:"value,omitempty"`
}

// FilterEndpointAgentsResponse is generated from the OpenAPI specification.
type FilterEndpointAgentsResponse struct {
	Links  PaginationNextLink `json:"_links,omitempty"`
	Agents []EndpointAgent    `json:"agents,omitempty"`
	// The total number of agents.
	TotalAgents *int `json:"totalAgents,omitempty"`
}

// InterfaceProfile is generated from the OpenAPI specification.
type InterfaceProfile struct {
	AddressProfiles []AddressProfile             `json:"addressProfiles,omitempty"`
	EthernetProfile EndpointAgentEthernetProfile `json:"ethernetProfile,omitempty"`
	HardwareType    InterfaceHardwareType        `json:"hardwareType,omitempty"`
	InterfaceName   *string                      `json:"interfaceName,omitempty"`
	WirelessProfile WirelessProfile              `json:"wirelessProfile,omitempty"`
}

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// ListEndpointAgentsResponse is generated from the OpenAPI specification.
type ListEndpointAgentsResponse struct {
	Links  PaginationNextAndSelfLink `json:"_links,omitempty"`
	Agents []EndpointAgent           `json:"agents,omitempty"`
	// The total number of agents.
	TotalAgents *int `json:"totalAgents,omitempty"`
}

// PaginationNextAndSelfLink A links object containing a related link for
// forward pagination.
type PaginationNextAndSelfLink struct {
	Next Link `json:"next,omitempty"`
	Self Link `json:"self,omitempty"`
}

// PaginationNextLink A links object containing a related link for forward
// pagination.
type PaginationNextLink struct {
	Next Link `json:"next,omitempty"`
}

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self Link `json:"self,omitempty"`
}

// WirelessProfile is generated from the OpenAPI specification.
type WirelessProfile struct {
	Bssid   *string `json:"bssid,omitempty"`
	Channel *int    `json:"channel,omitempty"`
	PhyMode *string `json:"phyMode,omitempty"`
	Rssi    *int    `json:"rssi,omitempty"`
	Ssid    *string `json:"ssid,omitempty"`
}
