// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.97)

package http_server_endpoint_instant_scheduled_tests

// AccountGroupId A unique identifier associated with your account group. You
// can retrieve your `AccountGroupId` from the `/account-groups` endpoint.
type AccountGroupId string

// EndpointAgentLabels Deprecated. Use `tagIds` instead. List of endpoint agent
// label IDs (obtained from `/endpoint/labels` endpoint), required when
// `agentSelectorType` is set to `agent-labels`.
type EndpointAgentLabels []string

// EndpointAgentLabelsSelectorConfig Agent labels selection object.
type EndpointAgentLabelsSelectorConfig struct {
	AgentSelectorType   EndpointAgentLabelsSelectorType `json:"agentSelectorType"`
	EndpointAgentLabels EndpointAgentLabels             `json:"endpointAgentLabels,omitempty"`
	MaxMachines         EndpointTestMaxMachines         `json:"maxMachines,omitempty"`
	TagIds              TagIds                          `json:"tagIds,omitempty"`
}

// EndpointAgentLabelsSelectorType is generated from the OpenAPI specification.
type EndpointAgentLabelsSelectorType string

// EndpointAgentTagsSelectorConfig Agent tags selection object.
type EndpointAgentTagsSelectorConfig struct {
	AgentSelectorType   EndpointAgentTagsSelectorType `json:"agentSelectorType"`
	EndpointAgentLabels EndpointAgentLabels           `json:"endpointAgentLabels,omitempty"`
	MaxMachines         EndpointTestMaxMachines       `json:"maxMachines,omitempty"`
	TagIds              TagIds                        `json:"tagIds,omitempty"`
}

// EndpointAgentTagsSelectorType is generated from the OpenAPI specification.
type EndpointAgentTagsSelectorType string

// EndpointAllAgentsSelectorConfig Any agent selection object.
type EndpointAllAgentsSelectorConfig struct {
	AgentSelectorType EndpointAllAgentsSelectorType `json:"agentSelectorType"`
	MaxMachines       EndpointTestMaxMachines       `json:"maxMachines,omitempty"`
}

// EndpointAllAgentsSelectorType is generated from the OpenAPI specification.
type EndpointAllAgentsSelectorType string

// EndpointHttpServerInstantTest is generated from the OpenAPI specification.
type EndpointHttpServerInstantTest struct {
	AgentSelectorType     EndpointTestAgentSelectorType `json:"agentSelectorType,omitempty"`
	Agents                EndpointTestAgents            `json:"agents,omitempty"`
	AuthType              EndpointTestAuthType          `json:"authType,omitempty"`
	EndpointAgentLabels   EndpointAgentLabels           `json:"endpointAgentLabels,omitempty"`
	HasPathTraceInSession TestHasPathTraceInSession     `json:"hasPathTraceInSession,omitempty"`
	HasPing               TestRequestHasPing            `json:"hasPing,omitempty"`
	HasTraceroute         TestRequestHasTraceRoute      `json:"hasTraceroute,omitempty"`
	// Maximum amount of time in milliseconds the agents wait before a request
	// times out.
	HttpTimeLimit       *int                    `json:"httpTimeLimit,omitempty"`
	IpVersion           EndpointIpVersionIn     `json:"ipVersion,omitempty"`
	MaxMachines         EndpointTestMaxMachines `json:"maxMachines,omitempty"`
	NetworkMeasurements TestNetworkMeasurements `json:"networkMeasurements,omitempty"`
	Password            TestPassword            `json:"password,omitempty"`
	Protocol            EndpointTestProtocol    `json:"protocol,omitempty"`
	SslVersionID        TestSslVersionId        `json:"sslVersionId,omitempty"`
	TagIds              TagIds                  `json:"tagIds,omitempty"`
	// Response time target in milliseconds.
	TargetResponseTime *int                      `json:"targetResponseTime,omitempty"`
	TcpProbeMode       TestProbeMode             `json:"tcpProbeMode,omitempty"`
	TestName           TestName                  `json:"testName"`
	URL                EndpointHttpServerTestUrl `json:"url"`
	Username           TestUsername              `json:"username,omitempty"`
	// Flag indicating if a certificate should be verified.
	VerifyCertificate *bool `json:"verifyCertificate,omitempty"`
}

// EndpointHttpServerTest is generated from the OpenAPI specification.
type EndpointHttpServerTest struct {
	Links                 EndpointTestLinks           `json:"_links,omitempty"`
	AgentSelectorConfig   EndpointAgentSelectorConfig `json:"agentSelectorConfig,omitempty"`
	AID                   AccountGroupId              `json:"aid,omitempty"`
	AuthType              EndpointTestAuthType        `json:"authType,omitempty"`
	CreatedDate           TestCreatedDate             `json:"createdDate,omitempty"`
	FollowRedirects       TestFollowRedirects         `json:"followRedirects,omitempty"`
	HasPathTraceInSession TestHasPathTraceInSession   `json:"hasPathTraceInSession,omitempty"`
	HttpTargetTime        TestHttpTargetTime          `json:"httpTargetTime,omitempty"`
	// Maximum amount of time in milliseconds the agents wait before a request
	// times out.
	HttpTimeLimit *int                 `json:"httpTimeLimit,omitempty"`
	HttpVersion   TestHttpVersion      `json:"httpVersion,omitempty"`
	Interval      TestInterval         `json:"interval,omitempty"`
	IpVersion     EndpointIpVersionOut `json:"ipVersion,omitempty"`
	IsEnabled     TestIsEnabled        `json:"isEnabled,omitempty"`
	IsPrioritized TestIsPrioritized    `json:"isPrioritized,omitempty"`
	IsSavedEvent  TestIsSavedEvent     `json:"isSavedEvent,omitempty"`
	Labels        TestLabels           `json:"labels,omitempty"`
	// UTC last modification date (ISO date-time format).
	ModifiedDate        *string                 `json:"modifiedDate,omitempty"`
	NetworkMeasurements TestNetworkMeasurements `json:"networkMeasurements,omitempty"`
	Port                EndpointTestPort        `json:"port,omitempty"`
	Protocol            EndpointTestProtocol    `json:"protocol,omitempty"`
	// Target domain name or IP address.
	Server       *string               `json:"server,omitempty"`
	SslVersion   TestSslVersion        `json:"sslVersion,omitempty"`
	SslVersionID TestSslVersionId      `json:"sslVersionId,omitempty"`
	TcpProbeMode TestProbeModeResponse `json:"tcpProbeMode,omitempty"`
	// Each test is assigned a unique ID to access test data from other endpoints.
	TestID   *string                `json:"testId,omitempty"`
	TestName TestName               `json:"testName,omitempty"`
	Type     EndpointHttpServerType `json:"type"`
	URL      EndpointTestResultUrl  `json:"url,omitempty"`
	UseNtlm  TestUseNtlm            `json:"useNtlm,omitempty"`
	Username TestUsername           `json:"username,omitempty"`
	// Flag indicating if a certificate should be verified.
	VerifyCertificate *bool `json:"verifyCertificate,omitempty"`
}

// EndpointHttpServerTestUrl The test target URL. You can optionally specify
// the protocol (`http` or `https`). - **Default Protocol:** If no protocol is
// specified, `https` is used by default. - **Port Number:** To specify a port,
// append it to the URL with a colon after the hostname or IP address (e.g.,
// `https://example.com:443`). - If no port is specified in the URL, the `port`
// is determined by the default for protocol (HTTP: 80, HTTPS: 443).
type EndpointHttpServerTestUrl string

// EndpointHttpServerType Type of test being queried.
type EndpointHttpServerType string

// EndpointIpVersionOut For reading current network test configurations, the IP
// version of the test. Values include V4_ONLY, V6_ONLY, V6_PREFER, and
// OS_DEFAULT.
type EndpointIpVersionOut string

// EndpointSpecificAgentsSelectorConfig Specific agents selection object.
type EndpointSpecificAgentsSelectorConfig struct {
	AgentSelectorType EndpointSpecificAgentsSelectorType `json:"agentSelectorType"`
	Agents            EndpointTestAgents                 `json:"agents,omitempty"`
	MaxMachines       EndpointTestMaxMachines            `json:"maxMachines,omitempty"`
}

// EndpointSpecificAgentsSelectorType is generated from the OpenAPI specification.
type EndpointSpecificAgentsSelectorType string

// EndpointTestAgents List of endpoint agent IDs (obtained from
// `/endpoint/agents` endpoint). Required when `agentSelectorType` is set to
// `specific-agent`.
type EndpointTestAgents []string

// EndpointTestLinks A list of links that can be accessed to get more
// information.
type EndpointTestLinks struct {
	Self        EndpointTestSelfLink `json:"self,omitempty"`
	TestResults ScheduledTestResults `json:"testResults,omitempty"`
}

// EndpointTestMaxMachines Maximum number of agents which can execute the test.
type EndpointTestMaxMachines int

// EndpointTestPort Port number.
type EndpointTestPort int

// EndpointTestResultUrl The test target URL.
type EndpointTestResultUrl string

// EndpointTestSelfLink is generated from the OpenAPI specification.
type EndpointTestSelfLink struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// ScheduledTestResults Reference to the test results.
type ScheduledTestResults []Link

// TagIds List of tag IDs (obtained from `/tags` endpoint).
type TagIds []string

// TestCreatedDate UTC created date (ISO date-time format).
type TestCreatedDate string

// TestFollowRedirects To disable following HTTP/301 or HTTP/302 redirect
// directives, set this parameter to `false`.
type TestFollowRedirects bool

// TestHasPathTraceInSession Enables "in session" path trace. When enabled,
// this option initiates a TCP session with the target server and sends path
// trace packets within the established TCP session.
type TestHasPathTraceInSession bool

// TestHttpTargetTime Target time for HTTP server completion, specified in
// milliseconds.
type TestHttpTargetTime int

// TestHttpVersion HTTP protocol version. Set to '2' to prefer HTTP/2, or '1'
// to use only HTTP/1.1.
type TestHttpVersion int

// TestIsEnabled Indicates if test is enabled.
type TestIsEnabled bool

// TestIsPrioritized Indicates whether the test should be prioritized when the
// number of tests assigned to an agent exceeds the license limit.
type TestIsPrioritized bool

// TestIsSavedEvent Indicates if the test is a saved event. **Note**: **Saved
// Events** are now called **Private Snapshots** in the user interface. This
// change does not affect API.
type TestIsSavedEvent bool

// TestLabel is generated from the OpenAPI specification.
type TestLabel struct {
	// Value indicating if the label in question is BuiltIn (Account Admin,
	// Organization Admin, Regular User).
	IsBuiltin *bool `json:"isBuiltin,omitempty"`
	// Label ID.
	LabelID *string `json:"labelId,omitempty"`
	// Name of the label.
	Name *string `json:"name,omitempty"`
}

// TestLabels Labels to which the test is assigned. This field is not returned
// for Instant Tests.
type TestLabels []TestLabel

// TestName Name of the test.
type TestName string

// TestNetworkMeasurements Enable or disable network measurements. Set to true
// to enable or false to disable network measurements.
type TestNetworkMeasurements bool

// TestPassword Password for Basic/NTLM authentication.
type TestPassword string

// TestRequestHasPing Optional flag indicating if the test should run ping.
type TestRequestHasPing bool

// TestRequestHasTraceRoute Optional flag indicating if the test should run
// traceroute.
type TestRequestHasTraceRoute bool

// TestSslVersion Reflects the verbose SSL protocol version used by a test.
type TestSslVersion string

// TestUseNtlm Set to true to use NTLM, false to use Basic Authentication.
// Requires username and password to be set.
type TestUseNtlm bool

// TestUsername Username for Basic/NTLM authentication.
type TestUsername string
