// Code generated by scripts/openapi/GenerateServices from the ThousandEyes
// OpenAPI specification. DO NOT EDIT.
//
// Source: api.yaml (API version 7.0.100)

package webhook_operations

// Header is generated from the OpenAPI specification.
type Header struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// Link A hyperlink from the containing resource to a URI.
type Link struct {
	// Its presence indicates that the link is to be deprecated at a future date.
	Deprecation *string `json:"deprecation,omitempty"`
	// Its value is either a URI [RFC3986] or a URI template [RFC6570].
	Href string `json:"href"`
	// Indicates the language of the target resource
	Hreflang *string `json:"hreflang,omitempty"`
	// Its value may be used as a secondary key for selecting link objects that
	// share the same relation type.
	Name *string `json:"name,omitempty"`
	// A URI that hints about the profile of the target resource.
	Profile *string `json:"profile,omitempty"`
	// Should be true when the link object's "href" property is a URI template.
	Templated *bool `json:"templated,omitempty"`
	// Intended for labelling the link with a human-readable identifier
	Title *string `json:"title,omitempty"`
	// Used as a hint to indicate the media type expected when dereferencing the
	// target resource.
	Type *string `json:"type,omitempty"`
}

// SelfLinks A links object containing the self link.
type SelfLinks struct {
	Self *Link `json:"self,omitempty"`
}

// WebhookOperation is generated from the OpenAPI specification.
type WebhookOperation struct {
	Links    *SelfLinks        `json:"_links,omitempty"`
	Category OperationCategory `json:"category"`
	Enabled  *bool             `json:"enabled,omitempty"`
	Headers  []Header          `json:"headers,omitempty"`
	ID       *string           `json:"id,omitempty"`
	Name     string            `json:"name"`
	Path     *string           `json:"path,omitempty"`
	// Handlebars template for the payload.
	Payload *string `json:"payload,omitempty"`
	// Handlebars template for the query params.
	QueryParams *string         `json:"queryParams,omitempty"`
	Status      OperationStatus `json:"status"`
	Type        OperationType   `json:"type,omitempty"`
}

// ResourceWebhookOperations is generated from the OpenAPI specification.
type ResourceWebhookOperations struct {
	Links *SelfLinks         `json:"_links,omitempty"`
	Items []WebhookOperation `json:"items,omitempty"`
}
